(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 640,
	height: 1500,
	fps: 30,
	color: "#000000",
	manifest: [
		{src:"images/aniUI01_Bitmap1.png", id:"aniUI01_Bitmap1"},
		{src:"images/aniUI01_Bitmap2.png", id:"aniUI01_Bitmap2"},
		{src:"images/aniUI01_Bitmap3.png", id:"aniUI01_Bitmap3"},
		{src:"images/aniUI01_Bitmap4.png", id:"aniUI01_Bitmap4"},
		{src:"images/bj.jpg", id:"bj"},
		{src:"images/d1.png", id:"d1"},
		{src:"images/duquzhong01.png", id:"duquzhong01"},
		{src:"images/dx.png", id:"dx"},
		{src:"images/greetpic1.png", id:"greetpic1"},
		{src:"images/greetpic2.png", id:"greetpic2"},
		{src:"images/greetpic3.png", id:"greetpic3"},
		{src:"images/greetpic4.png", id:"greetpic4"},
		{src:"images/lg.jpg", id:"lg"},
		{src:"images/role1_Bitmap1.png", id:"role1_Bitmap1"},
		{src:"images/role1_Bitmap10.png", id:"role1_Bitmap10"},
		{src:"images/role1_Bitmap11.png", id:"role1_Bitmap11"},
		{src:"images/role1_Bitmap12.png", id:"role1_Bitmap12"},
		{src:"images/role1_Bitmap13.png", id:"role1_Bitmap13"},
		{src:"images/role1_Bitmap2.png", id:"role1_Bitmap2"},
		{src:"images/role1_Bitmap3.png", id:"role1_Bitmap3"},
		{src:"images/role1_Bitmap4.png", id:"role1_Bitmap4"},
		{src:"images/role1_Bitmap5.png", id:"role1_Bitmap5"},
		{src:"images/role1_Bitmap6.png", id:"role1_Bitmap6"},
		{src:"images/role1_Bitmap7.png", id:"role1_Bitmap7"},
		{src:"images/role1_Bitmap8.png", id:"role1_Bitmap8"},
		{src:"images/role1_Bitmap9.png", id:"role1_Bitmap9"},
		{src:"images/role1_eye.png", id:"role1_eye"},
		{src:"images/role1_p6.png", id:"role1_p6"},
		{src:"images/role1_p7.png", id:"role1_p7"},
		{src:"images/role2_Bitmap1.png", id:"role2_Bitmap1"},
		{src:"images/role2_Bitmap10.png", id:"role2_Bitmap10"},
		{src:"images/role2_Bitmap11.png", id:"role2_Bitmap11"},
		{src:"images/role2_Bitmap12.png", id:"role2_Bitmap12"},
		{src:"images/role2_Bitmap2.png", id:"role2_Bitmap2"},
		{src:"images/role2_Bitmap3.png", id:"role2_Bitmap3"},
		{src:"images/role2_Bitmap4.png", id:"role2_Bitmap4"},
		{src:"images/role2_Bitmap5.png", id:"role2_Bitmap5"},
		{src:"images/role2_Bitmap6.png", id:"role2_Bitmap6"},
		{src:"images/role2_Bitmap7.png", id:"role2_Bitmap7"},
		{src:"images/role2_Bitmap8.png", id:"role2_Bitmap8"},
		{src:"images/role2_Bitmap9.png", id:"role2_Bitmap9"},
		{src:"images/s1btn.jpg", id:"s1btn"},
		{src:"images/s2btn.jpg", id:"s2btn"},
		{src:"images/t1.png", id:"t1"},
		{src:"images/t2.png", id:"t2"},
		{src:"images/wenzi.png", id:"wenzi"}
	]
};



// symbols:



(lib.aniUI01_Bitmap1 = function() {
	this.initialize(img.aniUI01_Bitmap1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,65,79);


(lib.aniUI01_Bitmap2 = function() {
	this.initialize(img.aniUI01_Bitmap2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,229,259);


(lib.aniUI01_Bitmap3 = function() {
	this.initialize(img.aniUI01_Bitmap3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,15,22);


(lib.aniUI01_Bitmap4 = function() {
	this.initialize(img.aniUI01_Bitmap4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,83,12);


(lib.bj = function() {
	this.initialize(img.bj);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,640,960);


(lib.d1 = function() {
	this.initialize(img.d1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,640,1500);


(lib.duquzhong01 = function() {
	this.initialize(img.duquzhong01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,315,36);


(lib.dx = function() {
	this.initialize(img.dx);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,640,320);


(lib.greetpic1 = function() {
	this.initialize(img.greetpic1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,335,132);


(lib.greetpic2 = function() {
	this.initialize(img.greetpic2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,335,132);


(lib.greetpic3 = function() {
	this.initialize(img.greetpic3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,335,132);


(lib.greetpic4 = function() {
	this.initialize(img.greetpic4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,335,132);


(lib.lg = function() {
	this.initialize(img.lg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,225,112);


(lib.role1_Bitmap1 = function() {
	this.initialize(img.role1_Bitmap1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,229,118);


(lib.role1_Bitmap10 = function() {
	this.initialize(img.role1_Bitmap10);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,114,49);


(lib.role1_Bitmap11 = function() {
	this.initialize(img.role1_Bitmap11);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,26,8);


(lib.role1_Bitmap12 = function() {
	this.initialize(img.role1_Bitmap12);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,104,22);


(lib.role1_Bitmap13 = function() {
	this.initialize(img.role1_Bitmap13);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,102,29);


(lib.role1_Bitmap2 = function() {
	this.initialize(img.role1_Bitmap2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,162,168);


(lib.role1_Bitmap3 = function() {
	this.initialize(img.role1_Bitmap3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,22,95);


(lib.role1_Bitmap4 = function() {
	this.initialize(img.role1_Bitmap4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,53,60);


(lib.role1_Bitmap5 = function() {
	this.initialize(img.role1_Bitmap5);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,47,63);


(lib.role1_Bitmap6 = function() {
	this.initialize(img.role1_Bitmap6);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,43,23);


(lib.role1_Bitmap7 = function() {
	this.initialize(img.role1_Bitmap7);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,29,15);


(lib.role1_Bitmap8 = function() {
	this.initialize(img.role1_Bitmap8);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,30,16);


(lib.role1_Bitmap9 = function() {
	this.initialize(img.role1_Bitmap9);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,86,25);


(lib.role1_eye = function() {
	this.initialize(img.role1_eye);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,114,49);


(lib.role1_p6 = function() {
	this.initialize(img.role1_p6);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,413,465);


(lib.role1_p7 = function() {
	this.initialize(img.role1_p7);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,884,665);


(lib.role2_Bitmap1 = function() {
	this.initialize(img.role2_Bitmap1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,235,129);


(lib.role2_Bitmap10 = function() {
	this.initialize(img.role2_Bitmap10);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,8,8);


(lib.role2_Bitmap11 = function() {
	this.initialize(img.role2_Bitmap11);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,158,194);


(lib.role2_Bitmap12 = function() {
	this.initialize(img.role2_Bitmap12);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,61,100);


(lib.role2_Bitmap2 = function() {
	this.initialize(img.role2_Bitmap2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,30,20);


(lib.role2_Bitmap3 = function() {
	this.initialize(img.role2_Bitmap3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,30,20);


(lib.role2_Bitmap4 = function() {
	this.initialize(img.role2_Bitmap4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,91,25);


(lib.role2_Bitmap5 = function() {
	this.initialize(img.role2_Bitmap5);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,102,26);


(lib.role2_Bitmap6 = function() {
	this.initialize(img.role2_Bitmap6);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,51,93);


(lib.role2_Bitmap7 = function() {
	this.initialize(img.role2_Bitmap7);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,40,73);


(lib.role2_Bitmap8 = function() {
	this.initialize(img.role2_Bitmap8);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,30,103);


(lib.role2_Bitmap9 = function() {
	this.initialize(img.role2_Bitmap9);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,39,23);


(lib.s1btn = function() {
	this.initialize(img.s1btn);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,105);


(lib.s2btn = function() {
	this.initialize(img.s2btn);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,105);


(lib.t1 = function() {
	this.initialize(img.t1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,618);


(lib.t2 = function() {
	this.initialize(img.t2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,618);


(lib.wenzi = function() {
	this.initialize(img.wenzi);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,535,369);


(lib.role_001 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role1_p6();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,413,465);


(lib.pic_001 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role1_p7();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,884,665);


(lib.greetMc6 = function() {
	this.initialize();

	// 图层 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAEFOQAhgfARg4IgxAAIAAghIEhAAIAAAhIh6AAIAAASIBkAAIAAAgIhkAAIAAATIAvAAIBMAAIgMAiIhLAAIgqgBQhEAAgegfQgOAYgQAQIgigYgABcEFIgJAZQATAUAfAGIAAhBIhOAAgAsRFmIARhPIAqAAIgYBPgATYFmIAAiNIgXAjQgGgegIgZQAmg/AXhDIAoAKQgKAggNAeIAADbgAisFKQASgTAMgZIgYASIgagkIAAA1QAAANgHAJQgIAJgQAAIgiABIgFgYIgggLQANgkAIgnIAiAJQgJAkgIAbQAVABADgEQADgEAAgFIAAhDIgyAAIAAhYIB8AAIAABYIglAAIAAAaIAWgRIAeAkQATgsACg8IgZAAIAAglIAaAAIAAhIIAnAAIgBBIIBJAAIAAAlIhKAAIgBAUIAcAAIAABwQAAAHAHAAQAFAAACgGQACgGACgqIAhAKQgGA3gEAIQgEAJgIAEQgIAEgMAAIgLAAQghAAAAgkIAAheQgLBTgpA1QgPgPgQgNgAjzDOIA1AAIAAgcIg1AAgAzjFmIAAgPIh5AAIAAAPIglAAIAAjZIA4AAIAAgcIg9AAIAAgEIgaAcIgtgnIAZgaQAdAVARAOIAAgbIDRAAIAAAhIhAAAIAAAcIA3AAIAADZgA1cE3IB5AAIAAgUIh5AAgA1cEEIB5AAIAAgRIgSAAQghAAAAgjIAAgkIgTAAQgBAwgZAhQgOgOgLgJgA1cDhQARgZABgcIgSAAgAz1DJQAAALALAAIAHAAIAAgoIgSAAgA0oCNIASAAIAAgcIgSAAgAU4FlQgDgYgEgRQAPACAZAAQAQAAAAgTIAAhDIhYAAIAAgnIBYAAIAAgZIAygvIh3AAIAAgnICpAAIAAAqIg6A5IAAAMIBEAAIAAAnIhEAAIAABUQAAAKgDAIQgDAJgHAGQgIAGgWABIgjABIgNAAgAyqFCQAPgZAGgfQAGgfAAg9IAAheIDvAAIAABaIjGAAIAAASIDTAAIgCB2QAAAWgHAKQgGAKgJAEQgKAFhAAAQgDgSgFgUIApABQAJAAAFgDQAFgEABgFQABgFABgwIAAghIipAAQAABWgjAxQgTgWgNgNgAxmCJICcAAIAAgXIicAAgAmeE4QgZARgcAPQgJgRgPgSQAigOAdgUQgIghgDg0Ig7AAIAAAgIAygHIgBAYIAAAQIgxAGIAAA6QAAAQgHAJQgIAIgTACQgTABgZAAQgFgagGgNQAOACAPAAIAGAAQAFAAADgEQACgEAAgIIAAgjIguAHIgHgpIA1gGIAAglIg1AAIAAgmIA1AAIAAgcIgpADIgFgmQBBgDA9gJIAJAkIgtAGIAAAhIA5AAIgEhTIApAAIADBTIBgAAIAAAmIheAAQACAhAEAYQAagYAUgeIAgAaQgdAlglAeQAMAcAOAAIAFgBQACgBAEgPQAEgPADgVQAUAOAPAGQgIAsgLAQQgKAQgTAAQgqAAgWgtgAFSFiIAAiBIgWAiIgMg4QAjg7AXhLIAnANQgLAhgNAgIAADPgAMBE1QAWACAYAAQAHAAAFgBQAGgCADgDQADgEABgEQACgEAAggIACg8IAAgtIgzAAQgJAUgLAUQgOgJgVgJIAACuIgpAAIAAgVIgpAAIAAAXIgpAAIAAjuIAfAAQAIgdAEgSIArAHIgNAoIAyAAIAAA5QAYgoAVhAIApAKIgOAmIBLAAIgDCpQgBAbgDALQgEALgIAHQgIAHgPACQgOADgxAAQgEgagHgTgAKQElIApAAIAAgyIgpAAgAKQDMIApAAIAAgyIgpAAgA3SFVQAQgtAQhDQAYAJAPAEQgPBBgQAuIgogMgAQDE1IBOACQANAAAFgEQAGgFACgGQADgHABg/IjCAAIAJhgIAuAAIgHA7IBkAAIAHhIIimAAIAAglIDYAAIgLBtIAuAAQgCBVgCAaQgCAagPAMQgPANgaABIhSABQgEgVgGgXgAG1FgQgCgRgFgUIAYABQALAAAEgDQAEgDAAgIIAAiPIApAAIAACbQAAARgHAKQgHAJgRABIggABIgOAAgAxVFFIAAhXIB5AAIAABJIhTAAIAAAOgAwvEcIAuAAIAAgUIguAAgAINDRIAkgKQAMAgAWBEIgpANQgPg8gOgrgAGCEmQAUgrARg3IAlAKQgPA4gWAwQgRgIgUgIgAOKEeIAAgmIDTAAIAAAmgALuDWIAigXQAVAZAZAkIglAZQgXglgUgagA3WCvIAYgdQAgAZATARIgbAeIgwgrgAGDCvQAcgrATg+IAqAGIgKAdIB6AAIAAAiIgNA0IgngIIALgpIhhAAQgPAhgSAZIgegZgAAnDIIAAh7IDdAAIAAB7gABPCnICNAAIAAgQIiNAAgABPB9ICNAAIAAgPIiNAAgAmKBlIAZgZQAiAcARARIgcAaQgVgYgbgWgAhMBgIAYgVQATASATAVIgaAXQgQgUgUgVgAkjCEIAAgiIA4AAIgHgaIArgFIAHAfIAzAAIAAAigAn6hiQBugcA7g6IAdAYQhBBChvAfIgWgjgALJhCIARhPIAqAAIgYBPgAsRhCIARhPIAqAAIgYBPgAHMhDIAAgxIgvAAIAAgfQgLAQgNAQIgWghIAABRIgjAAIAAiBQgJARgKAOQgEgbgGgcQAXgsAZhbIAmAKQgKAlgMAgIAAB4QAvgxAXhCIg1AAIAAglIBMAAIAAgvIAnAAIAAAvIBUAAIAAAlIg/AAQAXA+A0AwIgZAqQgMgMgKgPIAAAeIgxAAIAAAxgAHziZIAsAAQgbgpgRg7gAGhiZIArAAIAAhlQgOA3gdAugA3WhmQApgTATgVQATgUACglIg1AAIAAiQIDoAAIAACQIg7AAIAABDQAAAWAQAAIAMAAQAJAAAEgHQADgIAFglIApAPQgGAggFAPQgHAcgoAAIgfAAQgsAAAAgwIAAhPIgiAAQgDAygWAeQgWAdgwAXQgKgOgTgVgA2RjsICVAAIAAhGIiVAAgAVPhsIAvACQAQAAAAgRIAAgEIh9AAIAAA7IgqAAIAAiBQgTAUgWASIgKguQArglAbgvIhEAAIAAgkIBXAAQAHgQAFgQIAuAHIgKAZICYAAIAAAkIiqAAIgNAWICbAAIAACfQAAASgJAKQgJAKgQABQgPACguAAQgEgUgHgVgAURifIB9AAIAAgVIh9AAgAURjUIB9AAIAAgVIh9AAgAkBhDIAAkdIAiAAIAAAzIAdAMIgKAiIgTgKIAADGgAwuhDIAAhXQglAyhCAgIgZgkQA7gXAggjIhMAAIANheIBkAAIAAgaIhrAAIAAgjIA3AAIgQgVIAkgPIAcAkIAzAAQANgSAMgSIAoAPIgSAVIAzAAIAABfIhoAAIAAAaIB2AAIgDA8QgBAWgMALQgLAKgQACQgQACglgBQgEgTgGgTQASACAUAAQALAAAIgFQAIgFAAgaIhNAAIAABjgAxyjIIBEAAIAAgaIhBAAgAwFkEIA/AAIAAgaIg/AAgAOmhEIAAhEIgdAAIAAgjIAdAAIAAh0IBgAAIAAgUIh2AAIAAgkIEUAAIAAAkIh2AAIAAAUIBgAAIAAB0IAdAAIAAAjIgdAAIAAAVQAAAUgJALQgIALgOACQgPACgrAAQgDgWgEgRIAkACQAOAAADgGQADgGAAgHIAAgLIiYAAIAABEgAQuirIA4AAIAAgYIg4AAgAPOirIA4AAIAAgYIg4AAgAQujlIA4AAIAAgYIg4AAgAPOjlIA4AAIAAgYIg4AAgAi9hEIAAiUICrAAIAACTIgoAAIAAgOIhbAAIAAAPgAiVhyIBbAAIAAgUIhbAAgAiVikIBbAAIAAgVIhbAAgACdhFIgHgmQAUACAYAAQAQAAAAgRIAAgWQhPAqhrAeQgMgagJgNQBVgQBBgcIiTAAIAAgjIAiAAIAAiMIBBAAIAOgbIAuAGIgOAVIBjAAIAAB3IAXgTIAYAcQgVASgaAQIAAAzQAAAwgsAAgABQi+ICCAAIAAgSIiCAAgABQjqICCAAIAAgSIiCAAgABQkVICCAAIAAgSIiCAAgApSiBIAhgHIAAhCIgbAAIAAgpIAbAAIAAg1IgeAAIAAgoIBmAAIAAAoIggAAIAAA1IAWAAIAAApIgWAAIAAA4IAcgIQgBATABAWQgzANgsAOgAnpigQBIgbAygrIAcAYQg4AvhHAhQgIgQgPgSgAnpjbQAxgVAngiIAbAYQgpAkg0AbQgHgLgPgVgAkpjUQAJgrAEgsIAYACQgFAxgHApIgZgFgAjIjoIAAgfIAjAAIAAgbIgeAAIAAgfIAeAAIAAghIAoAAIAAAhIAsAAIAAghIAoAAIAAAhIAdAAIAAAfIgdAAIAAAbIAkAAIAAAfgAh9kHIAsAAIAAgbIgsAAgAn+kSQA3ggAegyIArAAIgEAHQAjAuAyAXIgVAkQg3gdgegtQgeAvg1AhQgJgTgLgRg");
	this.shape.setTransform(167.4,60);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#993300").s().p("A6KKUIAA0nMA0VAAAIAAUng");
	this.shape_1.setTransform(167.5,79,1,1,0,0,0,0,13);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,335.1,150.8);


(lib.greetMc5 = function() {
	this.initialize();

	// 图层 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADrF0IAAgmQAJAFAMAAQATAAAIgSIAJgWIhCihIA1AAIAgBlIAEAVIABAAQABgIAEgMIAghmIAvAAIhDCwQgXA+gvAAQgSAAgKgEgAAAF2IAAjsIAuAAIAAAYIAAAAQATgcAiAAQAfAAARAVQASAWAAAlQAAApgVAYQgUAZghAAQgdAAgQgYIAAAAIAABegAA3C2QgKANAAATIAAAOQAAARAJALQAKALAPAAQARAAAKgNQAKgOAAgZQAAgtgjAAQgQAAgKAMgAj6F2IAAjsIAwAAIAAAYIAAAAQATgcAiAAQAfAAARAVQASAWAAAlQAAApgVAYQgUAZghAAQgdAAgQgYIAAAAIAABegAjBC2QgKANAAATIAAAOQAAARAJALQAKALAPAAQARAAAKgNQAKgOAAgZQAAgtgjAAQgQAAgKAMgAMjEzQATgmAAhIIAmAAQAAAagCAWQAHASANAMIAAhaIhKAAIAAgkIA5AAIAAgbIgvAAIAAgkIAvAAIAAglIAoAAIAAAlIAsAAIAAAkIgsAAIAAAbIA0AAIAAAkIglAAIAAAhIAhAAIAAAkIghAAIAAAlQAPACAuAAIB2gCQgHATgHAXQh1AAgvgDQgugDgVghQgGAagKAUIgfghgAw8EzQATgmAAhIIAlAAQAAAagCAWQAIASANAMIAAhaIhKAAIAAgkIA5AAIAAgbIgvAAIAAgkIAvAAIAAglIAoAAIAAAlIArAAIAAAkIgrAAIAAAbIA0AAIAAAkIglAAIAAAhIAhAAIAAAkIghAAIAAAlQAOACAvAAIB2gCQgIATgGAXQh1AAgvgDQgvgDgUghQgGAagKAUIgfghgAU0EuIAtACQARAAAAgSIAAi+IiFAAIAAggICsAAIAADYQAAA2gmADQggACgXAAQgEgWgEgPgASNFTIAAjpIAnAAIAADpgAUBFBIAAhtIgcAAIAABQIghAAIAAhvIA9AAIAAgYIhFAAIAAggIBFAAIgHgRIAngKIAJAbIBBAAIAAAgIhGAAIAAAYIA+AAIAABJQgBAmgjAAIgUgBIgFghIASABQAJAAAAgOIAAghIgcAAIAABtgAnXEjQgOgOAAgWQAAgvA3gHIAtgGQAAgdgeAAQgdAAgZASIAAgkQALgHASgDQASgEAOAAQBDAAAABEIAABiIgsAAIAAgYIgBAAQgRAcggAAQgXAAgNgNgAmgDiQgZAEAAAUQAAAJAGAFQAGAGALAAQAOAAAJgLQAKgKAAgPIAAgMgApjEsIAAhdQAAglgbAAQgOAAgIALQgJAKAAAQIAABdIgwAAIAAjwIAwAAIAABmIAAAAQATgcAfAAQA3AAAABCIAABkgAPqEUQgoAAAAgqIAAhbIBLAAIAAgqIhRAAIAAgkIB4AAIAAByIhKAAIAAAwQAAAOAPAAIANAAQAMAAAEgHQADgGACgmQAYAKAQAGQgEAigFALQgJAZgkAAgAt2EUQgnAAAAgqIAAhbIBKAAIAAgqIhQAAIAAgkIB4AAIAAByIhLAAIAAAwQAAAOAPAAIAOAAQALAAAEgHQAEgGABgmQAZAKAQAGQgFAigFALQgIAZglAAgAHKDYIAAgsIEbAAIAAAsgA2VDYIAAgsIEbAAIAAAsgASfBHIAcgXIAnAnIgfAaQgQgVgUgVgA2Wh0QA7ghAFhEIhCAAIAAgmIBCAAIAAg8Ig1AFIgGgnQBRgGBMgLIAJAmIhAAIIAABBIBQAAIAAh1IArAAIAAB1IA5AAIAAAmIg5AAIAACCIgrAAIAAiCIhQAAQgDBZhFAuQgRgTgSgPgAj7hrQAegeAAg2IAAhlQBDgGAqgNIAQAiQgkAIgzAFIAAAgIBYAAIAAAiIgXAAIAABxIgmAAIAAhxIgbAAQAABIgiArQgQgMgSgMgAreh9QAkg0ABhuIghAAIAAgmIAiAAIABgxIAmAAIgBAxIBDAAIgEC7QgBAVgIAKQgIALgLADQgMACgiAAIgKgsIAeACQAHAAAEgDQADgDABgGQABgFABgnIAChiIgdAAQgBCLgzBBIgXgqgARkhUIARhPIApAAIgYBPgAC6hUIAAgKIiYAAIAAAKIgmAAIAAhKIDlAAIAABKgAAih3ICYAAIAAgOIiYAAgANuh5QgWAUgcAQIgPgYIAAAYIgmAAIAAkWICjAAIgCAzQgBAUgMALQgLAKgUABIgxgBQgCgPgGgVQAaACAQAAQALAAAFgEQAEgFAAgOIhUAAIAABHICBAAIAAAgQgNAqgaAiQAYAPAdAKIgYAnQgegOgYgWgAMth/QAVgKARgMQgUgYgPgdIAZgTQAOAcAUAUQASgWAJgcIhZAAgAvEhpQAcgmATgtIAgAPQgZA2gXAiQgTgNgMgHgAvqhVIAAgvIhLAOIgHgoIAPgCIAAijIgMAAIAAgjIB/AAIAAAjIgMAAIAACUIARgDIgDAlIgOADIAAA1gAwKikIAggFIAAgeIggAAgAwKjmIAgAAIAAgfIggAAgAwKklIAgAAIAAgeIggAAgAKbh+IAUABQAHAAADgDQADgDAAgIIAAg0IgfAIIgFgqIAkgHIAAg0IgfAAIAAgmIAfAAIAAg0IAmAAIAAA0IAdAAIAAAmIgdAAIAAAtIAegHQgBAaAAANIgdAHIAABMQAAAUgKAJQgLAJgoAAIgKgogAG2hWIAAhhQgkAvg9AiQgOgTgMgQQA5gYAogrIhcAAIAAgmIBBAAQgLgQgWgZIAbgUIgtAAIAAgmIBoAAIAAggIAqAAIAAAgIBqAAIAAAmIgwAAIAdAWQgTAXgRAQIBGAAIAAAmIhgAAQAoAqA7AVQgOASgMATQg/ghgjguIAABhgAHgjyIAvAAIgagWQASgRASgWIg5AAgAGhkHIgcAVIAxAAIAAg9Ig4AAQARARASAXgAtlisIAegPQAZAqAWAqIghARQgWgwgWgmgAlfh1IgJAQQgNgIgOgHQAPgaAIgWIAeALIgPAgIAPABQALAAAAgLIAAgjIg2AAIAAgdIA2AAIAAgSIg7AAIAAgdIAgAAIgLgTIAlAAIAMATIASAAIAKgTIApAAIgNATIAdAAIAAAdIg6AAIAAASIA1AAIAAAdIg1AAIAAAxQAAAagbADIghABQgBgPgFgPgAo+hbIAAkCIB2AAIAAEBIgnAAIAAgYIgoAAIAAAZgAoXibIAoAAIAAicIgoAAgAkYiXIAYgNIAVAfIgaAQQgLgWgIgMgAggirIAAgbIBAAAIgIgQIATgEIgrAAIAAg/IDeAAIAAA/IgtAAIAUAEIgOAQIBIAAIAAAbgABQjGIA4AAIAOgUIhSAAIAMAUgAAljzICRAAIAAgNIiRAAgAuxjOIAAiVICIAAIAACVgAuLjxIA9AAIAAhPIg9AAgAl5kMIAAgdIA3AAIgEgRIAWAAIAAgIIhPAAIAAghIBPAAIAAgSIAnAAIAAASIA2AAIAAgSIAnAAIAAASIBPAAIAAAhIhPAAIAAANIgnAAIAAgNIg2AAIAAANIgWAAIADAMIAyAAIAAAdgAgLkmIAAgZIBkAAIAAgNIh0AAIAAgbIB0AAIAAgQIApAAIAAAQIB2AAIAAAbIh2AAIAAANIBlAAIAAAZg");
	this.shape.setTransform(169.3,63.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#993300").s().p("A6KKUIAA0nMA0VAAAIAAUng");
	this.shape_1.setTransform(167.5,79,1,1,0,0,0,0,13);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,335.1,150.8);


(lib.greetMc4 = function() {
	this.initialize();

	// 图层 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiRE/QAmgTAagYQgUgggLgmIgJANQgLgRgOgSIAACtIgmAAIAAhVQglATgTAPIgQgmQAKgIABgOIAAiUIAkAAIAACUIAZgOIAAijIAmAAIAABvQAggvARhCIApAHQgGAUgGATIBjAAIAAAnIgUAAQgKBLgdAyQAaAZAjAOQgNASgNAXQgigUgbgcQgdAdgoAVQgJgWgNgSgAhXCgQAJAwAXAkQAUgkAKg4Ig6AAIgEAIgApfFGQAugeApgsIAiAbQguAwgtAggAysE/QAngTAagYQgUgggLgmIgJANQgLgRgOgSIAACtIgmAAIAAhVQglATgSAPIgRgmQALgIgBgOIAAiUIAlAAIAACUIAZgOIAAijIAmAAIAABvQAggvAShCIAnAHQgEAUgHATIBkAAIAAAnIgTAAQgJBLghAyQAbAZAlAOQgNASgNAXQgkgUgbgcQgcAdgoAVQgLgWgNgSgAxxCgQAJAwAWAkQAVgkAKg4Ig6AAIgEAIgAm0EVIAdgaQAzAmAnAlIghAgQgqgrgsgmgABbE/QBsgwAJhYIhvAAIAAgoIB0AAQABggAAgqIAtAAIgCBKIB4AAIAAAoIh1AAQAZBiBhAiIgiAoQhQgmgfhSQgYBMhYAuIgigmgAJzFlIAAhgIgaAAIAAATIglAAIAAgmIgWAWIgWgYIAAB1IgkAAIAAhhQgNAcgQAYIgOgwQAbggAPgqIgnAAIAAglIAoAAIAAgiIghAEQgDgUgEgOQAygGA1gHIAJAiIgkAGIAAAlIAjAAIAAAlIgjAAIAAAbIAKgKIAiAiIAAhzIA/AAIAAg5IAlAAIAAA5IA+AAIAACaIgkAAIAAgTIgaAAIAABggAKYDhIAaAAIAAg/IgaAAgAJZDhIAaAAIAAg/IgaAAgAuCFlIAAhqQgUAVgbAXQgGgcgGgVQA6gwAZgpIhHAAIAAgnIA5AAIgWgiIAigRIAbAmIgaANIAxAAIAAAkQgMAZgUAaIAAAPIAMgOQAUANAZATIgZAeIgggdIAAB2gANXFfQgEgVgHgXQAbADAYAAQAZAAgBgaIAAgvIh+AAIAAgoIB+AAIAAgjIBHgnIiwAAIAAgnID2AAIAAAnIhhA6IAAAQIB2AAIAAAoIh2AAIAAA3QAAAfgMAOQgOAPgcAAgArxFfQgogBAAgpIAAjtIAoAAIAADjQAAAPAOABIAJAAQAPgBADgLQAFgdADgcQARAJAXAHQgFAmgIAYQgHAagnABgApADzIAAijIDkAAIAACjgAoUDOICOAAIAAhZIiOAAgAIphpQAlgTAbgZQgUgfgMgnIgJAOQgKgRgOgSIAACtIgmAAIAAhUQglASgTAPIgRgmQAMgJAAgNIAAiUIAkAAIAACUIAZgOIAAijIAmAAIAABvQAggvARhCIApAHQgGAUgGATIBkAAIAAAnIgTAAQgKBLgfAyQAaAZAmAPQgNARgNAWQglgTgbgcQgdAegoATQgKgVgMgSgAJjkJQAJAxAXAkQAUgkAKg4Ig6AAIgEAHgAyVhYQAggjAegrIiiAAIAAgnIDbAAIAAAkQghAtgvA6gATjhCIARhPIAqAAIgZBPgAixhCIAAiNIhBAAIAAgnID6AAIgEBhQgCASgGALQgIAMgOADQgNAFhAAAQgEgTgGgZQAfACASABQAMAAAGgGQAHgEABgJIACgvIhfAAIAACNgADXhDIAAiMQgmAvg4AnIgegnQBdg8AjhNIhzAAIAAgpIENAAIAAApIhpAAQgJAYgOAXIAOAAIAAAiIAdgcIBgBXIgiAhQglgqg2gxIAACUgApfhxIAdgYIAAhRIgbAAIAAgnIBDAAIAAB3QAWAaAkAAIAtAAIB4gBIgNAoIingDQgUgBgQgGQgPgHgKgNIgjAkgANThEIAAhqQgWAWgZAWQgHgcgHgUQA8gwAXgpIhHAAIAAgmIA6AAIgWgjIAigRIAaAlIgZAPIAyAAIAAAkQgNAYgUAaIAAAPIAMgPQAVAOAZATIgZAdIghgcIAAB1gAsuhEIAAg+IiLAAIAAglIApAAIAAhIIgQARIgbglQAtglAYg9IAuAHIgMAYICvAAIAAAmIheAAIAAAmIBTAAIAAAlIhTAAIAAAuIBnAAIAAAlIhnAAIAAA+gAtninIA5AAIAAguIg5AAgAuFj6IBXAAIAAgmIg7AAQgNAUgPASgAPjhJQgoAAAAgqIAAjsIApAAIAADjQgBAPAOAAIAIAAQAQAAACgNQAGgcACgcQASAJAYAIQgGAlgIAYQgHAbgnAAgAnaikIAwADQAWAAAAgZIAAhVIh1AAIAAgkIB1AAIAAgxIArAAIAAAxIAqAAIAAAkIgqAAIAABhQAAAZgMANQgLAMgVABIg6ABQgDgTgIgXgAoDjzIAggZQATAXAfAoIgiAaIgwhAgAywkDIAggVQAaAbAQAWIgjAXQgZgigOgRgA0cj8QBNgjA0hFIA5AAIgKAKQAtA8BJAgIgbAjQhMglgqg8QguA8hNAoQgQgZgKgLgAhRkGIAAgZIg8AAIAAAZIgrAAIAAgZIhHAAIAAgmIBHAAIAAgfIArAAIAAAfIA8AAIAAgfIAsAAIAAAfIBEAAIAAAmIhEAAIAAAZgApWlRIAhgUQAWAfAPAYIgmAWQgQgfgQgag");
	this.shape.setTransform(167.6,62);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#993300").s().p("A6KKUIAA0nMA0VAAAIAAUng");
	this.shape_1.setTransform(167.5,79,1,1,0,0,0,0,13);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,335.1,150.8);


(lib.greetMc3 = function() {
	this.initialize();

	// 图层 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADoFGQgfAbhXAFQgIgSgJgRQBFgDAbgJQAYgJADgXIAmAAQgCAMgFAKQA7AMA6AOIgSAgIh2ghgAJID0QgaBDhUAtQgLgOgWgXQBegrAPg6IhqAAIAAgoIBzAAQAEgYABgeIhoAAIAAgoID9AAIAAAoIhqAAIgDA2IB8AAIAAAoIhwAAQAhBKBSAYIgiAqQhNghgkhRgApfE/QBfgWASghIhuAAIAAghIB3AAIACgdIhkAAIAAggIBkAAIAAgeIAqAAIAAAeIBkAAIAAAgIhkAAIgBAdIB8AAIAAAhIhqAAQAiAkBKAOIgeApQhPgWgjg5QgcA1hZAdIgegngAyKEnQggA0hjAKQgEgNgLgYQBRgIAaggIhkAAIAAggIByAAIADgQIArAAIgDAQIB7AAIAAAgIhpAAQAgAgBOAFQgHAKgNAfQhXgJgng2gAg0FlIAAgKIh2AAIAAAKIgmAAIAAhEIgdALQgIgPgLgQQBJgTA6gtIAsAAIgHAHQA1AoBEAOIgSAiIgdgKIAABDgAiqE/IB2AAIAAgYIh2AAgAiiEMIBkAAQgdgQgUgTQgTASggARgAuFFlIAAhSQgVARgXAQIgNgsQAugaAhgjIhNAAIAAgkIBrAAQALgPAIgPIAqAJIgNAVICHAAIAAAkIiiAAQgLAOgNANICcAAIAAB+IgrAAIAAgRIh4AAIAAASgAtbEwIB4AAIAAgnIh4AAgAQJFkIAAgPIiOAAIAAjTIAnAAIAACtIAfAAIAAjpIAoAAIAADpIAgAAIAAisIAmAAIAADhgAM7FkIAAiMIgXAjQgEgXgJgeQAjg0AXhPIAnAJQgJAhgOAgIAADXgAEjEyIAAglIhtAAIAAAlIgkAAIAAgnQgRALgSAJIgTgdQAkgNAXgPIg0AAIAAgcIBHAAIAAgNIgyAAIAAgWIAyAAIAAgNIgdAAIAAgXIAdAAIAAgMIAlAAIAAAMIA7AAIAAgMIAlAAIAAAMIAcAAIAAAXIgcAAIAAANIAzAAIAAAWIgzAAIAAANIBIAAIAAAcIg0AAQAbASAeAKQgHALgLATQgSgHgRgMIAAAlgACwD0IB3AAIgPgOIhZAAIgPAOgADPDKIA7AAIAAgNIg7AAgADPCnIA7AAIAAgNIg7AAgAhcDFIASgVQBDAbAaANIgRAeIhegxgAjzDXQAxgQAsgZIAWAWQgrAag0AXIgUgegA0ZDkIAAggIB6AAIAAgQIhiAAIAAggIBiAAIAAgRIhzAAIAAggIBBAAQgGgOgHgLIAqgIIAUAhIAtAAIAXghIAsAIIgXAZIBIAAIAAAgIh2AAIAAARIBmAAIAAAgIhmAAIAAAQIB7AAIAAAggAgSDCIAAgXIi6AAIAAAXIgoAAIAAgzIByAAIgIgRIApgFIAKAWIBrAAIAAAzgAr/CZIAAgVIhTAAIAAAVIgpAAIAAgVIhAAAIAAgkIBAAAIAAgbIApAAIAAAbIBTAAIAAgcIApAAIAAAcIA6AAIAAAkIg6AAIAAAVgAmoCYIAAgZIhMAAIAAAZIgnAAIAAgZIg7AAIAAghIA7AAIAAgZIAnAAIAAAZIBMAAIAAgZIAoAAIAAAZIA7AAIAAAhIg7AAIAAAZgAFVCQIAAgeIjRAAIAAAeIggAAIAAg6IBzAAIgHgQIAugDIAIATIBuAAIAAA6gAhLCEIAAgRIhKAAIAAARIgmAAIAAgRIhDAAIAAgeIBDAAIAAgTIAmAAIAAATIBKAAIAAgTIAnAAIAAATIBBAAIAAAeIhBAAIAAARgAHZhmQAMgMAAgXIAAhAIgpAAIAAgmIApAAIAAh2IAoAAIAAB2IDKAAIAAAmIhvAAQAiA8BSAYQgNARgQAXQhdgmgjhWIgyAAIAABRIBMgZIAAAnQhXAagSAPgATihDIARhPIAqAAIgYBPgAN7hmQApgEAYgIIgwgUIAQgYIgeAAIAAgfIAyAAIAKgTIg0AAIAAhWIAtAAIAAgUIgxAAIAAgfICzAAIAAAfIgyAAIAAAUIAtAAIAABWIhkAAIAVAGIgJANIBhAAIAAAfIgeAAQgJAVgOARIAyAUIgTAgIg8gcQgjAVg5AIQgGgPgKgUgAO6iUIAlAOQALgKAIgOIgwAAgAQDjuIATAAIAAgaIgTAAgAPSjuIASAAIAAgaIgSAAgAOgjuIATAAIAAgaIgTAAgAPSkmIASAAIAAgUIgSAAgAMWhhQAMgcACglQACgmAAgvIAAhhIBTAAIAADwQAAATgJAHQgKAHgegBQgDgRgFgVIAPABQAKAAAAgOIAAgnIgVAAQAAA6gWAlIgYgegANGjEIATAAIAAgnIgTAAIAAAngANGkNIATAAIAAgmIgTAAgADWhDIAAiNQgmAvg4AoIgegnQBdg9AjhNIhzAAIAAgoIENAAIAAAoIhpAAQgJAYgOAXIAPAAIAAAiIAdgcIBfBXIgiAiQglgrg1gxIAACVgAnAhjIAsAAQAJAAAGgBQAHgCABgKIiPAAIAGhGIgXAAIAAgfIAaAAIAFguIgOAOQgKgOgOgRQAngnAUgqIApAFIgJARICGAAIAAAgIiZAAIgOATICXAAIgBBHIAYAAIAAAfIgYAAIgBAoIAWAAIAAAeIgXAAQgBAWgJAJQgIAIgQACQgQACgvAAIgJgegAmPigIgSASIAlAAIAAgoIg1AAIAiAWgAnjiOIA3AAIgfgXIASgRIgmAAgAmPjnIgTASIAnAAIAAgpIg1AAIAhAXgAncjVIAyAAIgggYIASgRIggAAgApZhRQAPgwANg+QASAIAUAGQgOAxgOA7IgmgMgAx8hjIAsAAQAJAAAGgBQAHgCABgKIiPAAIAGhGIgXAAIAAgfIAaAAIAFguIgOAOQgKgOgOgRQAngnAUgqIApAFIgJARICGAAIAAAgIiZAAQgGAKgIAJICXAAIgBBHIAYAAIAAAfIgYAAIgBAoIAWAAIAAAeIgXAAQgBAWgJAJQgIAIgQACQgQACgvAAIgJgegAxLigIgSASIAlAAIAAgoIg1AAIAiAWgAyfiOIA3AAIgfgXIASgRIgmAAgAxLjnIgTASIAnAAIAAgpIg1AAIAhAXgAyYjVIAyAAIgggYIASgRIggAAgA0VhRQAPgwANg+QASAIAUAGQgOAxgOA7IgmgMgAg6hhIhbAAIAAhGIgQgPIAABUIggAAIAAgUIgQAAIAAAaIghAAIAAjwIBRAAIAACJQAUgSAPgWIgRAAIAAhxICfAAIAABxIhmAAIgJAQIB5AAQAAAsgDA7QAAAqgdACQgLACggAAIgFgbgAiCizIAMAAIAAA2IBbAAIAAAWQAOAAAAgSIADhEIgnAAIgEAJIAnAeIgTAXIgigeQgMARgQAOQgHgJgPgOQAWgSAOgWIgoAAgAjViXIAQAAIAAiUIgQAAgAhvkIIBZAAIAAgPIhZAAgAhvkvIBZAAIAAgPIhZAAgAsEhNQgeAAgQgLQgRgLAAgWQAAgmBTg5IhHAAIAAgkIACAAQgRgOgLgIIAACsIgjAAIAAgWIgYAAIAAAZIgkAAIAAjpIBfAAIAAA5QAfgmATgtIAoAMIgMAZIBlAAIAAAkIh6AAQgLASgNAPIB7AAIAAAiQhnBJAAAVQAAAOAaAAIAfAAQAMAAAIgFQAIgFACgKQACgLADgfQATAHAVAFQgEAbgFATQgFAUgPAJQgPAIgZAAgAuMihIAYAAIAAiGIgYAAgApfj6IAYgcQAWAQAYAVIgaAfIgsgogA0bj6IAYgcQAWAQAYAVIgaAfIgsgogAIikcQBOgkAvgiIAfAkQg+AjhGAfgApXlJIAZgbQAXARAYAUIgbAeQgVgUgYgUgA0TlJIAZgbQAXARAYAUIgbAeQgVgUgYgUg");
	this.shape.setTransform(167.7,62.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#993300").s().p("A6KKUIAA0nMA0VAAAIAAUng");
	this.shape_1.setTransform(167.5,79,1,1,0,0,0,0,13);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,335.1,132.1);


(lib.ani1_headMc = function() {
	this.initialize();

}).prototype = p = new cjs.Container();
p.nominalBounds = null;


(lib.ani1_gtInfoMc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(7));

	// 01
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AzpFnIAAgKIiYAAIAAAKIgnAAIAAhKIDnAAIAABKgA2BFEICYAAIAAgOIiYAAgADBFnIAAiMQgmAug4AoIgegnQBdg8AjhOIhzAAIAAgoIENAAIAAAoIhpAAQgJAZgOAWIAPAAIAAAjIAdgdIBfBXIgiAiQglgrg1gwIAACUgAohE6IAdgZIAAhKIgbAAIAAglIBBAAIAABvQAXAaAyAAQBpAAArgCIgNAmIhKABQhRAAgNgCQgOgDgOgFQgPgFgOgNIgiAigAtXE6IAdgZIAAhKIgbAAIAAglIBBAAIAABvQAXAaAyAAQBpAAArgCIgNAmIhKABQhRAAgNgCQgOgDgOgFQgPgFgOgNIgiAigAjRFmIAAiIQgJAQgKAQQgEgYgHgcQAcgxAWhTIAlAIQgKAhgLAeIAADZgAhsFlIgHgkQAPABAUAAQAOABAAgRIAAgLIhOAAIAAgeICxAAIAAAeIg8AAIAAAWQAAAlgfACIgjABIgPAAgAxCFkQgCgRgEgUIAmACQAPAAAAgOIhqAAIAAgZIBqAAIAAgOIh8AAIAAgaIB8AAIAAgNIhpAAIAAgaIBpAAIAAgOIhhAAIAAg9IBhAAIAAgOIh6AAIAAgaIB6AAIAAgTIAoAAIAAATIB7AAIAAAaIh7AAIAAAOIBiAAIAAA9IhiAAIAAAOIBmAAIAAAnIAXAAIAAAaIgXAAIAAA1IgnAAIAAgOIg/AAIAAAIQAAAOgFAKQgFAJgKADQgLAFgEAAIg0AAgAvrEaIA/AAIAAgOIg/AAgAvrDyIA/AAIAAgNIg/AAgAvrCmIA8AAIAAgPIg8AAgAxOCmIA7AAIAAgPIg7AAgAG9FgQgEgVgGgYQAcAEASAAQASAAAFgHQAFgIAAgLIAAhlQAkgYAugjIjJAAIAAgoIENAAIAAAoIhoBOIAABeQAAAcgOAOQgOANgcAAgAl1E3IAAghIhcAAIAAgiIBcAAIAAgcIhUAAIAAgfQAOgYAMgcIgcAAIAAgiIArAAIALgfIAqAHIgKAYIBoAAIAAAiIh3AAIgYAwIAnAAIAAglIAnAAIAAAlIA/AAIAAAjIg/AAIAAAcIBIAAIAAAiIhIAAIAAAhgAqrE3IAAghIhcAAIAAgiIBcAAIAAgcIhUAAIAAgfQAOgYAMgcIgcAAIAAgiIArAAIALgfIAqAHIgKAYIBoAAIAAAiIh3AAIgYAwIAnAAIAAglIAnAAIAAAlIA/AAIAAAjIg/AAIAAAcIBIAAIAAAiIhIAAIAAAhgA3FERIAAgbIBDAAIgJgRIAUgEIguAAIAAg/IDgAAIAAA/IgtAAIAVAFIgPAQIBJAAIAAAbgA1SD2IA4AAIAOgVIhSAAIAMAVgA19DJICRAAIAAgOIiRAAgAAMEEIAAgQIiKAAIAAAQIgmAAIAAguIDXAAIAAAugAiJDLIAAhDICjAAIAABDgAhjCxIBZAAIAAgPIhZAAgAoYBeIAfgUQAXAcARAaIgiAXQgSgfgTgagAtOBeIAfgUQAXAcARAaIgiAXQgSgfgTgagA2vCVIAAgZIBmAAIAAgNIh2AAIAAgbIB2AAIAAgPIApAAIAAAPIB2AAIAAAbIh2AAIAAANIBlAAIAAAZgAibB8IAAgdIBQAAIgIgSIArgIIAJAaIBQAAIAAAdgAWLhAIARhQIAqAAIgYBQgAGehBIAAhqIgYAZIgLgxQAjghASgjIgxAAIAAgnIAvAAQgNgUgMgRIAigSQAQAUANATIgeAQIAnAAIAAAgQgMAZgNAVIAAAIIAMgHIASAaIAAgLICyAAIAACNIgnAAIAAgNIhkAAIAAANIgnAAIAAhpIgQAJIgOgbIAAB9gAJOhtIAfAAIAAgVIgfAAgAIJhtIAfAAIAAgVIgfAAgAJOieIAfAAIAAgWIgfAAgAIJieIAfAAIAAgWIgfAAgABThBIAAkWIEIAAIAAEVIglAAIAAgMIi+AAIAAANgAB4htIC+AAIAAjLIi+AAgA1KhBIAAhFIh5AAIAAgkIB5AAIAAggIhbAAIAAgjIBbAAIAAghIhvAAIAAgjIBFAAIgcgfIAfgXIAoAoIgVAOIA3AAQAUgZATgcIAsATIgfAiIBCAAIAAAjIhtAAIAAAhIBaAAIAAAjIhaAAIAAAgIB4AAIAAAkIh4AAIAABFgAnKhmQgfAPgkANQgKgSgNgRQBWgVA3gqIgGgMQgwAig9AQIgUgeQBGgOAtgcIgHgKQgnATgwAMQgJgQgKgOQA7gKAqgVIgxAAIAAggICrAAIAAAgIhAAAIgTAMQAMAQAJAPQAxgXAggUIAXAhIguAWQAUAyAsAaIggAgQgmgdgZhCIgMAGQAHAXAAAWQAAATgEALQgDAMgJAIQgJAIgMABQgLACgsAAQgEgUgFgQgAnGhpQASADAMAAQAbAAAAgbIgCgMQgYAVgfAPgAwChCIAAg+IiLAAIAAglIApAAIAAhIIgQARIgagmQAsgkAYg+IAuAHIgLAZICuAAIAAAlIheAAIAAAmIBTAAIAAAmIhTAAIAAAuIBnAAIAAAlIhnAAIAAA+gAw7ilIA5AAIAAguIg5AAgAxZj5IBXAAIAAgmIg6AAQgNAUgQASgAK4hPQAPgzAOg9IAlAOIgcBvQgTgHgTgGgAMChDIAAicIA3AAIAAgYIhAAAIAAgfIDaAAIAAAfIg9AAIAAAYIA0AAIAAB0QAAARgIAJQgHAKgNABQgMACgoAAQgDgPgFgOIgegSQANgOAIgSIgOAMIgKgMQgJAYgSAaQgDgFgMgIIAAArgAN0hjIAgABQARABAAgRIAAgRIgLALIgPgSQgIAVgPASgAMliFQASgbACgkIgUAAgAOUirIATAUIAAgtIgRAAIgCAZgANYixIAVAVQAGgSABgWIgaAAQAAAMgCAHgANajfIAbAAIAAgYIgbAAgAjihDIAAkUIEJAAIAAETIgnAAIAAgKIi5AAIAAALgAi5hyIC5AAIAAjBIi5AAgAPqhLIAAgiIB7AAIAAgSIhkAAIAAghIBkAAIAAgRIhPAAIAAg5IglAAIAAhIIA5AAIghgZIAXgZQAdAVATAOIgNAPIAjAAIAAgxIAnAAIAAAxIAgAAIgLgMQAZgTAWgTIAaAXIgiAbIA5AAIAABIIgmAAIAAA5IhPAAIAAARIBkAAIAAAhIhkAAIAAASIB9AAIAAAigAQ9jPIB3AAIAAgTIh3AAgAQZkAIDAAAIAAgQIjAAAgAtNhMIAAgmIBuAAIAAgjIhXAAIAAgmIBXAAIAAgdIg4AAIAAgXIgqAbIgagiQBegzAig5IAzAAIgIALQAmA2BTAnIgaAiQgWgLgTgNIAAAYIg5AAIAAAdIBYAAIAAAmIhYAAIAAAjIBvAAIAAAmgAsFj9IB4AAQgjgcgZgfQgYAegkAdgADXiOQgZAWgxAJIgPgfQAwgGANgLQAOgLACgTIAhAAQgBAOgFAMIBOAaIgRAbgAiAidIAhABQAXAAAAgYIAAgwQgeAtg4AqQgNgTgMgNQA0geAhglIhLAAIAAgiIBlAAIAAgaIAnAAIAAAaIAVAAIAAAiIgVAAIAAA/QAAAagMAOQgMAOgXACIgoABIgIglgAEFibIAAgrIhcAAIAAArIggAAIAAhGICcAAIAABGgAKxj3IAYgcQAXAQAYAWIgbAfIgsgpgAHujeIAAhLICaAAIAABLgAIWj8IBKAAIAAgQIhKAAgACUjsIAAhAICGAAIAABAgACykFIBKAAIAAgNIhKAAgAkyj/IAAgpIjBAAIAAApIgoAAIAAhLIByAAIgJgUIAzgGIAIAaIBtAAIAABLgAN9kZIAAgSIguAAIAAASIgmAAIAAgSIgwAAIAAgLIgXAYQgTgTgYgUIAYgbQATANAXAUIAAgLIAwAAIAAgYIAmAAIAAAYIAuAAIAAgZIAmAAIAAAZIAwAAIAAAfIgwAAIAAASgAHkk4IAAgfICxAAIAAAfg");
	this.shape.setTransform(260.8,94.6,1.867,1.867);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AtlFJQA0gzAAhvIABgwIgZAAIAAgjICQAAIAAAiIgUA3IAnAAQAAA/gCA8QgBA0gvACIgsABQgCgPgGgaIAjACQAaAAAAgVQADgpAAgqIgoAAIAAgiIAUg3IgqAAIAAAwQgBCAg4BAQgMgMgWgSgApiE+QAlg0ABhuIgiAAIAAgnIAjAAIAAgxIAmAAIAAAxIBCAAIgEC7QgBAVgIALQgIAKgLADQgLACgjAAIgKgrIAeABQAHAAAEgDQAEgDABgGQABgFABgnIABhhIgcAAQgCCKgzBBIgXgpgAQQFTQhDAJhQAHIgHglIBNgGIAAggIhCAAIAAhdIBCAAIAAgUIg4AAIAAhYICWAAIAABYIg5AAIAAAUIBDAAIAABdIgPAAQAPAdAPAkIgiANgAPoE1IAagDIgHgOIAhgMIg0AAgAPoD4IAfAAIAAgdIgfAAgAOlD4IAeAAIAAgdIgeAAgAOwCGIBMAAIAAgWIhMAAgAFUFTQhDAJhQAHIgHglIBNgGIAAggIhCAAIAAhdIBCAAIAAgUIg4AAIAAhYICWAAIAABYIg5AAIAAAUIBDAAIAABdIgPAAQAPAdAPAkIgiANgAEsE1IAagDIgHgOIAhgMIg0AAgAEsD4IAfAAIAAgdIgfAAgADpD4IAeAAIAAgdIgeAAgAD0CGIBMAAIAAgWIhMAAgAi3E9IAiACQAQAAAAgQIAAgkIhUAAIAAgaIgXAMQgQgfgGgJQBTgbAxg0IAxAAIgIAIQAwArBHAUQgMAVgIAVIgWgLIAAAfIhQAAIAAAtQAAApgfACIg0ABIgIgngAhcDJIAAAfIBIAAQg3gbgmgjQgfAfg4AfIBDAAIAAgfgAxWFJIhbAAIAAhHIgQgPIAABUIggAAIAAgTIgQAAIAAAZIghAAIAAjwIBRAAIAACJQAUgSAPgVIgRAAIAAhyIChAAIAAByIhoAAIgJAPIB7AAQAAAtgDA6QAAArgfACQgLABggABIgFgbgAyeD3IAMAAIAAA2IBbAAIAAAVQAOAAAAgSIADhEIgnAAIgEAJIAnAeIgTAXIgigeQgMARgQAOQgHgJgPgOQAWgRAOgXIgoAAgAzxESIAQAAIAAiUIgQAAgAyLChIBZAAIAAgPIhZAAgAyLB6IBZAAIAAgPIhZAAgAMiFjIgIgoIAfACQALgBAEgHQADgJABgwIg0AAIAHhoIAyAAIAAgiIg4AAIAAgjIBcAAIAABoIg0AAIgCAjIAzAAQgBBHgCAVQgCAWgGAIQgGAJgLAEQgIACggAAIgMAAgABmFjIgIgoIAfACQALgBAEgHQADgJABgwIg0AAIAHhoIAyAAIAAgiIg4AAIAAgjIBcAAIAABoIg0AAIgCAjIAzAAQgBBHgCAVQgCAWgGAIQgGAJgLAEQgIACggAAIgMAAgAIGE3QAYACAQAAQARAAAAgSIAAg6IhyAAIAAgpQAVgaASgcIg5AAIAAgmIBQAAQAKgSAIgTIAxAFIgQAgICWAAIAAAmIitAAQgRAbgWAdIA/AAIAAgpIAsAAIAAApIBfAAIAAAnIhfAAIAABDQAAAXgKALQgJAMgRADQgRACgmAAIgKgsgAvBFCQAcgTASgcIgnghQAJghAIg2IgVAAIAAgjIAbAAIAGg0IAmADIgIAxIA0AAQgCBbgWA3IAWARIgZAhIgQgPQgVAggeAWQgKgPgOgSgAuTDmIASANQAPgkADg0IgWAAQgHAtgHAegAnCFfIAAkCIB3AAIAAEBIgoAAIAAgYIgnAAIAAAZgAmaEfIAnAAIAAibIgnAAgAg8EpIAZgaQAkAbAaAVIgbAeIg8g0gAkCE+QAjgZAZgYIAcAaQgeAcghAZIgZgegAGzE4QAigeAkgnIAiAbQgkAnglAjQgOgRgRgPgAJ6EWIAbgdIBHA5IgeAhQgfgeglgfgAhICTIAAgVIhSAAIAAAVIgpAAIAAgVIg6AAIAAgjIA6AAIAAgWIApAAIAAAWIBSAAIAAgWIAoAAIAAAWIA9AAIAAAjIg9AAIAAAVgAh6hPIAGgJIgsAAIAAAYIgkAAIAAgYIg7AAIAAgVIA7AAIAAgKIgvAAIAAgxIAvAAIAAgLIggAAIAAgbIgbAAIAAgVIAbAAIAAgJIAcAAIAAAJIArAAIAAgJIAdAAIAAAJIAZAAIAAAVIgZAAIAAAbIggAAIAAALIAxAAIAAAxIgxAAIAAAKIAwAAIAAAOQAQgaAAg2IAAg4IBtAAIAACAQAAAjgfABIglABIgGghIAgABQAKAAAAgLIAAgJIguAAQgFAagTAeQgRgJgQgIgAigiJIAUAAIAAgOIgUAAgAjXiJIATAAIAAgOIgTAAgAg+iQIArAAIAAgRIgqAAIgBARgAg9i5IAqAAIAAgRIgqAAgAjIjEIArAAIAAgKIgrAAgATghBIARhQIAqAAIgYBQgAIOhgQA4gpAAhRIAChTIgkAAIAAglICoAAIgFDMQAAAagIAOQgIAOgPADQgOADgwABQgEgUgGgZIAmACQANAAAFgFQAFgGABgIQACgIACieIgwAAQgDBpgFAdQgEAcgPAcQgPAcgYASQgNgOgVgRgAu5hQQAPgwAOhAIAlAOIgcBuIgmgMgAo4hEIAAheQgNAdgOAUIgPgvQAYgdARgtIgmAAIAAglIAnAAIAAghIgiAEIgEgjQA7gGAtgGIAHAiIgkAFIAAAlIAeAAQAagrAIgnIAmAFIgJAeIBxAAIAAAiIgMAzIgkgIIAKgqIhZAAQgLAbgQAWIgUgYIAAAYIggAAIAAAQIAlAYIgRAfIgUgRIAABwgAzNhEQgEgVgGgSIApABQAUAAAAgSIAAgSIiAAAIAAgkICAAAIAAgHIAogZIhrAAIAAgkICkAAIAAAjIgyAhIBtAAIAAAkIhxAAIAAAfQAAAUgMALQgLAMgXAAIgwAAgAnShHQgDgVgEgRQANACAOgBQAOABAAgNIAAiQIAnAAIAACYQAAATgHAJQgHAKgOABQgLACgWAAIgMAAgAt5hLIAAgfIDaAAIAAAfgAOAhNIAAkKICyAAIAAAjIiNAAIAADFICRAAIAAAigADEhNIAAkKICyAAIAAAjIiNAAIAADFICRAAIAAAigAHPh+QAIgJAAgUIAAhQIgeADIgCgmIAggDIAAhQIAoAAIAABMIAtgEIACAmIgvAFIAABMIAogdQAAAbACARQg3ApgIAMgAMghjIAAjpIBQAAIAADhIgfAAIAAgTIgPAAIAAAbgANCijIAPAAIAAiDIgPAAgABkhjIAAjpIBQAAIAADhIgfAAIAAgTIgPAAIAAAbgACGijIAPAAIAAiDIgPAAgAl/jXIAhgKQALAfAVBFIgmAOQgOg8gNgsgAoBiCQAVgxANguIAjAKQgNAzgVAyIgjgQgAtgh5IAAhzIgJAGQgKgQgNgRQAogQAcgWIgtAAIAAgeIBJAAIAAgZIAmAAIAAAZIBPAAIAAAeIg4AAQAeAVArALQgNAVgGAQIgNgGIAAB1gAs6iYIBaAAIAAgSIhaAAgAs6jFIBaAAIAAgSIhaAAgArEj0QgggTgWgXIAAAhIgmAAIAAgiQgWAXgdAUICPAAIAAAAgAOsiIIAAgfIAwAAIAAgbIgnAAIAAgfIAnAAIAAgcIgsAAIAAgeIB8AAIAAAeIgtAAIAAAcIAoAAIAAAfIgoAAIAAAbIAyAAIAAAfgADwiIIAAgfIAwAAIAAgbIgnAAIAAgfIAnAAIAAgcIgsAAIAAgeIB8AAIAAAeIgtAAIAAAcIAoAAIAAAfIgoAAIAAAbIAyAAIAAAfgAvAj4IAYgcQAXARAYAUIgbAgQgJgKgjgfgAwsjnIAAglIjAAAIAAAlIgpAAIAAhIIAwAAIgZggIAfgVQASATASAZIgNAJIAxAAQgNgYgKgQIAkgQQALASAQAcIgUAKIAkAAIAigyIAnAVIgXAdIAqAAIAABIgAhSjyIAAgPIBLAAIAAAPgAjdjyIAAgPIBMAAIAAAPgAiEj1IAAgtIhVAAIAAAYIgiAAIAAgtIB3AAIAAgMIhoAAIAAgWIDzAAIAAAWIhnAAIAAAMIB1AAIAAAtIggAAIAAgYIhVAAIAAAtgAhSkKIAAgPIBAAAIAAAPgAjRkKIAAgPIBAAAIAAAPgAu3lHIAYgaIAxAkIgcAeQgVgVgYgTg");
	this.shape_1.setTransform(257.2,94.8,1.867,1.867);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ADoFGQgfAbhXAFQgIgSgJgRQBFgDAbgJQAYgJADgXIAmAAQgCAMgFAKQA7AMA6AOIgSAgIh2ghgAJID0QgaBDhUAtQgLgOgWgXQBegrAPg6IhqAAIAAgoIBzAAQAEgYABgeIhoAAIAAgoID9AAIAAAoIhqAAIgDA2IB8AAIAAAoIhwAAQAhBKBSAYIgiAqQhNghgkhRgApfE/QBfgWASghIhuAAIAAghIB3AAIACgdIhkAAIAAggIBkAAIAAgeIAqAAIAAAeIBkAAIAAAgIhkAAIgBAdIB8AAIAAAhIhqAAQAiAkBKAOIgeApQhPgWgjg5QgcA1hZAdIgegngAyKEnQggA0hjAKQgEgNgLgYQBRgIAaggIhkAAIAAggIByAAIADgQIArAAIgDAQIB7AAIAAAgIhpAAQAgAgBOAFQgHAKgNAfQhXgJgng2gAg0FlIAAgKIh2AAIAAAKIgmAAIAAhEIgdALQgIgPgLgQQBJgTA6gtIAsAAIgHAHQA1AoBEAOIgSAiIgdgKIAABDgAiqE/IB2AAIAAgYIh2AAgAiiEMIBkAAQgdgQgUgTQgTASggARgAuFFlIAAhSQgVARgXAQIgNgsQAugaAhgjIhNAAIAAgkIBrAAQALgPAIgPIAqAJIgNAVICHAAIAAAkIiiAAQgLAOgNANICcAAIAAB+IgrAAIAAgRIh4AAIAAASgAtbEwIB4AAIAAgnIh4AAgAQJFkIAAgPIiOAAIAAjTIAnAAIAACtIAfAAIAAjpIAoAAIAADpIAgAAIAAisIAmAAIAADhgAM7FkIAAiMIgXAjQgEgXgJgeQAjg0AXhPIAnAJQgJAhgOAgIAADXgAEjEyIAAglIhtAAIAAAlIgkAAIAAgnQgRALgSAJIgTgdQAkgNAXgPIg0AAIAAgcIBHAAIAAgNIgyAAIAAgWIAyAAIAAgNIgdAAIAAgXIAdAAIAAgMIAlAAIAAAMIA7AAIAAgMIAlAAIAAAMIAcAAIAAAXIgcAAIAAANIAzAAIAAAWIgzAAIAAANIBIAAIAAAcIg0AAQAbASAeAKQgHALgLATQgSgHgRgMIAAAlgACwD0IB3AAIgPgOIhZAAIgPAOgADPDKIA7AAIAAgNIg7AAgADPCnIA7AAIAAgNIg7AAgAhcDFIASgVQBDAbAaANIgRAeIhegxgAjzDXQAxgQAsgZIAWAWQgrAag0AXIgUgegA0ZDkIAAggIB6AAIAAgQIhiAAIAAggIBiAAIAAgRIhzAAIAAggIBBAAQgGgOgHgLIAqgIIAUAhIAtAAIAXghIAsAIIgXAZIBIAAIAAAgIh2AAIAAARIBmAAIAAAgIhmAAIAAAQIB7AAIAAAggAgSDCIAAgXIi6AAIAAAXIgoAAIAAgzIByAAIgIgRIApgFIAKAWIBrAAIAAAzgAr/CZIAAgVIhTAAIAAAVIgpAAIAAgVIhAAAIAAgkIBAAAIAAgbIApAAIAAAbIBTAAIAAgcIApAAIAAAcIA6AAIAAAkIg6AAIAAAVgAmoCYIAAgZIhMAAIAAAZIgnAAIAAgZIg7AAIAAghIA7AAIAAgZIAnAAIAAAZIBMAAIAAgZIAoAAIAAAZIA7AAIAAAhIg7AAIAAAZgAFVCQIAAgeIjRAAIAAAeIggAAIAAg6IBzAAIgHgQIAugDIAIATIBuAAIAAA6gAhLCEIAAgRIhKAAIAAARIgmAAIAAgRIhDAAIAAgeIBDAAIAAgTIAmAAIAAATIBKAAIAAgTIAnAAIAAATIBBAAIAAAeIhBAAIAAARgAHZhmQAMgMAAgXIAAhAIgpAAIAAgmIApAAIAAh2IAoAAIAAB2IDKAAIAAAmIhvAAQAiA8BSAYQgNARgQAXQhdgmgjhWIgyAAIAABRIBMgZIAAAnQhXAagSAPgATihDIARhPIAqAAIgYBPgAN7hmQApgEAYgIIgwgUIAQgYIgeAAIAAgfIAyAAIAKgTIg0AAIAAhWIAtAAIAAgUIgxAAIAAgfICzAAIAAAfIgyAAIAAAUIAtAAIAABWIhkAAIAVAGIgJANIBhAAIAAAfIgeAAQgJAVgOARIAyAUIgTAgIg8gcQgjAVg5AIQgGgPgKgUgAO6iUIAlAOQALgKAIgOIgwAAgAQDjuIATAAIAAgaIgTAAgAPSjuIASAAIAAgaIgSAAgAOgjuIATAAIAAgaIgTAAgAPSkmIASAAIAAgUIgSAAgAMWhhQAMgcACglQACgmAAgvIAAhhIBTAAIAADwQAAATgJAHQgKAHgegBQgDgRgFgVIAPABQAKAAAAgOIAAgnIgVAAQAAA6gWAlIgYgegANGjEIATAAIAAgnIgTAAIAAAngANGkNIATAAIAAgmIgTAAgADWhDIAAiNQgmAvg4AoIgegnQBdg9AjhNIhzAAIAAgoIENAAIAAAoIhpAAQgJAYgOAXIAPAAIAAAiIAdgcIBfBXIgiAiQglgrg1gxIAACVgAnAhjIAsAAQAJAAAGgBQAHgCABgKIiPAAIAGhGIgXAAIAAgfIAaAAIAFguIgOAOQgKgOgOgRQAngnAUgqIApAFIgJARICGAAIAAAgIiZAAIgOATICXAAIgBBHIAYAAIAAAfIgYAAIgBAoIAWAAIAAAeIgXAAQgBAWgJAJQgIAIgQACQgQACgvAAIgJgegAmPigIgSASIAlAAIAAgoIg1AAIAiAWgAnjiOIA3AAIgfgXIASgRIgmAAgAmPjnIgTASIAnAAIAAgpIg1AAIAhAXgAncjVIAyAAIgggYIASgRIggAAgApZhRQAPgwANg+QASAIAUAGQgOAxgOA7IgmgMgAx8hjIAsAAQAJAAAGgBQAHgCABgKIiPAAIAGhGIgXAAIAAgfIAaAAIAFguIgOAOQgKgOgOgRQAngnAUgqIApAFIgJARICGAAIAAAgIiZAAQgGAKgIAJICXAAIgBBHIAYAAIAAAfIgYAAIgBAoIAWAAIAAAeIgXAAQgBAWgJAJQgIAIgQACQgQACgvAAIgJgegAxLigIgSASIAlAAIAAgoIg1AAIAiAWgAyfiOIA3AAIgfgXIASgRIgmAAgAxLjnIgTASIAnAAIAAgpIg1AAIAhAXgAyYjVIAyAAIgggYIASgRIggAAgA0VhRQAPgwANg+QASAIAUAGQgOAxgOA7IgmgMgAg6hhIhbAAIAAhGIgQgPIAABUIggAAIAAgUIgQAAIAAAaIghAAIAAjwIBRAAIAACJQAUgSAPgWIgRAAIAAhxICfAAIAABxIhmAAIgJAQIB5AAQAAAsgDA7QAAAqgdACQgLACggAAIgFgbgAiCizIAMAAIAAA2IBbAAIAAAWQAOAAAAgSIADhEIgnAAIgEAJIAnAeIgTAXIgigeQgMARgQAOQgHgJgPgOQAWgSAOgWIgoAAgAjViXIAQAAIAAiUIgQAAgAhvkIIBZAAIAAgPIhZAAgAhvkvIBZAAIAAgPIhZAAgAsEhNQgeAAgQgLQgRgLAAgWQAAgmBTg5IhHAAIAAgkIACAAQgRgOgLgIIAACsIgjAAIAAgWIgYAAIAAAZIgkAAIAAjpIBfAAIAAA5QAfgmATgtIAoAMIgMAZIBlAAIAAAkIh6AAQgLASgNAPIB7AAIAAAiQhnBJAAAVQAAAOAaAAIAfAAQAMAAAIgFQAIgFACgKQACgLADgfQATAHAVAFQgEAbgFATQgFAUgPAJQgPAIgZAAgAuMihIAYAAIAAiGIgYAAgApfj6IAYgcQAWAQAYAVIgaAfIgsgogA0bj6IAYgcQAWAQAYAVIgaAfIgsgogAIikcQBOgkAvgiIAfAkQg+AjhGAfgApXlJIAZgbQAXARAYAUIgbAeQgVgUgYgUgA0TlJIAZgbQAXARAYAUIgbAeQgVgUgYgUg");
	this.shape_2.setTransform(258.7,95,1.867,1.867);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AiRE/QAmgTAagYQgUgggLgmIgJANQgLgRgOgSIAACtIgmAAIAAhVQglATgTAPIgQgmQAKgIABgOIAAiUIAkAAIAACUIAZgOIAAijIAmAAIAABvQAggvARhCIApAHQgGAUgGATIBjAAIAAAnIgUAAQgKBLgdAyQAaAZAjAOQgNASgNAXQgigUgbgcQgdAdgoAVQgJgWgNgSgAhXCgQAJAwAXAkQAUgkAKg4Ig6AAIgEAIgApfFGQAugeApgsIAiAbQguAwgtAggAysE/QAngTAagYQgUgggLgmIgJANQgLgRgOgSIAACtIgmAAIAAhVQglATgSAPIgRgmQALgIgBgOIAAiUIAlAAIAACUIAZgOIAAijIAmAAIAABvQAggvAShCIAnAHQgEAUgHATIBkAAIAAAnIgTAAQgJBLghAyQAbAZAlAOQgNASgNAXQgkgUgbgcQgcAdgoAVQgLgWgNgSgAxxCgQAJAwAWAkQAVgkAKg4Ig6AAIgEAIgAm0EVIAdgaQAzAmAnAlIghAgQgqgrgsgmgABbE/QBsgwAJhYIhvAAIAAgoIB0AAQABggAAgqIAtAAIgCBKIB4AAIAAAoIh1AAQAZBiBhAiIgiAoQhQgmgfhSQgYBMhYAuIgigmgAJzFlIAAhgIgaAAIAAATIglAAIAAgmIgWAWIgWgYIAAB1IgkAAIAAhhQgNAcgQAYIgOgwQAbggAPgqIgnAAIAAglIAoAAIAAgiIghAEQgDgUgEgOQAygGA1gHIAJAiIgkAGIAAAlIAjAAIAAAlIgjAAIAAAbIAKgKIAiAiIAAhzIA/AAIAAg5IAlAAIAAA5IA+AAIAACaIgkAAIAAgTIgaAAIAABggAKYDhIAaAAIAAg/IgaAAgAJZDhIAaAAIAAg/IgaAAgAuCFlIAAhqQgUAVgbAXQgGgcgGgVQA6gwAZgpIhHAAIAAgnIA5AAIgWgiIAigRIAbAmIgaANIAxAAIAAAkQgMAZgUAaIAAAPIAMgOQAUANAZATIgZAeIgggdIAAB2gANXFfQgEgVgHgXQAbADAYAAQAZAAgBgaIAAgvIh+AAIAAgoIB+AAIAAgjIBHgnIiwAAIAAgnID2AAIAAAnIhhA6IAAAQIB2AAIAAAoIh2AAIAAA3QAAAfgMAOQgOAPgcAAgArxFfQgogBAAgpIAAjtIAoAAIAADjQAAAPAOABIAJAAQAPgBADgLQAFgdADgcQARAJAXAHQgFAmgIAYQgHAagnABgApADzIAAijIDkAAIAACjgAoUDOICOAAIAAhZIiOAAgAIphpQAlgTAbgZQgUgfgMgnIgJAOQgKgRgOgSIAACtIgmAAIAAhUQglASgTAPIgRgmQAMgJAAgNIAAiUIAkAAIAACUIAZgOIAAijIAmAAIAABvQAggvARhCIApAHQgGAUgGATIBkAAIAAAnIgTAAQgKBLgfAyQAaAZAmAPQgNARgNAWQglgTgbgcQgdAegoATQgKgVgMgSgAJjkJQAJAxAXAkQAUgkAKg4Ig6AAIgEAHgAyVhYQAggjAegrIiiAAIAAgnIDbAAIAAAkQghAtgvA6gATjhCIARhPIAqAAIgZBPgAixhCIAAiNIhBAAIAAgnID6AAIgEBhQgCASgGALQgIAMgOADQgNAFhAAAQgEgTgGgZQAfACASABQAMAAAGgGQAHgEABgJIACgvIhfAAIAACNgADXhDIAAiMQgmAvg4AnIgegnQBdg8AjhNIhzAAIAAgpIENAAIAAApIhpAAQgJAYgOAXIAOAAIAAAiIAdgcIBgBXIgiAhQglgqg2gxIAACUgApfhxIAdgYIAAhRIgbAAIAAgnIBDAAIAAB3QAWAaAkAAIAtAAIB4gBIgNAoIingDQgUgBgQgGQgPgHgKgNIgjAkgANThEIAAhqQgWAWgZAWQgHgcgHgUQA8gwAXgpIhHAAIAAgmIA6AAIgWgjIAigRIAaAlIgZAPIAyAAIAAAkQgNAYgUAaIAAAPIAMgPQAVAOAZATIgZAdIghgcIAAB1gAsuhEIAAg+IiLAAIAAglIApAAIAAhIIgQARIgbglQAtglAYg9IAuAHIgMAYICvAAIAAAmIheAAIAAAmIBTAAIAAAlIhTAAIAAAuIBnAAIAAAlIhnAAIAAA+gAtninIA5AAIAAguIg5AAgAuFj6IBXAAIAAgmIg7AAQgNAUgPASgAPjhJQgoAAAAgqIAAjsIApAAIAADjQgBAPAOAAIAIAAQAQAAACgNQAGgcACgcQASAJAYAIQgGAlgIAYQgHAbgnAAgAnaikIAwADQAWAAAAgZIAAhVIh1AAIAAgkIB1AAIAAgxIArAAIAAAxIAqAAIAAAkIgqAAIAABhQAAAZgMANQgLAMgVABIg6ABQgDgTgIgXgAoDjzIAggZQATAXAfAoIgiAaIgwhAgAywkDIAggVQAaAbAQAWIgjAXQgZgigOgRgA0cj8QBNgjA0hFIA5AAIgKAKQAtA8BJAgIgbAjQhMglgqg8QguA8hNAoQgQgZgKgLgAhRkGIAAgZIg8AAIAAAZIgrAAIAAgZIhHAAIAAgmIBHAAIAAgfIArAAIAAAfIA8AAIAAgfIAsAAIAAAfIBEAAIAAAmIhEAAIAAAZgApWlRIAhgUQAWAfAPAYIgmAWQgQgfgQgag");
	this.shape_3.setTransform(258.6,94.9,1.867,1.867);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("ADrF0IAAgmQAJAFAMAAQATAAAIgSIAJgWIhCihIA1AAIAgBlIAEAVIABAAQABgIAEgMIAghmIAvAAIhDCwQgXA+gvAAQgSAAgKgEgAAAF2IAAjsIAuAAIAAAYIAAAAQATgcAiAAQAfAAARAVQASAWAAAlQAAApgVAYQgUAZghAAQgdAAgQgYIAAAAIAABegAA3C2QgKANAAATIAAAOQAAARAJALQAKALAPAAQARAAAKgNQAKgOAAgZQAAgtgjAAQgQAAgKAMgAj6F2IAAjsIAwAAIAAAYIAAAAQATgcAiAAQAfAAARAVQASAWAAAlQAAApgVAYQgUAZghAAQgdAAgQgYIAAAAIAABegAjBC2QgKANAAATIAAAOQAAARAJALQAKALAPAAQARAAAKgNQAKgOAAgZQAAgtgjAAQgQAAgKAMgAMjEzQATgmAAhIIAmAAQAAAagCAWQAHASANAMIAAhaIhKAAIAAgkIA5AAIAAgbIgvAAIAAgkIAvAAIAAglIAoAAIAAAlIAsAAIAAAkIgsAAIAAAbIA0AAIAAAkIglAAIAAAhIAhAAIAAAkIghAAIAAAlQAPACAuAAIB2gCQgHATgHAXQh1AAgvgDQgugDgVghQgGAagKAUIgfghgAw8EzQATgmAAhIIAlAAQAAAagCAWQAIASANAMIAAhaIhKAAIAAgkIA5AAIAAgbIgvAAIAAgkIAvAAIAAglIAoAAIAAAlIArAAIAAAkIgrAAIAAAbIA0AAIAAAkIglAAIAAAhIAhAAIAAAkIghAAIAAAlQAOACAvAAIB2gCQgIATgGAXQh1AAgvgDQgvgDgUghQgGAagKAUIgfghgAU0EuIAtACQARAAAAgSIAAi+IiFAAIAAggICsAAIAADYQAAA2gmADQggACgXAAQgEgWgEgPgASNFTIAAjpIAnAAIAADpgAUBFBIAAhtIgcAAIAABQIghAAIAAhvIA9AAIAAgYIhFAAIAAggIBFAAIgHgRIAngKIAJAbIBBAAIAAAgIhGAAIAAAYIA+AAIAABJQgBAmgjAAIgUgBIgFghIASABQAJAAAAgOIAAghIgcAAIAABtgAnXEjQgOgOAAgWQAAgvA3gHIAtgGQAAgdgeAAQgdAAgZASIAAgkQALgHASgDQASgEAOAAQBDAAAABEIAABiIgsAAIAAgYIgBAAQgRAcggAAQgXAAgNgNgAmgDiQgZAEAAAUQAAAJAGAFQAGAGALAAQAOAAAJgLQAKgKAAgPIAAgMgApjEsIAAhdQAAglgbAAQgOAAgIALQgJAKAAAQIAABdIgwAAIAAjwIAwAAIAABmIAAAAQATgcAfAAQA3AAAABCIAABkgAPqEUQgoAAAAgqIAAhbIBLAAIAAgqIhRAAIAAgkIB4AAIAAByIhKAAIAAAwQAAAOAPAAIANAAQAMAAAEgHQADgGACgmQAYAKAQAGQgEAigFALQgJAZgkAAgAt2EUQgnAAAAgqIAAhbIBKAAIAAgqIhQAAIAAgkIB4AAIAAByIhLAAIAAAwQAAAOAPAAIAOAAQALAAAEgHQAEgGABgmQAZAKAQAGQgFAigFALQgIAZglAAgAHKDYIAAgsIEbAAIAAAsgA2VDYIAAgsIEbAAIAAAsgASfBHIAcgXIAnAnIgfAaQgQgVgUgVgA2Wh0QA7ghAFhEIhCAAIAAgmIBCAAIAAg8Ig1AFIgGgnQBRgGBMgLIAJAmIhAAIIAABBIBQAAIAAh1IArAAIAAB1IA5AAIAAAmIg5AAIAACCIgrAAIAAiCIhQAAQgDBZhFAuQgRgTgSgPgAj7hrQAegeAAg2IAAhlQBDgGAqgNIAQAiQgkAIgzAFIAAAgIBYAAIAAAiIgXAAIAABxIgmAAIAAhxIgbAAQAABIgiArQgQgMgSgMgAreh9QAkg0ABhuIghAAIAAgmIAiAAIABgxIAmAAIgBAxIBDAAIgEC7QgBAVgIAKQgIALgLADQgMACgiAAIgKgsIAeACQAHAAAEgDQADgDABgGQABgFABgnIAChiIgdAAQgBCLgzBBIgXgqgARkhUIARhPIApAAIgYBPgAC6hUIAAgKIiYAAIAAAKIgmAAIAAhKIDlAAIAABKgAAih3ICYAAIAAgOIiYAAgANuh5QgWAUgcAQIgPgYIAAAYIgmAAIAAkWICjAAIgCAzQgBAUgMALQgLAKgUABIgxgBQgCgPgGgVQAaACAQAAQALAAAFgEQAEgFAAgOIhUAAIAABHICBAAIAAAgQgNAqgaAiQAYAPAdAKIgYAnQgegOgYgWgAMth/QAVgKARgMQgUgYgPgdIAZgTQAOAcAUAUQASgWAJgcIhZAAgAvEhpQAcgmATgtIAgAPQgZA2gXAiQgTgNgMgHgAvqhVIAAgvIhLAOIgHgoIAPgCIAAijIgMAAIAAgjIB/AAIAAAjIgMAAIAACUIARgDIgDAlIgOADIAAA1gAwKikIAggFIAAgeIggAAgAwKjmIAgAAIAAgfIggAAgAwKklIAgAAIAAgeIggAAgAKbh+IAUABQAHAAADgDQADgDAAgIIAAg0IgfAIIgFgqIAkgHIAAg0IgfAAIAAgmIAfAAIAAg0IAmAAIAAA0IAdAAIAAAmIgdAAIAAAtIAegHQgBAaAAANIgdAHIAABMQAAAUgKAJQgLAJgoAAIgKgogAG2hWIAAhhQgkAvg9AiQgOgTgMgQQA5gYAogrIhcAAIAAgmIBBAAQgLgQgWgZIAbgUIgtAAIAAgmIBoAAIAAggIAqAAIAAAgIBqAAIAAAmIgwAAIAdAWQgTAXgRAQIBGAAIAAAmIhgAAQAoAqA7AVQgOASgMATQg/ghgjguIAABhgAHgjyIAvAAIgagWQASgRASgWIg5AAgAGhkHIgcAVIAxAAIAAg9Ig4AAQARARASAXgAtlisIAegPQAZAqAWAqIghARQgWgwgWgmgAlfh1IgJAQQgNgIgOgHQAPgaAIgWIAeALIgPAgIAPABQALAAAAgLIAAgjIg2AAIAAgdIA2AAIAAgSIg7AAIAAgdIAgAAIgLgTIAlAAIAMATIASAAIAKgTIApAAIgNATIAdAAIAAAdIg6AAIAAASIA1AAIAAAdIg1AAIAAAxQAAAagbADIghABQgBgPgFgPgAo+hbIAAkCIB2AAIAAEBIgnAAIAAgYIgoAAIAAAZgAoXibIAoAAIAAicIgoAAgAkYiXIAYgNIAVAfIgaAQQgLgWgIgMgAggirIAAgbIBAAAIgIgQIATgEIgrAAIAAg/IDeAAIAAA/IgtAAIAUAEIgOAQIBIAAIAAAbgABQjGIA4AAIAOgUIhSAAIAMAUgAAljzICRAAIAAgNIiRAAgAuxjOIAAiVICIAAIAACVgAuLjxIA9AAIAAhPIg9AAgAl5kMIAAgdIA3AAIgEgRIAWAAIAAgIIhPAAIAAghIBPAAIAAgSIAnAAIAAASIA2AAIAAgSIAnAAIAAASIBPAAIAAAhIhPAAIAAANIgnAAIAAgNIg2AAIAAANIgWAAIADAMIAyAAIAAAdgAgLkmIAAgZIBkAAIAAgNIh0AAIAAgbIB0AAIAAgQIApAAIAAAQIB2AAIAAAbIh2AAIAAANIBlAAIAAAZg");
	this.shape_4.setTransform(261.8,98.2,1.867,1.867);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAEFOQAhgfARg4IgxAAIAAghIEhAAIAAAhIh6AAIAAASIBkAAIAAAgIhkAAIAAATIAvAAIBMAAIgMAiIhLAAIgqgBQhEAAgegfQgOAYgQAQIgigYgABcEFIgJAZQATAUAfAGIAAhBIhOAAgAsRFmIARhPIAqAAIgYBPgATYFmIAAiNIgXAjQgGgegIgZQAmg/AXhDIAoAKQgKAggNAeIAADbgAisFKQASgTAMgZIgYASIgagkIAAA1QAAANgHAJQgIAJgQAAIgiABIgFgYIgggLQANgkAIgnIAiAJQgJAkgIAbQAVABADgEQADgEAAgFIAAhDIgyAAIAAhYIB8AAIAABYIglAAIAAAaIAWgRIAeAkQATgsACg8IgZAAIAAglIAaAAIAAhIIAnAAIgBBIIBJAAIAAAlIhKAAIgBAUIAcAAIAABwQAAAHAHAAQAFAAACgGQACgGACgqIAhAKQgGA3gEAIQgEAJgIAEQgIAEgMAAIgLAAQghAAAAgkIAAheQgLBTgpA1QgPgPgQgNgAjzDOIA1AAIAAgcIg1AAgAzjFmIAAgPIh5AAIAAAPIglAAIAAjZIA4AAIAAgcIg9AAIAAgEIgaAcIgtgnIAZgaQAdAVARAOIAAgbIDRAAIAAAhIhAAAIAAAcIA3AAIAADZgA1cE3IB5AAIAAgUIh5AAgA1cEEIB5AAIAAgRIgSAAQghAAAAgjIAAgkIgTAAQgBAwgZAhQgOgOgLgJgA1cDhQARgZABgcIgSAAgAz1DJQAAALALAAIAHAAIAAgoIgSAAgA0oCNIASAAIAAgcIgSAAgAU4FlQgDgYgEgRQAPACAZAAQAQAAAAgTIAAhDIhYAAIAAgnIBYAAIAAgZIAygvIh3AAIAAgnICpAAIAAAqIg6A5IAAAMIBEAAIAAAnIhEAAIAABUQAAAKgDAIQgDAJgHAGQgIAGgWABIgjABIgNAAgAyqFCQAPgZAGgfQAGgfAAg9IAAheIDvAAIAABaIjGAAIAAASIDTAAIgCB2QAAAWgHAKQgGAKgJAEQgKAFhAAAQgDgSgFgUIApABQAJAAAFgDQAFgEABgFQABgFABgwIAAghIipAAQAABWgjAxQgTgWgNgNgAxmCJICcAAIAAgXIicAAgAmeE4QgZARgcAPQgJgRgPgSQAigOAdgUQgIghgDg0Ig7AAIAAAgIAygHIgBAYIAAAQIgxAGIAAA6QAAAQgHAJQgIAIgTACQgTABgZAAQgFgagGgNQAOACAPAAIAGAAQAFAAADgEQACgEAAgIIAAgjIguAHIgHgpIA1gGIAAglIg1AAIAAgmIA1AAIAAgcIgpADIgFgmQBBgDA9gJIAJAkIgtAGIAAAhIA5AAIgEhTIApAAIADBTIBgAAIAAAmIheAAQACAhAEAYQAagYAUgeIAgAaQgdAlglAeQAMAcAOAAIAFgBQACgBAEgPQAEgPADgVQAUAOAPAGQgIAsgLAQQgKAQgTAAQgqAAgWgtgAFSFiIAAiBIgWAiIgMg4QAjg7AXhLIAnANQgLAhgNAgIAADPgAMBE1QAWACAYAAQAHAAAFgBQAGgCADgDQADgEABgEQACgEAAggIACg8IAAgtIgzAAQgJAUgLAUQgOgJgVgJIAACuIgpAAIAAgVIgpAAIAAAXIgpAAIAAjuIAfAAQAIgdAEgSIArAHIgNAoIAyAAIAAA5QAYgoAVhAIApAKIgOAmIBLAAIgDCpQgBAbgDALQgEALgIAHQgIAHgPACQgOADgxAAQgEgagHgTgAKQElIApAAIAAgyIgpAAgAKQDMIApAAIAAgyIgpAAgA3SFVQAQgtAQhDQAYAJAPAEQgPBBgQAuIgogMgAQDE1IBOACQANAAAFgEQAGgFACgGQADgHABg/IjCAAIAJhgIAuAAIgHA7IBkAAIAHhIIimAAIAAglIDYAAIgLBtIAuAAQgCBVgCAaQgCAagPAMQgPANgaABIhSABQgEgVgGgXgAG1FgQgCgRgFgUIAYABQALAAAEgDQAEgDAAgIIAAiPIApAAIAACbQAAARgHAKQgHAJgRABIggABIgOAAgAxVFFIAAhXIB5AAIAABJIhTAAIAAAOgAwvEcIAuAAIAAgUIguAAgAINDRIAkgKQAMAgAWBEIgpANQgPg8gOgrgAGCEmQAUgrARg3IAlAKQgPA4gWAwQgRgIgUgIgAOKEeIAAgmIDTAAIAAAmgALuDWIAigXQAVAZAZAkIglAZQgXglgUgagA3WCvIAYgdQAgAZATARIgbAeIgwgrgAGDCvQAcgrATg+IAqAGIgKAdIB6AAIAAAiIgNA0IgngIIALgpIhhAAQgPAhgSAZIgegZgAAnDIIAAh7IDdAAIAAB7gABPCnICNAAIAAgQIiNAAgABPB9ICNAAIAAgPIiNAAgAmKBlIAZgZQAiAcARARIgcAaQgVgYgbgWgAhMBgIAYgVQATASATAVIgaAXQgQgUgUgVgAkjCEIAAgiIA4AAIgHgaIArgFIAHAfIAzAAIAAAigAn6hiQBugcA7g6IAdAYQhBBChvAfIgWgjgALJhCIARhPIAqAAIgYBPgAsRhCIARhPIAqAAIgYBPgAHMhDIAAgxIgvAAIAAgfQgLAQgNAQIgWghIAABRIgjAAIAAiBQgJARgKAOQgEgbgGgcQAXgsAZhbIAmAKQgKAlgMAgIAAB4QAvgxAXhCIg1AAIAAglIBMAAIAAgvIAnAAIAAAvIBUAAIAAAlIg/AAQAXA+A0AwIgZAqQgMgMgKgPIAAAeIgxAAIAAAxgAHziZIAsAAQgbgpgRg7gAGhiZIArAAIAAhlQgOA3gdAugA3WhmQApgTATgVQATgUACglIg1AAIAAiQIDoAAIAACQIg7AAIAABDQAAAWAQAAIAMAAQAJAAAEgHQADgIAFglIApAPQgGAggFAPQgHAcgoAAIgfAAQgsAAAAgwIAAhPIgiAAQgDAygWAeQgWAdgwAXQgKgOgTgVgA2RjsICVAAIAAhGIiVAAgAVPhsIAvACQAQAAAAgRIAAgEIh9AAIAAA7IgqAAIAAiBQgTAUgWASIgKguQArglAbgvIhEAAIAAgkIBXAAQAHgQAFgQIAuAHIgKAZICYAAIAAAkIiqAAIgNAWICbAAIAACfQAAASgJAKQgJAKgQABQgPACguAAQgEgUgHgVgAURifIB9AAIAAgVIh9AAgAURjUIB9AAIAAgVIh9AAgAkBhDIAAkdIAiAAIAAAzIAdAMIgKAiIgTgKIAADGgAwuhDIAAhXQglAyhCAgIgZgkQA7gXAggjIhMAAIANheIBkAAIAAgaIhrAAIAAgjIA3AAIgQgVIAkgPIAcAkIAzAAQANgSAMgSIAoAPIgSAVIAzAAIAABfIhoAAIAAAaIB2AAIgDA8QgBAWgMALQgLAKgQACQgQACglgBQgEgTgGgTQASACAUAAQALAAAIgFQAIgFAAgaIhNAAIAABjgAxyjIIBEAAIAAgaIhBAAgAwFkEIA/AAIAAgaIg/AAgAOmhEIAAhEIgdAAIAAgjIAdAAIAAh0IBgAAIAAgUIh2AAIAAgkIEUAAIAAAkIh2AAIAAAUIBgAAIAAB0IAdAAIAAAjIgdAAIAAAVQAAAUgJALQgIALgOACQgPACgrAAQgDgWgEgRIAkACQAOAAADgGQADgGAAgHIAAgLIiYAAIAABEgAQuirIA4AAIAAgYIg4AAgAPOirIA4AAIAAgYIg4AAgAQujlIA4AAIAAgYIg4AAgAPOjlIA4AAIAAgYIg4AAgAi9hEIAAiUICrAAIAACTIgoAAIAAgOIhbAAIAAAPgAiVhyIBbAAIAAgUIhbAAgAiVikIBbAAIAAgVIhbAAgACdhFIgHgmQAUACAYAAQAQAAAAgRIAAgWQhPAqhrAeQgMgagJgNQBVgQBBgcIiTAAIAAgjIAiAAIAAiMIBBAAIAOgbIAuAGIgOAVIBjAAIAAB3IAXgTIAYAcQgVASgaAQIAAAzQAAAwgsAAgABQi+ICCAAIAAgSIiCAAgABQjqICCAAIAAgSIiCAAgABQkVICCAAIAAgSIiCAAgApSiBIAhgHIAAhCIgbAAIAAgpIAbAAIAAg1IgeAAIAAgoIBmAAIAAAoIggAAIAAA1IAWAAIAAApIgWAAIAAA4IAcgIQgBATABAWQgzANgsAOgAnpigQBIgbAygrIAcAYQg4AvhHAhQgIgQgPgSgAnpjbQAxgVAngiIAbAYQgpAkg0AbQgHgLgPgVgAkpjUQAJgrAEgsIAYACQgFAxgHApIgZgFgAjIjoIAAgfIAjAAIAAgbIgeAAIAAgfIAeAAIAAghIAoAAIAAAhIAsAAIAAghIAoAAIAAAhIAdAAIAAAfIgdAAIAAAbIAkAAIAAAfgAh9kHIAsAAIAAgbIgsAAgAn+kSQA3ggAegyIArAAIgEAHQAjAuAyAXIgVAkQg3gdgegtQgeAvg1AhQgJgTgLgRg");
	this.shape_5.setTransform(258.1,91.1,1.867,1.867);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.ani1_元件49111 = function() {
	this.initialize();

	// 图层 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AtlFJQA0gzAAhvIABgwIgZAAIAAgjICQAAIAAAiIgUA3IAnAAQAAA/gCA8QgBA0gvACIgsABQgCgPgGgaIAjACQAaAAAAgVQADgpAAgqIgoAAIAAgiIAUg3IgqAAIAAAwQgBCAg4BAQgMgMgWgSgApiE+QAlg0ABhuIgiAAIAAgnIAjAAIAAgxIAmAAIAAAxIBCAAIgEC7QgBAVgIALQgIAKgLADQgLACgjAAIgKgrIAeABQAHAAAEgDQAEgDABgGQABgFABgnIABhhIgcAAQgCCKgzBBIgXgpgAQQFTQhDAJhQAHIgHglIBNgGIAAggIhCAAIAAhdIBCAAIAAgUIg4AAIAAhYICWAAIAABYIg5AAIAAAUIBDAAIAABdIgPAAQAPAdAPAkIgiANgAPoE1IAagDIgHgOIAhgMIg0AAgAPoD4IAfAAIAAgdIgfAAgAOlD4IAeAAIAAgdIgeAAgAOwCGIBMAAIAAgWIhMAAgAFUFTQhDAJhQAHIgHglIBNgGIAAggIhCAAIAAhdIBCAAIAAgUIg4AAIAAhYICWAAIAABYIg5AAIAAAUIBDAAIAABdIgPAAQAPAdAPAkIgiANgAEsE1IAagDIgHgOIAhgMIg0AAgAEsD4IAfAAIAAgdIgfAAgADpD4IAeAAIAAgdIgeAAgAD0CGIBMAAIAAgWIhMAAgAi3E9IAiACQAQAAAAgQIAAgkIhUAAIAAgaIgXAMQgQgfgGgJQBTgbAxg0IAxAAIgIAIQAwArBHAUQgMAVgIAVIgWgLIAAAfIhQAAIAAAtQAAApgfACIg0ABIgIgngAhcDJIAAAfIBIAAQg3gbgmgjQgfAfg4AfIBDAAIAAgfgAxWFJIhbAAIAAhHIgQgPIAABUIggAAIAAgTIgQAAIAAAZIghAAIAAjwIBRAAIAACJQAUgSAPgVIgRAAIAAhyIChAAIAAByIhoAAIgJAPIB7AAQAAAtgDA6QAAArgfACQgLABggABIgFgbgAyeD3IAMAAIAAA2IBbAAIAAAVQAOAAAAgSIADhEIgnAAIgEAJIAnAeIgTAXIgigeQgMARgQAOQgHgJgPgOQAWgRAOgXIgoAAgAzxESIAQAAIAAiUIgQAAgAyLChIBZAAIAAgPIhZAAgAyLB6IBZAAIAAgPIhZAAgAMiFjIgIgoIAfACQALgBAEgHQADgJABgwIg0AAIAHhoIAyAAIAAgiIg4AAIAAgjIBcAAIAABoIg0AAIgCAjIAzAAQgBBHgCAVQgCAWgGAIQgGAJgLAEQgIACggAAIgMAAgABmFjIgIgoIAfACQALgBAEgHQADgJABgwIg0AAIAHhoIAyAAIAAgiIg4AAIAAgjIBcAAIAABoIg0AAIgCAjIAzAAQgBBHgCAVQgCAWgGAIQgGAJgLAEQgIACggAAIgMAAgAIGE3QAYACAQAAQARAAAAgSIAAg6IhyAAIAAgpQAVgaASgcIg5AAIAAgmIBQAAQAKgSAIgTIAxAFIgQAgICWAAIAAAmIitAAQgRAbgWAdIA/AAIAAgpIAsAAIAAApIBfAAIAAAnIhfAAIAABDQAAAXgKALQgJAMgRADQgRACgmAAIgKgsgAvBFCQAcgTASgcIgnghQAJghAIg2IgVAAIAAgjIAbAAIAGg0IAmADIgIAxIA0AAQgCBbgWA3IAWARIgZAhIgQgPQgVAggeAWQgKgPgOgSgAuTDmIASANQAPgkADg0IgWAAQgHAtgHAegAnCFfIAAkCIB3AAIAAEBIgoAAIAAgYIgnAAIAAAZgAmaEfIAnAAIAAibIgnAAgAg8EpIAZgaQAkAbAaAVIgbAeIg8g0gAkCE+QAjgZAZgYIAcAaQgeAcghAZIgZgegAGzE4QAigeAkgnIAiAbQgkAnglAjQgOgRgRgPgAJ6EWIAbgdIBHA5IgeAhQgfgeglgfgAhICTIAAgVIhSAAIAAAVIgpAAIAAgVIg6AAIAAgjIA6AAIAAgWIApAAIAAAWIBSAAIAAgWIAoAAIAAAWIA9AAIAAAjIg9AAIAAAVgAh6hPIAGgJIgsAAIAAAYIgkAAIAAgYIg7AAIAAgVIA7AAIAAgKIgvAAIAAgxIAvAAIAAgLIggAAIAAgbIgbAAIAAgVIAbAAIAAgJIAcAAIAAAJIArAAIAAgJIAdAAIAAAJIAZAAIAAAVIgZAAIAAAbIggAAIAAALIAxAAIAAAxIgxAAIAAAKIAwAAIAAAOQAQgaAAg2IAAg4IBtAAIAACAQAAAjgfABIglABIgGghIAgABQAKAAAAgLIAAgJIguAAQgFAagTAeQgRgJgQgIgAigiJIAUAAIAAgOIgUAAgAjXiJIATAAIAAgOIgTAAgAg+iQIArAAIAAgRIgqAAIgBARgAg9i5IAqAAIAAgRIgqAAgAjIjEIArAAIAAgKIgrAAgATghBIARhQIAqAAIgYBQgAIOhgQA4gpAAhRIAChTIgkAAIAAglICoAAIgFDMQAAAagIAOQgIAOgPADQgOADgwABQgEgUgGgZIAmACQANAAAFgFQAFgGABgIQACgIACieIgwAAQgDBpgFAdQgEAcgPAcQgPAcgYASQgNgOgVgRgAu5hQQAPgwAOhAIAlAOIgcBuIgmgMgAo4hEIAAheQgNAdgOAUIgPgvQAYgdARgtIgmAAIAAglIAnAAIAAghIgiAEIgEgjQA7gGAtgGIAHAiIgkAFIAAAlIAeAAQAagrAIgnIAmAFIgJAeIBxAAIAAAiIgMAzIgkgIIAKgqIhZAAQgLAbgQAWIgUgYIAAAYIggAAIAAAQIAlAYIgRAfIgUgRIAABwgAzNhEQgEgVgGgSIApABQAUAAAAgSIAAgSIiAAAIAAgkICAAAIAAgHIAogZIhrAAIAAgkICkAAIAAAjIgyAhIBtAAIAAAkIhxAAIAAAfQAAAUgMALQgLAMgXAAIgwAAgAnShHQgDgVgEgRQANACAOgBQAOABAAgNIAAiQIAnAAIAACYQAAATgHAJQgHAKgOABQgLACgWAAIgMAAgAt5hLIAAgfIDaAAIAAAfgAOAhNIAAkKICyAAIAAAjIiNAAIAADFICRAAIAAAigADEhNIAAkKICyAAIAAAjIiNAAIAADFICRAAIAAAigAHPh+QAIgJAAgUIAAhQIgeADIgCgmIAggDIAAhQIAoAAIAABMIAtgEIACAmIgvAFIAABMIAogdQAAAbACARQg3ApgIAMgAMghjIAAjpIBQAAIAADhIgfAAIAAgTIgPAAIAAAbgANCijIAPAAIAAiDIgPAAgABkhjIAAjpIBQAAIAADhIgfAAIAAgTIgPAAIAAAbgACGijIAPAAIAAiDIgPAAgAl/jXIAhgKQALAfAVBFIgmAOQgOg8gNgsgAoBiCQAVgxANguIAjAKQgNAzgVAyIgjgQgAtgh5IAAhzIgJAGQgKgQgNgRQAogQAcgWIgtAAIAAgeIBJAAIAAgZIAmAAIAAAZIBPAAIAAAeIg4AAQAeAVArALQgNAVgGAQIgNgGIAAB1gAs6iYIBaAAIAAgSIhaAAgAs6jFIBaAAIAAgSIhaAAgArEj0QgggTgWgXIAAAhIgmAAIAAgiQgWAXgdAUICPAAIAAAAgAOsiIIAAgfIAwAAIAAgbIgnAAIAAgfIAnAAIAAgcIgsAAIAAgeIB8AAIAAAeIgtAAIAAAcIAoAAIAAAfIgoAAIAAAbIAyAAIAAAfgADwiIIAAgfIAwAAIAAgbIgnAAIAAgfIAnAAIAAgcIgsAAIAAgeIB8AAIAAAeIgtAAIAAAcIAoAAIAAAfIgoAAIAAAbIAyAAIAAAfgAvAj4IAYgcQAXARAYAUIgbAgQgJgKgjgfgAwsjnIAAglIjAAAIAAAlIgpAAIAAhIIAwAAIgZggIAfgVQASATASAZIgNAJIAxAAQgNgYgKgQIAkgQQALASAQAcIgUAKIAkAAIAigyIAnAVIgXAdIAqAAIAABIgAhSjyIAAgPIBLAAIAAAPgAjdjyIAAgPIBMAAIAAAPgAiEj1IAAgtIhVAAIAAAYIgiAAIAAgtIB3AAIAAgMIhoAAIAAgWIDzAAIAAAWIhnAAIAAAMIB1AAIAAAtIggAAIAAgYIhVAAIAAAtgAhSkKIAAgPIBAAAIAAAPgAjRkKIAAgPIBAAAIAAAPgAu3lHIAYgaIAxAkIgcAeQgVgVgYgTg");
	this.shape.setTransform(166.9,62);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#993300").s().p("A6KKUIAA0nMA0VAAAIAAUng");
	this.shape_1.setTransform(167.5,79,1,1,0,0,0,0,13);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,335.1,132.1);


(lib.ani1_元件49 = function() {
	this.initialize();

	// 图层 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AzpFnIAAgKIiYAAIAAAKIgnAAIAAhKIDnAAIAABKgA2BFEICYAAIAAgOIiYAAgADBFnIAAiMQgmAug4AoIgegnQBdg8AjhOIhzAAIAAgoIENAAIAAAoIhpAAQgJAZgOAWIAPAAIAAAjIAdgdIBfBXIgiAiQglgrg1gwIAACUgAohE6IAdgZIAAhKIgbAAIAAglIBBAAIAABvQAXAaAyAAQBpAAArgCIgNAmIhKABQhRAAgNgCQgOgDgOgFQgPgFgOgNIgiAigAtXE6IAdgZIAAhKIgbAAIAAglIBBAAIAABvQAXAaAyAAQBpAAArgCIgNAmIhKABQhRAAgNgCQgOgDgOgFQgPgFgOgNIgiAigAjRFmIAAiIQgJAQgKAQQgEgYgHgcQAcgxAWhTIAlAIQgKAhgLAeIAADZgAhsFlIgHgkQAPABAUAAQAOABAAgRIAAgLIhOAAIAAgeICxAAIAAAeIg8AAIAAAWQAAAlgfACIgjABIgPAAgAxCFkQgCgRgEgUIAmACQAPAAAAgOIhqAAIAAgZIBqAAIAAgOIh8AAIAAgaIB8AAIAAgNIhpAAIAAgaIBpAAIAAgOIhhAAIAAg9IBhAAIAAgOIh6AAIAAgaIB6AAIAAgTIAoAAIAAATIB7AAIAAAaIh7AAIAAAOIBiAAIAAA9IhiAAIAAAOIBmAAIAAAnIAXAAIAAAaIgXAAIAAA1IgnAAIAAgOIg/AAIAAAIQAAAOgFAKQgFAJgKADQgLAFgEAAIg0AAgAvrEaIA/AAIAAgOIg/AAgAvrDyIA/AAIAAgNIg/AAgAvrCmIA8AAIAAgPIg8AAgAxOCmIA7AAIAAgPIg7AAgAG9FgQgEgVgGgYQAcAEASAAQASAAAFgHQAFgIAAgLIAAhlQAkgYAugjIjJAAIAAgoIENAAIAAAoIhoBOIAABeQAAAcgOAOQgOANgcAAgAl1E3IAAghIhcAAIAAgiIBcAAIAAgcIhUAAIAAgfQAOgYAMgcIgcAAIAAgiIArAAIALgfIAqAHIgKAYIBoAAIAAAiIh3AAIgYAwIAnAAIAAglIAnAAIAAAlIA/AAIAAAjIg/AAIAAAcIBIAAIAAAiIhIAAIAAAhgAqrE3IAAghIhcAAIAAgiIBcAAIAAgcIhUAAIAAgfQAOgYAMgcIgcAAIAAgiIArAAIALgfIAqAHIgKAYIBoAAIAAAiIh3AAIgYAwIAnAAIAAglIAnAAIAAAlIA/AAIAAAjIg/AAIAAAcIBIAAIAAAiIhIAAIAAAhgA3FERIAAgbIBDAAIgJgRIAUgEIguAAIAAg/IDgAAIAAA/IgtAAIAVAFIgPAQIBJAAIAAAbgA1SD2IA4AAIAOgVIhSAAIAMAVgA19DJICRAAIAAgOIiRAAgAAMEEIAAgQIiKAAIAAAQIgmAAIAAguIDXAAIAAAugAiJDLIAAhDICjAAIAABDgAhjCxIBZAAIAAgPIhZAAgAoYBeIAfgUQAXAcARAaIgiAXQgSgfgTgagAtOBeIAfgUQAXAcARAaIgiAXQgSgfgTgagA2vCVIAAgZIBmAAIAAgNIh2AAIAAgbIB2AAIAAgPIApAAIAAAPIB2AAIAAAbIh2AAIAAANIBlAAIAAAZgAibB8IAAgdIBQAAIgIgSIArgIIAJAaIBQAAIAAAdgAWLhAIARhQIAqAAIgYBQgAGehBIAAhqIgYAZIgLgxQAjghASgjIgxAAIAAgnIAvAAQgNgUgMgRIAigSQAQAUANATIgeAQIAnAAIAAAgQgMAZgNAVIAAAIIAMgHIASAaIAAgLICyAAIAACNIgnAAIAAgNIhkAAIAAANIgnAAIAAhpIgQAJIgOgbIAAB9gAJOhtIAfAAIAAgVIgfAAgAIJhtIAfAAIAAgVIgfAAgAJOieIAfAAIAAgWIgfAAgAIJieIAfAAIAAgWIgfAAgABThBIAAkWIEIAAIAAEVIglAAIAAgMIi+AAIAAANgAB4htIC+AAIAAjLIi+AAgA1KhBIAAhFIh5AAIAAgkIB5AAIAAggIhbAAIAAgjIBbAAIAAghIhvAAIAAgjIBFAAIgcgfIAfgXIAoAoIgVAOIA3AAQAUgZATgcIAsATIgfAiIBCAAIAAAjIhtAAIAAAhIBaAAIAAAjIhaAAIAAAgIB4AAIAAAkIh4AAIAABFgAnKhmQgfAPgkANQgKgSgNgRQBWgVA3gqIgGgMQgwAig9AQIgUgeQBGgOAtgcIgHgKQgnATgwAMQgJgQgKgOQA7gKAqgVIgxAAIAAggICrAAIAAAgIhAAAIgTAMQAMAQAJAPQAxgXAggUIAXAhIguAWQAUAyAsAaIggAgQgmgdgZhCIgMAGQAHAXAAAWQAAATgEALQgDAMgJAIQgJAIgMABQgLACgsAAQgEgUgFgQgAnGhpQASADAMAAQAbAAAAgbIgCgMQgYAVgfAPgAwChCIAAg+IiLAAIAAglIApAAIAAhIIgQARIgagmQAsgkAYg+IAuAHIgLAZICuAAIAAAlIheAAIAAAmIBTAAIAAAmIhTAAIAAAuIBnAAIAAAlIhnAAIAAA+gAw7ilIA5AAIAAguIg5AAgAxZj5IBXAAIAAgmIg6AAQgNAUgQASgAK4hPQAPgzAOg9IAlAOIgcBvQgTgHgTgGgAMChDIAAicIA3AAIAAgYIhAAAIAAgfIDaAAIAAAfIg9AAIAAAYIA0AAIAAB0QAAARgIAJQgHAKgNABQgMACgoAAQgDgPgFgOIgegSQANgOAIgSIgOAMIgKgMQgJAYgSAaQgDgFgMgIIAAArgAN0hjIAgABQARABAAgRIAAgRIgLALIgPgSQgIAVgPASgAMliFQASgbACgkIgUAAgAOUirIATAUIAAgtIgRAAIgCAZgANYixIAVAVQAGgSABgWIgaAAQAAAMgCAHgANajfIAbAAIAAgYIgbAAgAjihDIAAkUIEJAAIAAETIgnAAIAAgKIi5AAIAAALgAi5hyIC5AAIAAjBIi5AAgAPqhLIAAgiIB7AAIAAgSIhkAAIAAghIBkAAIAAgRIhPAAIAAg5IglAAIAAhIIA5AAIghgZIAXgZQAdAVATAOIgNAPIAjAAIAAgxIAnAAIAAAxIAgAAIgLgMQAZgTAWgTIAaAXIgiAbIA5AAIAABIIgmAAIAAA5IhPAAIAAARIBkAAIAAAhIhkAAIAAASIB9AAIAAAigAQ9jPIB3AAIAAgTIh3AAgAQZkAIDAAAIAAgQIjAAAgAtNhMIAAgmIBuAAIAAgjIhXAAIAAgmIBXAAIAAgdIg4AAIAAgXIgqAbIgagiQBegzAig5IAzAAIgIALQAmA2BTAnIgaAiQgWgLgTgNIAAAYIg5AAIAAAdIBYAAIAAAmIhYAAIAAAjIBvAAIAAAmgAsFj9IB4AAQgjgcgZgfQgYAegkAdgADXiOQgZAWgxAJIgPgfQAwgGANgLQAOgLACgTIAhAAQgBAOgFAMIBOAaIgRAbgAiAidIAhABQAXAAAAgYIAAgwQgeAtg4AqQgNgTgMgNQA0geAhglIhLAAIAAgiIBlAAIAAgaIAnAAIAAAaIAVAAIAAAiIgVAAIAAA/QAAAagMAOQgMAOgXACIgoABIgIglgAEFibIAAgrIhcAAIAAArIggAAIAAhGICcAAIAABGgAKxj3IAYgcQAXAQAYAWIgbAfIgsgpgAHujeIAAhLICaAAIAABLgAIWj8IBKAAIAAgQIhKAAgACUjsIAAhAICGAAIAABAgACykFIBKAAIAAgNIhKAAgAkyj/IAAgpIjBAAIAAApIgoAAIAAhLIByAAIgJgUIAzgGIAIAaIBtAAIAABLgAN9kZIAAgSIguAAIAAASIgmAAIAAgSIgwAAIAAgLIgXAYQgTgTgYgUIAYgbQATANAXAUIAAgLIAwAAIAAgYIAmAAIAAAYIAuAAIAAgZIAmAAIAAAZIAwAAIAAAfIgwAAIAAASgAHkk4IAAgfICxAAIAAAfg");
	this.shape.setTransform(168.8,61.9);

	// greet1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#993300").s().p("A6KKUIAA0nMA0VAAAIAAUng");
	this.shape_1.setTransform(167.5,79,1,1,0,0,0,0,13);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,335.1,132.1);


(lib.ani1_元件41 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.aniUI01_Bitmap1();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,65,79);


(lib.ani1_元件40 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.aniUI01_Bitmap3();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,15,22);


(lib.ani1_元件9 = function() {
	this.initialize();

	// 图层 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF9B7F").s().p("ABAAnIg4hLIALAAIA7BLgAANAnIg2hLIALAAIA5BLgAgYAnIg4hLIALAAIA7BLgAhIAnIg4hLIALAAIA7BLgAByAkIg4hKIALAAIA8BKg");
	this.shape.setTransform(12.9,4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,25.8,7.9);


(lib.ani1_元件3 = function() {
	this.initialize();

	// 图层 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0.424)","rgba(255,255,255,0)"],[0,1],-14.2,0,14.3,0).s().p("EgD3AouQgUAAAAhCMAAAhPXQAAhCAUAAIHvAAQAUAAAABCMAAABPXQAABCgUAAg");
	this.shape.setTransform(26.9,260.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(255,255,255,0.424)","rgba(255,255,255,0)"],[0,1],-7.4,0,7.5,0).s().p("EgCBAouQgKAAAAhCMAAAhPXQAAhCAKAAIEDAAQAKAAAABCMAAABPXQAABCgKAAg");
	this.shape_1.setTransform(55.4,260.7);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,69.5,521.4);


(lib.ani1_bjmc = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.bj();
	this.instance.setTransform(-320,-480,1,1.563);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-320,-480,640,1500);


(lib.ani1_我擦擦 = function() {
	this.initialize();

	// 图层 3
	this.instance = new lib.duquzhong01();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-5.7,0,320.8,36);


(lib.ani1_补间20 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.aniUI01_Bitmap2();
	this.instance.setTransform(-114.7,-129.2);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-114.7,-129.2,229,259);


(lib.ani1_元件29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF9900").s().p("A/3WRMAAAgshMA/vAAAMAAAAshg");
	this.shape.setTransform(204.1,142.6);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.role2_元件37 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role2_Bitmap10();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,8,8);


(lib.role2_元件35 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role2_Bitmap9();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,39,23);


(lib.role2_元件34 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role2_Bitmap2();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,30,20);


(lib.role2_元件33 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role2_Bitmap3();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,30,20);


(lib.role2_元件31 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role2_Bitmap8();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,30,103);


(lib.role2_元件30 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role2_Bitmap6();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,51,93);


(lib.role2_元件28 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role2_Bitmap7();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,40,73);


(lib.role2_元件27 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role2_Bitmap4();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,91,25);


(lib.role2_元件25 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role2_Bitmap1();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,235,129);


(lib.role2_补间17 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role2_Bitmap11();
	this.instance.setTransform(-79.1,-97.2);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-79.1,-97.2,158,194);


(lib.role1_元件16 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role1_Bitmap3();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,22,95);


(lib.role1_元件14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 1
	this.instance = new lib.role1_Bitmap12();
	this.instance.setTransform(0.9,3.4);

	this.instance_1 = new lib.role1_Bitmap13();

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},3).wait(3));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.9,3.4,104,22);


(lib.role1_元件13 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role1_Bitmap4();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,53,60);


(lib.role1_元件12 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role1_Bitmap5();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,47,63);


(lib.role1_元件11 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role1_Bitmap6();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,43,23);


(lib.role1_元件9 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role1_Bitmap11();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,26,8);


(lib.role1_元件8 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role1_Bitmap9();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,86,25);


(lib.role1_元件6 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role1_Bitmap1();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,229,118);


(lib.role1_元件5 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role1_Bitmap2();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,162,168);


(lib.role1_补间13 = function() {
	this.initialize();

	// 图层 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF9B7F").s().p("AhaBQQgygGgJgcQgIgbAlgfQAnghA+gUQA8gTAyAFQAzAGAIAcQAJAbgnAfQgmAhg+AUQgvAPgpAAIgWgBg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-15.2,-8.1,30.4,16.3);


(lib.role1_补间11 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role1_Bitmap8();
	this.instance.setTransform(-15.2,-8.1);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-15.2,-8.1,30,16);


(lib.role1_补间9 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role1_Bitmap7();
	this.instance.setTransform(-14.3,-7.5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-14.3,-7.5,29,15);


(lib.role1_补间3 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role1_Bitmap10();
	this.instance.setTransform(-57,-24.3);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-57,-24.3,114,49);


(lib.role1_补间1 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role1_eye();
	this.instance.setTransform(-57,-24.3);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-57,-24.3,114,49);


(lib.ani1_哈哈哈哈 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 1
	this.instance = new lib.ani1_我擦擦();
	this.instance.setTransform(72.9,13.9,1,1,0,0,0,72.9,13.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0.531},14).to({alpha:1},15).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,315,36);


(lib.ani1_wenzimc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 5 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A+hKKIAAimICeAAIglpZIomCTIBDlxIGuhXIgWjrIGKh9IAAE3IEagsIAfD+Ik5BMIAAM6IjPCvgAS7KaICiuEIALACIJ3AlIidIBIkfANIgKBhIM8AvIh1EegAYrBnIBtAAIAhhmIiYgQgA2PGkIBBigIKGEQIlsDHgAn2GaIGLjbIA2BAIAnAAIAAhPIF2gOIASl2Il0gQIAAhoIgmACIilDyIAlAnIBIgaIA4BbImnE/IjNjDIB8i9IiwiBIE6p5ID6CKIjLFHIAfAVIB9iiIDCA+IADACIALghIN7giIA2ErIlPgLIAAFgIGFAAIBBDdIxIClIAAjJIgkgIIl7F3gEglUAGUIGTiEIAACwIjbC/gAfPFiIAzpXIq3guIivFBIiEhzIDbqjIETAsIhUDyIOAgpIhlNwgEgkPAB3ICghkIBtCTIhHA7gA2cBxIDVkHIDqCYIldC8gA19o3IgHgTIBKjdICzBhIiJCPg");
	mask.setTransform(-15.9,47.1);

	// 图层 6
	this.instance = new lib.ani1_元件3();
	this.instance.setTransform(-309.2,-50.6,0.999,0.999,25,0,0,34.7,260.6);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:275.5,y:153},14).wait(16));

	// 图层 8
	this.instance_1 = new lib.wenzi();
	this.instance_1.setTransform(-267.4,-216.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(30));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-267.4,-216.4,534.9,369);


(lib.ani1_gezhongmc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// 图层 12
	this.instance = new lib.lg();
	this.instance.setTransform(-114,-480);

	this.instance_1 = new lib.ani1_wenzimc();
	this.instance_1.setTransform(5.1,-238.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

	// gtInfoMc
	this.gtInfoMc = new lib.ani1_gtInfoMc();
	this.gtInfoMc.setTransform(25.3,186.9,1,1,0,0,0,279.1,142.1);

	this.timeline.addTween(cjs.Tween.get(this.gtInfoMc).wait(1));

	// headMc
	this.nickTxt = new cjs.Text("", "bold 45px 'Microsoft YaHei'", "#FFFF00");
	this.nickTxt.name = "nickTxt";
	this.nickTxt.lineHeight = 47;
	this.nickTxt.lineWidth = 439;
	this.nickTxt.setTransform(-141.3,-29.8);

	this.headMc = new lib.ani1_headMc();
	this.headMc.setTransform(-197.6,-16.5,1,1,0,0,0,51.3,51.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.headMc},{t:this.nickTxt}]}).wait(1));

	// 图层 4
	this.instance_2 = new lib.ani1_哈哈哈哈();
	this.instance_2.setTransform(-60.1,309.7,1,1,0,0,0,72.9,13.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// 图层 14
	this.instance_3 = new lib.dx();
	this.instance_3.setTransform(-319.9,305.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

	// 图层 2
	this.instance_4 = new lib.bj();
	this.instance_4.setTransform(-320,-480,1,1.563);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-445.7,-539.4,765.8,1559.5);


(lib.ani1_元件48 = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{s1:1,s1end:11,s2:12,s2end:24,s3:25,s3end:40,s4:41,s4end:58,s5:59,s5end:79,s0:80,s0end:97});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_11 = function() {
		this.stop();
	}
	this.frame_24 = function() {
		this.stop();
	}
	this.frame_40 = function() {
		this.stop();
	}
	this.frame_58 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(11).call(this.frame_11).wait(13).call(this.frame_24).wait(16).call(this.frame_40).wait(18).call(this.frame_58).wait(40));

	// 图层 9
	this.instance = new lib.ani1_元件49();
	this.instance.setTransform(507.5,79,1,1,0,0,0,167.5,79);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(80).to({_off:false},0).to({x:144.5},11).to({x:167.5},6).wait(1));

	// 图层 7
	this.instance_1 = new lib.greetMc6();
	this.instance_1.setTransform(507.5,79,1,1,0,0,0,167.5,79);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(59).to({_off:false},0).to({x:133.5},13).to({x:167.5},7).to({x:-195.5},18).wait(1));

	// 图层 8
	this.instance_2 = new lib.greetMc5();
	this.instance_2.setTransform(507.5,79,1,1,0,0,0,167.5,79);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(41).to({_off:false},0).to({x:144.5},11).to({x:167.5},6).wait(1).to({x:-195.5},20).to({_off:true},1).wait(18));

	// 图层 6
	this.instance_3 = new lib.greetMc4();
	this.instance_3.setTransform(507.5,79,1,1,0,0,0,167.5,79);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(25).to({_off:false},0).to({x:144.5},10).to({x:167.5},5).to({x:-195.5},18).to({_off:true},6).wait(34));

	// 图层 5
	this.instance_4 = new lib.greetMc3();
	this.instance_4.setTransform(507.5,79,1,1,0,0,0,167.5,79);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(12).to({_off:false},0).to({x:144.5},8).to({x:167.5},4).to({x:-217.5},16).to({_off:true},1).wait(57));

	// 图层 2
	this.instance_5 = new lib.ani1_元件49111();
	this.instance_5.setTransform(507.5,79,1,1,0,0,0,167.5,79);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1).to({_off:false},0).to({x:144.5},7,cjs.Ease.get(1)).to({x:167.5},3).to({x:-205.5},13).to({_off:true},1).wait(73));

	// 图层 1
	this.instance_6 = new lib.ani1_元件49();
	this.instance_6.setTransform(167.5,79,1,1,0,0,0,167.5,79);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(1).to({x:-205.5},9,cjs.Ease.get(1)).to({_off:true},1).wait(87));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,335.1,132.1);


(lib.ani1_元件39 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 2
	this.instance = new lib.ani1_元件40();
	this.instance.setTransform(131.3,169.6,1,1,0,0,0,7.4,11);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.86,scaleY:0.86},14).to({scaleX:1,scaleY:1},15).wait(11));

	// 图层 5
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("ACbAfQAFgRALgPQAKgGA6gIQA5gHAZgBIAwgDQAXgDAbAAIAvgBQAWgBAUACIAmAGQAOAaADAcQjVgxjDAxgAoyAfIAGgTIAmgJQAVgDAWgBIAygDQAbgCAXAAIAygCQAZgBA8ACQA7ACAMAFQANAOAHARQjYgojFAog");
	this.shape.setTransform(127.4,131.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("ACZAyIAAgCQgCgjAXggQAJgHA6gHQA6gIAYgBIAwgDQAXgCAbgBIAvgBQAWAAAUACIAmAFQAXAsgHAuIAAACQjhhCi6BCgAo1AyIAAgCQABgbALgaIAmgJQAUgEAXgBIAxgEQAbgCAYAAIAxgBQAagCA7ACQA8ACALAGQAbAeABAkIAAACQjVg9jVA9g");
	this.shape_1.setTransform(127.1,133.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("Ao1AIQABgYALgcIAmgJQAUgEAXgCIAxgDQAbgCAYAAIAxgCQAagBA7ACQA8ACALAFQAbAhABAhQACAggTAhQiogHjbAXQgXgnABgqgACZAIQgCghAXgiQAJgGA6gIQA6gHAYgBIAwgDQAXgDAbAAIAvgBQAWgBAUACIAmAGQAXAugHArQgDAWgKAWQjWgCihAXQgWghgBggg");
	this.shape_2.setTransform(127.1,137.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},12).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape}]},1).to({state:[]},1).wait(23));

	// 图层 3
	this.instance_1 = new lib.aniUI01_Bitmap4();
	this.instance_1.setTransform(78.4,129.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(40));

	// 图层 4
	this.instance_2 = new lib.ani1_元件9();
	this.instance_2.setTransform(130,155.2,1,1,0,0,0,12.9,7.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(40));

	// 图层 6
	this.instance_3 = new lib.ani1_元件41();
	this.instance_3.setTransform(196.5,206.3,1,1,0,0,0,60.4,49.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({rotation:-4.5},19).to({rotation:0},20).wait(1));

	// 图层 1
	this.instance_4 = new lib.ani1_补间20();
	this.instance_4.setTransform(114.7,129.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(40));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,229,259);


(lib.role2_元件32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 2
	this.instance = new lib.role2_元件34();
	this.instance.setTransform(142.3,17.1,1,1,0,0,0,15.2,10.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.88,scaleY:0.88,y:17},19).to({scaleX:1,scaleY:1,y:17.1},20).wait(1));

	// 图层 1
	this.instance_1 = new lib.role2_元件33();
	this.instance_1.setTransform(15.2,10.1,1,1,0,0,0,15.2,10.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleX:0.84,scaleY:0.84},19).to({scaleX:1,scaleY:1},20).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,157.1,27);


(lib.role2_元件26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 3 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("ACeBdQhOgwAjiYIGJAjQgXCwh9ATQgiAFgfAAQhRAAg4gjgAm1BHQhTgrAPibIGdAGQgZDAh2AVQgnAHgkAAQhHAAg4gcg");
	mask.setTransform(50.9,12.9);

	// 图层 1
	this.instance = new lib.role2_元件27();
	this.instance.setTransform(56.9,13,1,1,0,0,0,45.6,12.7);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:49.6,y:12.3},19,cjs.Ease.get(1)).wait(30).to({x:56.9,y:13},20).wait(11));

	// 图层 2
	this.instance_1 = new lib.role2_Bitmap5();

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(80));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,102,26);


(lib.role2_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 2
	this.instance = new lib.role2_元件25();
	this.instance.setTransform(111.1,99.7,1,1,0,0,0,111.3,99.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:4.8,x:104.6},19).wait(30).to({rotation:0,x:111.1},20).wait(11));

	// 图层 5
	this.instance_1 = new lib.role2_元件32();
	this.instance_1.setTransform(97.5,162.2,1,1,0,0,0,78.8,13.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regY:13.6,rotation:2.1,x:94.4,y:162.3},19).wait(30).to({regY:13.5,rotation:0,x:97.5,y:162.2},20).wait(11));

	// 图层 6
	this.instance_2 = new lib.role2_元件26();
	this.instance_2.setTransform(99,156.3,1,1,0,0,0,50.9,25.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({regX:50.8,rotation:2.3,x:95.2,y:156.4},19).wait(30).to({regX:50.9,rotation:0,x:99,y:156.3},20).wait(11));

	// 图层 8
	this.instance_3 = new lib.role2_元件30();
	this.instance_3.setTransform(68.9,209.2,1,1,0,0,0,25.4,46.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({x:64.1},19).wait(1).to({regX:8.3,regY:82.9,x:47,y:245.8},0).to({scaleY:1.02},5).to({scaleY:1},5).to({scaleY:1.02},5).to({scaleY:1},5).to({scaleY:1.02},4).to({scaleY:1},4).wait(1).to({regX:25.4,regY:46.3,x:64.1,y:209.2},0).to({x:68.9},20).wait(11));

	// 图层 7
	this.instance_4 = new lib.role2_元件28();
	this.instance_4.setTransform(39.4,219.1,1,1,0,0,0,19.9,36.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({x:35.1},19).wait(30).to({x:39.4},20).wait(11));

	// 图层 9
	this.instance_5 = new lib.role2_元件31();
	this.instance_5.setTransform(186.7,238.3,1,1,0,0,0,14.8,45.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({x:180.7},19).wait(30).to({x:186.7},20).wait(11));

	// 图层 10
	this.instance_6 = new lib.role2_元件35();
	this.instance_6.setTransform(97.2,182.6,1,1,0,0,0,19.4,11.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({rotation:4.8,x:95.4},19).wait(30).to({rotation:0,x:97.2},20).wait(11));

	// 图层 11
	this.instance_7 = new lib.role2_元件37();
	this.instance_7.setTransform(103.7,161,1,1,0,0,0,4,4);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({x:100},19).wait(30).to({x:103.7},20).wait(11));

	// 图层 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1D5165").s().p("AgdAeQgNgNAAgRQAAgQANgOQANgLAQAAQARAAANALQANAOAAAQQAAARgNANQgNANgRgBQgQABgNgNg");
	this.shape.setTransform(90.8,160.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#1D5165").s().p("AgdAeQgMgNAAgRQAAgQAMgOQAMgLARAAQASAAAMALQAMAOAAAQQAAARgMANQgMANgSgBQgRABgMgNg");
	this.shape_1.setTransform(90.6,160.6);
	this.shape_1._off = true;

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#1D5165").s().p("AgdAeQgNgNAAgRQAAgQANgOQANgLAQAAQASAAAMALQAMAOAAAQQAAARgMANQgMANgSgBQgQABgNgNg");
	this.shape_2.setTransform(90.2,160.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#1D5165").s().p("AgdAeQgMgNgBgRQABgQAMgOQAMgLARAAQARAAANALQANAOAAAQQAAARgNANQgNANgRgBQgRABgMgNg");
	this.shape_3.setTransform(88.9,160.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#1D5165").s().p("AgdAeQgNgNABgRQgBgQANgOQAMgLARAAQARAAANALQANAOAAAQQAAARgNANQgNANgRgBQgRABgMgNg");
	this.shape_4.setTransform(87.6,160.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#1D5165").s().p("AgeAfQgNgNAAgSQAAgRANgOQANgNARAAQASAAANANQAMAOAAARQAAASgMANQgNANgSAAQgRAAgNgNg");
	this.shape_5.setTransform(87.2,160.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#1D5165").s().p("AgeAgQgOgNAAgTQAAgSAOgOQANgNARAAQATAAANANQANAOAAASQAAATgNANQgNAOgTAAQgRAAgNgOg");
	this.shape_6.setTransform(87.2,160.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#1D5165").s().p("AgfAhQgOgNAAgUQAAgSAOgPQANgOASAAQATAAANAOQAOAPAAASQAAAUgOANQgNAPgTAAQgSAAgNgPg");
	this.shape_7.setTransform(87.2,160.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#1D5165").s().p("AggAiQgPgOAAgUQAAgTAPgQQAOgOASABQAUgBANAOQAPAQAAATQAAAUgPAOQgNAPgUAAQgSAAgOgPg");
	this.shape_8.setTransform(87.2,160.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#1D5165").s().p("AghAkQgOgPAAgVQAAgUAOgQQAOgOATAAQAUAAAOAOQAOAQABAUQgBAVgOAPQgOAPgUAAQgTAAgOgPg");
	this.shape_9.setTransform(87.2,160.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#1D5165").s().p("AgeAfQgNgNAAgSQAAgSANgNQANgNARAAQASAAANANQANANAAASQAAASgNANQgNAOgSAAQgRAAgNgOg");
	this.shape_10.setTransform(87.2,160.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#1D5165").s().p("AgfAhQgOgOAAgTQAAgSAOgOQAOgOARAAQATAAANAOQANAOAAASQAAATgNAOQgNAOgTAAQgRAAgOgOg");
	this.shape_11.setTransform(87.2,160.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#1D5165").s().p("AggAiQgOgOAAgUQAAgTAOgQQAOgNASAAQAUAAANANQAOAQAAATQAAAUgOAOQgNAPgUAAQgSAAgOgPg");
	this.shape_12.setTransform(87.2,160.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#1D5165").s().p("AgdAeQgNgNAAgRQAAgQANgOQAMgLARAAQARAAANALQANAOAAAQQAAARgNANQgNANgRgBQgRABgMgNg");
	this.shape_13.setTransform(89.4,160.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2,p:{x:90.2}}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_4,p:{x:87.6}}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2,p:{x:87.5}}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_4,p:{x:88.5}}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_13,p:{x:89.4}}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_13,p:{x:90.3}}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape}]},1).wait(11));
	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},1).wait(5).to({_off:false,x:89.7},0).wait(1).to({x:89.5},0).to({_off:true},1).wait(5).to({_off:false,x:88.3},0).wait(1).to({x:88.1},0).to({_off:true},1).wait(1).to({_off:false,x:87.8},0).to({_off:true},1).wait(32).to({_off:false,x:87.2},0).to({_off:true},1).wait(9).to({_off:false,x:89},0).to({_off:true},1).wait(4).to({_off:false,x:89.9},0).to({_off:true},1).wait(2).to({_off:false,x:90.5},0).to({_off:true},1).wait(1).to({_off:false,x:90.8},0).wait(11));
	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1).to({_off:false},0).wait(1).to({x:90.4},0).to({_off:true},1).wait(1).to({_off:false,x:90.1},0).wait(1).to({x:89.9},0).to({_off:true},1).wait(2).to({_off:false,x:89.3},0).wait(1).to({x:89.1},0).to({_off:true},1).wait(1).to({_off:false,x:88.7},0).wait(1).to({x:88.5},0).to({_off:true},1).wait(2).to({_off:false,x:87.9},0).to({_off:true},1).wait(2).to({_off:false,x:87.4},0).wait(1).to({x:87.2},0).wait(1).to({_off:true},1).wait(9).to({_off:false},0).to({_off:true},1).wait(4).to({_off:false,scaleX:1.14,scaleY:1.21},0).to({_off:true},1).wait(4).to({_off:false,scaleX:1,scaleY:1},0).to({_off:true},1).wait(3).to({_off:false,scaleX:1.14,scaleY:1.21},0).to({_off:true},1).wait(3).to({_off:false,scaleX:1,scaleY:1},0).to({_off:true},1).wait(1).to({_off:false,x:87.4},0).to({_off:true},1).wait(1).to({_off:false,x:87.7},0).wait(1).to({x:87.9},0).wait(1).to({x:88.1},0).wait(1).to({x:88.3},0).to({_off:true},1).wait(1).to({_off:false,x:88.6},0).wait(1).to({x:88.8},0).to({_off:true},1).wait(1).to({_off:false,x:89.2},0).to({_off:true},1).wait(1).to({_off:false,x:89.5},0).wait(1).to({x:89.7},0).to({_off:true},1).wait(1).to({_off:false,x:90.1},0).to({_off:true},1).wait(2).to({_off:false,x:90.6},0).to({_off:true},1).wait(11));

	// 图层 3
	this.instance_8 = new lib.role2_补间17("synched",0);
	this.instance_8.setTransform(110.4,285.2,1,1,0,0,0,0,97.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({regX:0.1,rotation:-3.5},19).wait(30).to({startPosition:0},0).to({regX:0,rotation:0},20).wait(11));

	// 图层 12
	this.instance_9 = new lib.role2_Bitmap12();
	this.instance_9.setTransform(73.8,223.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(80));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.2,0,235,323.9);


(lib.role1_元件7123213213213213 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 2
	this.instance = new lib.role1_元件8();
	this.instance.setTransform(57.9,26.8,1,1,0,0,0,43,12.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:27.5},2).to({y:26.8},2).wait(1));

	// 图层 1
	this.instance_1 = new lib.role1_补间1("synched",0);
	this.instance_1.setTransform(57,24.3);

	this.instance_2 = new lib.role1_补间3("synched",0);
	this.instance_2.setTransform(57,24.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1}]}).to({state:[{t:this.instance_1}]},2).to({state:[{t:this.instance_2}]},2).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({startPosition:0},2).to({_off:true},2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,114,49);


(lib.role1_元件15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 2
	this.instance = new lib.role1_补间9("synched",0);
	this.instance.setTransform(155.3,7.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.88,scaleY:0.88},19).to({scaleX:1,scaleY:1},20).wait(1));

	// 图层 1
	this.instance_1 = new lib.role1_补间11("synched",0);
	this.instance_1.setTransform(15.2,13.6);

	this.instance_2 = new lib.role1_补间13("synched",0);
	this.instance_2.setTransform(15.2,13.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1}]}).to({state:[{t:this.instance_1}]},19).to({state:[{t:this.instance_2}]},20).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleX:0.9,scaleY:0.9},19).to({_off:true,scaleX:1,scaleY:1},20).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,170,21.5);


(lib.role1_元件10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 1
	this.instance = new lib.role1_元件11();
	this.instance.setTransform(21.6,11.4,1,1,0,0,0,21.6,11.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleY:0.89},4).to({scaleY:1},5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,43,23);


(lib.role1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 3
	this.instance = new lib.role1_元件6();
	this.instance.setTransform(122.4,90.8,1,1,0,0,0,122.4,90.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleY:0.94,y:96.5},19).wait(30).to({scaleY:1,y:90.8},20).wait(11));

	// 图层 12
	this.instance_1 = new lib.role1_元件14();
	this.instance_1.setTransform(123.3,156.7,1,1,0,0,0,50.8,14.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(80));

	// 图层 9
	this.instance_2 = new lib.role1_元件13();
	this.instance_2.setTransform(164.3,178.6,1,1,0,0,0,26.5,29.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:175.1},19).to({scaleY:0.94,rotation:-6.5},10).to({regX:26.6,scaleY:1,rotation:6.1,x:164.4},10).to({regX:26.5,rotation:0,x:164.3},10).to({regX:26.6,rotation:6.1,x:164.4},10).to({regX:26.5,rotation:0,x:164.3,y:178.6},10).wait(11));

	// 图层 10
	this.instance_3 = new lib.role1_元件12();
	this.instance_3.setTransform(200.2,196.5,1,1,0,0,0,44.9,31.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({scaleY:0.79,y:200.1},19).wait(30).to({scaleY:1,y:196.5},20).wait(11));

	// 图层 4
	this.instance_4 = new lib.role1_元件7123213213213213();
	this.instance_4.setTransform(126.2,148.9,1,1,0,0,0,58.5,46.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({scaleY:0.91,y:150.3},19).wait(30).to({scaleY:1,y:148.9},20).wait(11));

	// 图层 6
	this.instance_5 = new lib.role1_元件9();
	this.instance_5.setTransform(128.8,148.9,1,1,0,0,0,12.9,7.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({scaleY:0.81,y:149.9},19).wait(30).to({scaleY:1,y:148.9},20).wait(11));

	// 图层 7
	this.instance_6 = new lib.role1_元件10();
	this.instance_6.setTransform(127.5,165.4,1,1,0,0,0,21.6,11.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(80));

	// 图层 8
	this.instance_7 = new lib.role1_元件15();
	this.instance_7.setTransform(122.4,152.6,1,1,0,0,0,84.8,10.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(80));

	// 图层 11
	this.instance_8 = new lib.role1_元件16();
	this.instance_8.setTransform(46.6,173.3,1,1,0,0,0,13.8,4.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({scaleY:0.96,y:176.8},19).wait(30).to({scaleY:1,y:173.3},20).wait(11));

	// 图层 1
	this.instance_9 = new lib.role1_元件5();
	this.instance_9.setTransform(117.3,253.6,1,1,0,0,0,80.8,162.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({scaleY:0.97},19).wait(30).to({scaleY:1},20).wait(11));

	// 图层 13
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFF6C3").s().p("AhYAyQgjgjAAgcQAAgqAFgLQAMgYAtAAQAyAABAApQBHAsAAAoQAAAdg1AQQglALgdAAQgzAAgqgpg");
	this.shape.setTransform(135.9,290.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFF6C3").s().p("AhYAyQgjgjAAgcQAAgqAFgLQAMgYAtAAQAyAABAApQBHAsAAAoQAAAdg1AQQglALgdAAQgzAAgqgpg");
	this.shape_1.setTransform(103.9,290.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFF6C3").s().p("AiEHAQBwnphAlRQCmjvAyELQAOFviqG8QgfAfgZAAQgeAAgWgsg");
	this.shape_2.setTransform(137.5,252.5,1,1,0,0,0,-1.8,4.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFF6C3").s().p("AiEHAQBwnphAlRQCmjvAyELQAOFviqG8QgfAfgZAAQgeAAgWgsg");
	this.shape_3.setTransform(103.9,252.5,1,1,0,0,0,-1.8,4.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(80));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,229,299.7);


(lib.ani1_d1_mc = function() {
	this.initialize();

	// nextBtn
	this.nextBtn = new lib.ani1_元件29();
	this.nextBtn.setTransform(462.4,434,0.601,0.299,0,0,0,204.1,142.2);
	new cjs.ButtonHelper(this.nextBtn, 0, 1, 2, false, new lib.ani1_元件29(), 3);

	// changeBtn
	this.changeBtn = new lib.ani1_元件29();
	this.changeBtn.setTransform(166.4,434,0.601,0.299,0,0,0,204.1,142.2);
	new cjs.ButtonHelper(this.changeBtn, 0, 1, 2, false, new lib.ani1_元件29(), 3);

	// gtmc
	this.gtmc = new lib.ani1_元件48();
	this.gtmc.setTransform(320,248.4,1.91,1.91,0,0,0,167.5,79);

	// 图层 1
	this.instance = new lib.d1();

	this.addChild(this.instance,this.gtmc,this.changeBtn,this.nextBtn);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,640,1500);


(lib.ani1_2 = function() {
	this.initialize();

	// 图层 2
	this.instance = new lib.role2_2();
	this.instance.setTransform(117.1,131.8,1.076,1.076,0,0,0,117.4,142.5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-9.4,-21.5,256,351);


(lib.ani1_1 = function() {
	this.initialize();

	// 图层 3
	this.instance = new lib.role1_1();
	this.instance.setTransform(110.9,124.9,0.967,0.967,0,0,0,114.7,129.2);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,221.4,289.7);


(lib.ani1_2a = function() {
	this.initialize();

	// 图层 2
	this.instance = new lib.s1btn();
	this.instance.setTransform(-124.6,219.1);

	// 图层 3
	this.instance_1 = new lib.ani1_2();
	this.instance_1.setTransform(59.5,139.8,1.783,1.783,0,0,0,117.4,142.6);

	// 图层 1
	this.instance_2 = new lib.t2();
	this.instance_2.setTransform(-124.6,-181.9);

	this.addChild(this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-166.6,-181.9,457,656.1);


(lib.ani1_1a = function() {
	this.initialize();

	// 图层 4
	this.instance = new lib.s2btn();
	this.instance.setTransform(0,220.6);

	// 图层 2
	this.instance_1 = new lib.ani1_1();
	this.instance_1.setTransform(148.5,143.2,1.914,1.914,0,0,0,114.7,129.3);

	// 图层 1
	this.instance_2 = new lib.t1();
	this.instance_2.setTransform(0,-180.9);

	this.addChild(this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-71,-180.9,427,634.6);


(lib.ani1_mc_dh1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{init:11,d2end:15,d0:1,d2:12});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_11 = function() {
		this.stop();
	}
	this.frame_15 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(11).call(this.frame_11).wait(4).call(this.frame_15).wait(1));

	// kardMc
	this.kardMc = new lib.ani1_gezhongmc();
	this.kardMc.setTransform(333.4,480);
	this.kardMc._off = true;

	this.timeline.addTween(cjs.Tween.get(this.kardMc).wait(12).to({_off:false},0).wait(4));

	// 图层 5
	this.instance = new lib.ani1_元件39();
	this.instance.setTransform(335.8,752.2,1.799,1.799,0,0,0,114.7,129.2);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(11).to({_off:false},0).to({_off:true},1).wait(4));

	// 图层 10
	this.instance_1 = new lib.role_001();
	this.instance_1.setTransform(335.9,1200.3,1,1,0,0,0,206.5,232.5);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({_off:false},0).to({y:740.8},6).to({y:752.2},3).to({_off:true},1).wait(5));

	// greetMc
	this.greetMc = new lib.ani1_d1_mc();
	this.greetMc.setTransform(332.8,-261.6,1,1,0,0,0,320,480);
	this.greetMc.alpha = 0;
	this.greetMc._off = true;

	this.timeline.addTween(cjs.Tween.get(this.greetMc).wait(1).to({_off:false},0).to({y:504.6,alpha:1},6).to({y:480},4).to({_off:true},1).wait(4));

	// 图层 9
	this.btn0 = new lib.ani1_1a();
	this.btn0.setTransform(116.7,741.5,1,1,0,0,0,103.6,218.6);

	this.btn1 = new lib.ani1_2a();
	this.btn1.setTransform(565.3,742.1,1,1,0,0,0,107.5,217.9);

	this.instance_2 = new lib.pic_001();
	this.instance_2.setTransform(326.8,674.6,1,1,0,0,0,442,332.5);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.btn1},{t:this.btn0}]}).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},9).to({state:[]},1).wait(5));
	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1).to({_off:false},0).to({y:1292.6},9).to({_off:true},1).wait(5));

	// 图层 1
	this.instance_3 = new lib.lg();
	this.instance_3.setTransform(214,0.4);

	this.instance_4 = new lib.ani1_wenzimc();
	this.instance_4.setTransform(333.1,242);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_4},{t:this.instance_3}]}).to({state:[]},11).wait(5));

	// 图层 6
	this.instance_5 = new lib.ani1_bjmc();
	this.instance_5.setTransform(488.1,755.4,1,1,0,0,0,155,275.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({_off:true},11).wait(5));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-117.7,-59,866.9,1559.1);


// stage content:



(lib.aniUI01 = function() {
	this.initialize();

	// 图层 1
	this.ui = new lib.ani1_mc_dh1();
	this.ui.setTransform(265,450.9,1,1,0,0,0,278.1,450.9);

	this.addChild(this.ui);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(189.2,691,866.9,1559.1);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;