(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 640,
	height: 1500,
	fps: 30,
	color: "#000000",
	manifest: [
		{src:"images/bai.png", id:"bai"},
		{src:"images/bj.jpg", id:"bj"},
		{src:"images/bu.png", id:"bu"},
		{src:"images/duquzhong01.png", id:"duquzhong01"},
		{src:"images/dx.png", id:"dx"},
		{src:"images/hao.png", id:"hao"},
		{src:"images/hao2.png", id:"hao2"},
		{src:"images/headimg.jpg", id:"headimg"},
		{src:"images/jiu.png", id:"jiu"},
		{src:"images/jiuyibai.png", id:"jiuyibai"},
		{src:"images/lg.jpg", id:"lg"},
		{src:"images/num1.png", id:"num1"},
		{src:"images/num2.png", id:"num2"},
		{src:"images/num3.png", id:"num3"},
		{src:"images/role21_Bitmap1.png", id:"role21_Bitmap1"},
		{src:"images/role21_Bitmap2.png", id:"role21_Bitmap2"},
		{src:"images/role21_Bitmap3.png", id:"role21_Bitmap3"},
		{src:"images/role21_Bitmap4.png", id:"role21_Bitmap4"},
		{src:"images/role21_Bitmap5.png", id:"role21_Bitmap5"},
		{src:"images/role2_Bitmap1.png", id:"role2_Bitmap1"},
		{src:"images/role2_Bitmap10.png", id:"role2_Bitmap10"},
		{src:"images/role2_Bitmap11.png", id:"role2_Bitmap11"},
		{src:"images/role2_Bitmap12.png", id:"role2_Bitmap12"},
		{src:"images/role2_Bitmap2.png", id:"role2_Bitmap2"},
		{src:"images/role2_Bitmap3.png", id:"role2_Bitmap3"},
		{src:"images/role2_Bitmap4.png", id:"role2_Bitmap4"},
		{src:"images/role2_Bitmap5.png", id:"role2_Bitmap5"},
		{src:"images/role2_Bitmap6.png", id:"role2_Bitmap6"},
		{src:"images/role2_Bitmap7.png", id:"role2_Bitmap7"},
		{src:"images/role2_Bitmap8.png", id:"role2_Bitmap8"},
		{src:"images/role2_Bitmap9.png", id:"role2_Bitmap9"},
		{src:"images/wenzi.png", id:"wenzi"},
		{src:"images/woyeyao.png", id:"woyeyao"},
		{src:"images/x1.png", id:"x1"},
		{src:"images/x2.png", id:"x2"},
		{src:"images/x3.png", id:"x3"},
		{src:"images/yi.png", id:"yi"},
		{src:"sounds/sound01.mp3", id:"sound01"}
	]
};



// symbols:



(lib.bai = function() {
	this.initialize(img.bai);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,193,205);


(lib.bj = function() {
	this.initialize(img.bj);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,640,960);


(lib.bu = function() {
	this.initialize(img.bu);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,214,205);


(lib.duquzhong01 = function() {
	this.initialize(img.duquzhong01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,315,36);


(lib.dx = function() {
	this.initialize(img.dx);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,640,320);


(lib.hao = function() {
	this.initialize(img.hao);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,225,198);


(lib.hao2 = function() {
	this.initialize(img.hao2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,230,185);


(lib.headimg = function() {
	this.initialize(img.headimg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,50,50);


(lib.jiu = function() {
	this.initialize(img.jiu);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,250,195);


(lib.jiuyibai = function() {
	this.initialize(img.jiuyibai);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,510,293);


(lib.lg = function() {
	this.initialize(img.lg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,225,112);


(lib.num1 = function() {
	this.initialize(img.num1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,17,143);


(lib.num2 = function() {
	this.initialize(img.num2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,101,143);


(lib.num3 = function() {
	this.initialize(img.num3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,101,143);


(lib.role21_Bitmap1 = function() {
	this.initialize(img.role21_Bitmap1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,784,674);


(lib.role21_Bitmap2 = function() {
	this.initialize(img.role21_Bitmap2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,838,646);


(lib.role21_Bitmap3 = function() {
	this.initialize(img.role21_Bitmap3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,731,663);


(lib.role21_Bitmap4 = function() {
	this.initialize(img.role21_Bitmap4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,677,643);


(lib.role21_Bitmap5 = function() {
	this.initialize(img.role21_Bitmap5);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,750,1182);


(lib.role2_Bitmap1 = function() {
	this.initialize(img.role2_Bitmap1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,235,129);


(lib.role2_Bitmap10 = function() {
	this.initialize(img.role2_Bitmap10);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,8,8);


(lib.role2_Bitmap11 = function() {
	this.initialize(img.role2_Bitmap11);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,158,194);


(lib.role2_Bitmap12 = function() {
	this.initialize(img.role2_Bitmap12);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,61,100);


(lib.role2_Bitmap2 = function() {
	this.initialize(img.role2_Bitmap2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,30,20);


(lib.role2_Bitmap3 = function() {
	this.initialize(img.role2_Bitmap3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,30,20);


(lib.role2_Bitmap4 = function() {
	this.initialize(img.role2_Bitmap4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,91,25);


(lib.role2_Bitmap5 = function() {
	this.initialize(img.role2_Bitmap5);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,102,26);


(lib.role2_Bitmap6 = function() {
	this.initialize(img.role2_Bitmap6);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,51,93);


(lib.role2_Bitmap7 = function() {
	this.initialize(img.role2_Bitmap7);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,40,73);


(lib.role2_Bitmap8 = function() {
	this.initialize(img.role2_Bitmap8);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,30,103);


(lib.role2_Bitmap9 = function() {
	this.initialize(img.role2_Bitmap9);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,39,23);


(lib.wenzi = function() {
	this.initialize(img.wenzi);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,535,369);


(lib.woyeyao = function() {
	this.initialize(img.woyeyao);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,299,165);


(lib.x1 = function() {
	this.initialize(img.x1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,496,625);


(lib.x2 = function() {
	this.initialize(img.x2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,655,625);


(lib.x3 = function() {
	this.initialize(img.x3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,517,625);


(lib.yi = function() {
	this.initialize(img.yi);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,207,60);


(lib.btn001 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.woyeyao();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,299,165);


(lib.ani2_yj3 = function() {
	this.initialize();

	// 图层 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0.424)","rgba(255,255,255,0)"],[0,1],-14.2,0,14.3,0).s().p("EgD3AouQgUAAAAhCMAAAhPXQAAhCAUAAIHvAAQAUAAAABCMAAABPXQAABCgUAAg");
	this.shape.setTransform(26.9,260.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(255,255,255,0.424)","rgba(255,255,255,0)"],[0,1],-7.4,0,7.5,0).s().p("EgCBAouQgKAAAAhCMAAAhPXQAAhCAKAAIEDAAQAKAAAABCMAAABPXQAABCgKAAg");
	this.shape_1.setTransform(55.4,260.7);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,69.5,521.4);


(lib.ani2_faguang = function() {
	this.initialize();

	// 图层 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EgynB9AMAAAj5/MBlPAAAMAAAD5/g");
	this.shape.setTransform(324,800);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,648,1600);


(lib.ani2_元件56 = function() {
	this.initialize();

	// 图层 1
	this.text = new cjs.Text("我要微信红包", "20px 'Microsoft YaHei'");
	this.text.lineHeight = 22;
	this.text.setTransform(36.3,-75.2,2.416,2.416);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A3oD9QpykSAAmGQAAmGJykVQJzkTN1AAQN2AAJyETQJzEVAAGGQAAGGpzESQpyEUt2AAQj0AAuGM5QBXuFnFjIg");
	this.shape.setTransform(180.5,3.5);

	this.addChild(this.shape,this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-33.4,-131.9,427.9,271);


(lib.ani2_元件13b = function() {
	this.initialize();

	// 图层 2
	this.instance = new lib.num3();
	this.instance.setTransform(11.4,66);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(11.4,66,101,143.2);


(lib.ani2_元件12a = function() {
	this.initialize();

	// 图层 2
	this.instance = new lib.num2();
	this.instance.setTransform(11.4,66);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(11.4,66,101,143.2);


(lib.ani2_元件11a = function() {
	this.initialize();

	// 图层 2
	this.instance = new lib.num1();
	this.instance.setTransform(39.5,66);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(39.5,66,17.4,143.2);


(lib.ani2_ani1_我擦擦 = function() {
	this.initialize();

	// 图层 3
	this.instance = new lib.duquzhong01();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-5.7,0,320.8,36);


(lib.ani1_headMc = function() {
	this.initialize();

}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,102.5,102.5);


(lib.ani1_gtInfoMc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(7));

	// 01
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EgksAKgIAAgTIkcAAIAAATIhKAAIAAiLIGwAAIAACLgEgpIAJfIEcAAIAAgcIkcAAgAFpKfIAAkGQhHBXhoBKQgSgZgmgwQCthxBCiQIjYAAIAAhLIH2AAIAABLIjDAAQgRAtgZAqIAbAAIAABBIA2g0QBJBCBpBgIhAA/QhGhRhihaIAAEVgAv7JLIA2gvIAAiKIgzAAIAAhGIB7AAIAADRQArAwBdAAQDDAABRgFIgZBJIiKABQiWAAgagEQgagFgagKQgbgJgagYIhABAgA4/JLIA3gvIAAiKIgyAAIAAhGIB6AAIAADRQAqAwBeAAQDDAABQgFIgYBJIiKABQiWAAgZgEQgbgFgagKQgbgJgagYIg/BAgAmIKdIAAj/QgRAggSAdQgHgsgOg2QA1hbAqibIBDAPQgSA+gUA4IAAGVgAjMKaQgDgZgKgqQAcADAnAAQAaACAAgfIAAgWIiSAAIAAg4IFLAAIAAA4IhxAAIAAAqQAABEg5ADQgZADgpAAIgdgBgA/1KZQgEgggIglQA1AFASAAQAdAAABgbIjIAAIAAgvIDIAAIAAgaIjpAAIAAgxIDpAAIAAgZIjFAAIAAgvIDFAAIAAgaIi2AAIAAhyIC2AAIAAgaIjlAAIAAgwIDlAAIAAglIBLAAIAAAlIDkAAIAAAwIjkAAIAAAaIC2AAIAAByIi2AAIAAAaIC+AAIAABIIAqAAIAAAxIgqAAIAABiIhKAAIAAgZIh0AAIAAAQQAAAZgKASQgKAQgTAIQgTAIgJAAIhhAAgA9RIPIB0AAIAAgaIh0AAgA9RHEIB0AAIAAgZIh0AAgA9RE3IBuAAIAAgbIhuAAgEggLAE3IBvAAIAAgbIhvAAgANAKTQgIgogLgsQAzAFAjAAQAhAAAKgNQAJgOAAgUIAAi9QBCgtBXhAIl3AAIAAhMIH2AAIAABLIjBCRIAACwQAAA0gbAaQgbAZg0ABgAq6JFIAAg8IirAAIAAhBICrAAIAAg0IicAAIAAg7QAZgrAYg0Ig1AAIAAhBIBQAAIAUg5IBQAMQgJAWgKAXIDBAAIAABBIjfAAIgsBaIBJAAIAAhHIBJAAIAABHIB1AAIAABAIh1AAIAAA0ICGAAIAABBIiGAAIAAA8gAz9JFIAAg8IirAAIAAhBICrAAIAAg0IicAAIAAg7QAZgrAXg0Ig0AAIAAhBIBPAAIAVg5IBPAMIgSAtIDBAAIAABBIjeAAQgVArgYAvIBJAAIAAhHIBIAAIAABHIB2AAIAABAIh2AAIAAA0ICHAAIAABBIiHAAIAAA8gEgrHAH9IAAgyIB8AAIgPgfIAkgGIhVAAIAAh2IGiAAIAAB2IhUAAIAnAHIgbAeICHAAIAAAygEgnxAHLIBpAAIAaglIiZAAQALARALAUgEgpCAF3IEPAAIAAgYIkPAAgAAYHnIAAgfIkEAAIAAAfIhHAAIAAhWIGSAAIAABWgAkAF8IAAh9IExAAIAAB9gAi6FLICmAAIAAgcIimAAgAvqCvIA6gkQAqA1AgAwIhAArQghg5gjgzgA4uCvIA8gkQApA1AgAwIhAArQghg5gkgzgEgqfAEXIAAguIC/AAIAAgZIjcAAIAAgzIDcAAIAAgcIBNAAIAAAcIDbAAIAAAzIjbAAIAAAZIC8AAIAAAugAkiDoIAAg3ICUAAIgOghIBQgOIASAvICVAAIAAA3gEApbgB6IAfiUIBOAAIgtCUgAMFh7IAAjFQgWAYgWAVQgLg3gKgiQBBg/AihCIhbAAIAAhIIBXAAQgXglgYggIBAghQAfAkAXAkIg3AeIBHAAIAAA9QgWAtgXAoIAAAPIAXgOIAhAxIAAgVIFLAAIAAEIIhIAAIAAgZIi6AAIAAAZIhJAAIAAjFIgeASIgag0IAADqgAROjNIA6AAIAAgoIg6AAgAPOjNIA6AAIAAgoIg6AAgAROkoIA6AAIAAgoIg6AAgAPOkoIA6AAIAAgoIg6AAgACbh7IAAoGIHuAAIAAIFIhFAAIAAgWIlkAAIAAAXgADgjMIFkAAIAAl7IlkAAgEgnhgB7IAAiAIjjAAIAAhDIDjAAIAAg9IirAAIAAhCICrAAIAAg8IjQAAIAAhCICAAAQgfgkgVgWIA7gqIBKBKIgmAaIBmAAQAkgtAlg1IBRAkIg5A+IB8AAIAABCIjNAAIAAA8ICpAAIAABCIipAAIAAA9IDhAAIAABDIjhAAIAACAgAtZjAQg5AdhEAXQgTghgYggQCigoBlhOIgKgWQhaA/hxAgIgmg5QCCgbBVg0QgGgJgHgJQhJAjhZAWQgSgdgTgbQBvgTBOgmIhbAAIAAg8IE+AAIAAA8Ih3AAIgjAXQAXAdAQAcQBcgsA7gkIAsA9IhXAoQAmBfBTAwQgjAggaAcQhGg2gvh7IgYAMQAOApABAqQgBAjgHAWQgHAWgQAOQgRAOgWADQgUAEhTAAQgHgmgKgegAtRjEQAiADAWAAQAyAAAAgxQAAgJgDgMQgtAlg6AegA99h8IAAh0IkDAAIAAhFIBNAAIAAiHQgOAQgRAPQgVgggcgmQBThEAthzIBVANQgKAYgLAWIFGAAIAABGIiwAAIAABIICbAAIAABGIibAAIAABWIDAAAIAABFIjAAAIAAB0gA/nk1IBqAAIAAhWIhqAAgEggggHRICjAAIAAhIIhtAAQgYAmgeAigAUUiUQAchgAahyQArASAbAIIg0DPQglgNgjgKgAWeh+IAAkkIBmAAIAAgtIh3AAIAAg5IGXAAIAAA5IhxAAIAAAtIBhAAIAADaQAAAfgPASQgNAQgYADQgXADhKABQgHgcgJgZIg4gjQAZgaAPgjIgbAZIgTgYQgQAtghAxQgGgJgXgQIAABRgAZ0i5QAkACAXAAQAgAAAAgeIAAghIgVAVIgbgjQgRAogaAjgAXgj5QAhgyADhDIgkAAgAaulAIAlAmIAAhUIggAAQgBAXgEAXgAZAlMIAlAnQAMghADgoIgyAAQAAAWgCAMgAZCmiIAzAAIAAgtIgzAAgAmoh/IAAoDIHxAAIAAICIhKAAIAAgTIlaAAIAAAUgAlbjVIFaAAIAAlqIlaAAgAdPiNIAAhAIDnAAIAAghIi8AAIAAg9IC8AAIAAggIiVAAIAAhsIhFAAIAAiGIBqAAQgggZgdgUIArgwQA3AmAjAcIgZAbIBCAAIAAhcIBJAAIAABcIA8AAIgVgWQAvgiApglIAwAsQgfAagfAXIBpAAIAACGIhHAAIAABsIiTAAIAAAgIC7AAIAAA9Ii7AAIAAAhIDqAAIAABAgAfrmFIDeAAIAAghIjeAAgAeongIFmAAIAAgeIlmAAgA4riPIAAhGIDNAAIAAhCIijAAIAAhGICjAAIAAg3IhpAAIAAgrQgkAZgqAZQgPgWghgqQCwheA+hrIBgAAIgPAUQBGBlCcBJQgcAkgVAcQgpgVgkgYIAAAtIhqAAIAAA3IClAAIAABGIilAAIAABCIDPAAIAABGgA2knaIDgAAQhDgzgtg7QgtA5hDA1gAGSkJQgvAnhbARQgMgagQgeQBZgNAZgUQAbgVACgiIA+AAQgBAagKAVQBHAWBKAaIgfAzgAjwkmQAaACAjAAQArAAABgtIAAhaQg5BThoBQQgZgkgWgYQBig5A9hEIiNAAIAAhBIC+AAIAAgwIBHAAIAAAwIAoAAIAABBIgoAAIAAB1QABAygXAZQgWAagrADQgqADggAAQgIgngHgegAHnkjIAAhPIisAAIAABPIg6AAIAAiBIEiAAIAACBgAUHnOIAtg1QAqAfAtAnIgyA7IhShMgAOcmfIAAiOIEeAAIAACOgAPlnXICLAAIAAgeIiLAAgAEUm6IAAh4ID8AAIAAB4gAFMnoICMAAIAAgaIiMAAgAo9neIAAhLIloAAIAABLIhLAAIAAiKIDVAAQgJgXgHgPIBegMIAPAyIDNAAIAACKgAaFoOIAAgiIhYAAIAAAiIhHAAIAAgiIhZAAIAAgVIgrAuQgkgkgrgmIAtgyQAiAZArAkIAAgTIBZAAIAAguIBHAAIAAAuIBYAAIAAgvIBHAAIAAAvIBZAAIAAA5IhZAAIAAAigAOIpHIAAg6IFLAAIAAA6g");
	this.shape.setTransform(260.8,94.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("A5YJoQBhhhABjPIAAhZIgtAAIAAhCIEMAAIAABAIglBnIBJAAQAAB2gFBvQgCBghWAFQghACgyAAQgDgcgLgxQAlADAcAAQAwAAAAgmQAGhNAAhOIhLAAIAAhBIAmhlIhPAAIgBBaQgBDthpB6QgXgYgogggAx0JRQBFhhABjNIg+AAIAAhIIBAAAIABhbIBHAAIgBBbIB8AAIgHFdQgCAngPAUQgPAUgUAFQgWAFhBAAIgShSQAhACAXAAQANAAAIgFQAGgGACgKQABgKAChJQAChJAChtIg2AAQgDEDhfB5QgTgmgYgogAeXJ6Qh+APiVAOIgMhGICOgKIAAg8Ih6AAIAAitIB6AAIAAgnIhoAAIAAiiIEXAAIAACiIhpAAIAAAnIB8AAIAACtIgbAAQAbA2AcBEIg/AZgAdMJBIAwgFIgNgaIA9gXIhgAAgAdMHPIA5AAIAAg2Ig5AAgAbPHPIA3AAIAAg2Ig3AAgAbjD8ICNAAIAAgrIiNAAgAJ8J6Qh+APiVAOIgMhGICOgKIAAg8Ih6AAIAAitIB6AAIAAgnIhoAAIAAiiIEYAAIAACiIhqAAIAAAnIB8AAIAACtIgbAAQAbA2AcBEIg/AZgAIxJBIAwgFIgNgaIA+gXIhhAAgAIxHPIA5AAIAAg2Ig5AAgAG0HPIA3AAIAAg2Ig3AAgAHHD8ICOAAIAAgrIiOAAgAlWJQQAqADAVAAQAdABAAgfIAAhBIidAAIAAgxQgVAMgVAKQgeg6gLgQQCbgzBahhIBcAAIgPAPQBbBPCGAnQgYAngOAmIgrgUIAAA7IiWAAIAABUQAABNg5ACQg3ACgqAAQgEgbgKgugAiuF3IAAA8ICIAAQhogzhGhCQg6A5hpA8IB9AAIAAg8gEggaAJmIirAAIAAiDQgOgQgPgNIAACdIg8AAIAAgkIgeAAIAAAvIg9AAIAAnAICXAAIAAEBQAmgiAcgpIgfAAIAAjTIErAAIAADTIjCAAQgIAPgJAOIDmAAQgBBTgEBtQAABQg7AEQgUACg8ABIgJgygEgigAHNIAXAAIAABlICpAAIAAAoQAZAAACghQAEhAABhAIhJAAIgIARIBJA5IgjAqIhAg4QgWAggfAaQgNgRgbgZQAqgiAZgqIhLAAgEgk8AIAIAeAAIAAkTIgeAAgEgh9AEtICmAAIAAgcIimAAgEgh9ADkICmAAIAAgcIimAAgAXaKXQgEgbgLguIA5ABQAWAAAGgOQAGgPADhbIhiAAIAOjCIBcAAIAAhAIhoAAIAAhBICtAAIAADCIhhAAIgGBBIBgAAQgCCFgEAnQgEAogKARQgMARgUAGQgPAEg7AAIgXAAgAC/KXQgEgbgMguIA7ABQAVAAAHgOQAFgPADhbIhiAAIAOjCIBcAAIAAhAIhoAAIAAhBICsAAIAADCIhgAAIgGBBIBgAAQgCCFgEAnQgDAogMARQgLARgTAGQgQAEg7AAIgXAAgAPHJFQAtAEAeAAQAfAAAAghIAAhtIjUAAIAAhMQAogyAigzIhrAAIAAhIICVAAQATgiAPgiIBaAJIgdA7IEYAAIAABIIlDAAQggAygoA3IB0AAIAAhOIBTAAIAABOICyAAIAABIIiyAAIAAB+QAAApgSAWQgSAWgfAFQggAEhHAAQgGgegNg0gA8EJbQA1glAigzIhJg+QAQg+APhmIgnAAIAAhBIAyAAIAMhhIBGAHIgOBaIBgAAQgDCrgpBlIAoAgIguA/IgdgcQgpA7g3ApQgTgcgagggA6uGuIAhAYQAchDAGhiIgoAAQgOBWgNA3gAtJKRIAAnjIDdAAIAAHgIhJAAIAAgtIhLAAIAAAwgAsAIZIBLAAIAAkjIhLAAgAhyIrIAwgwQBFAyAvAmIgyA6Qg1gwg9gygAnjJRQBBgtAvgsIA1AwQg5A0g9AtQgWgbgZgdgAMtJIQA/g5BDhIQA+AyADABQhEBIhGBAQgagfgfgbgASgIIIAyg3ICGBrIg4A9Qg7g4hFg5gAiIETIAAgmIiaAAIAAAmIhLAAIAAgmIhtAAIAAhDIBtAAIAAgpIBLAAIAAApICaAAIAAgpIBMAAIAAApIByAAIAABDIhyAAIAAAmgAjmiUIALgRIhSAAIAAAsIhCAAIAAgsIhuAAIAAgoIBuAAIAAgTIhYAAIAAhbIBYAAIAAgUIg9AAIAAgzIgyAAIAAgoIAyAAIAAgQIA2AAIAAAQIBQAAIAAgQIA2AAIAAAQIAuAAIAAAoIguAAIAAAzIg9AAIAAAUIBcAAIAABbIhcAAIAAATIBbAAIAAAZQAegwAAhlIAAhoIDNAAIAADvQAABBg7ADQgmABggAAIgLg9IA7ACQATAAAAgUIAAgTIhWAAQgIAyglA4QgfgSgfgNgAktkBIAnAAIAAgZIgnAAgAmSkBIAjAAIAAgZIgjAAgAh0kOIBPAAIAAgfIhOAAIgBAfgAhzlcIBOAAIAAgeIhOAAgAl2lvIBQAAIAAgTIhQAAgEAkcgB8IAfiUIBNAAIgsCUgAPXi1QBohNAAiXIAEiaIhDAAIAAhFIE6AAIgKF9QAAAxgOAZQgQAagcAFQgbAGhZABQgHglgMgtQAvADAZAAQAXAAALgJQAJgLACgOQADgQAEknIhaAAQgGDEgIA1QgIA1gcA0QgcA0guAhQgXgYgnghgA71iXQAchYAah5QAsASAaAIIg0DOIhIgXgAwliBIAAiuQgaA1gZAlQgKgkgSgzQAtg2AfhTIhGAAIAAhGIBJAAIAAg+IhBAHQgEgwgDgSQBugKBUgMIANBBIhEAJIAABFIA6AAQAvhQAQhKIBHAKQgIAdgIAaIDSAAIAAA/IgWBhIhEgOIAThRIimAAQgVAzgdArIglguIAAAuIg+AAIAAAdIBHAsIghA7QgSgRgUgOIAADPgEgj3gCBQgIgmgMgiQArACAiAAQAmAAgBghIAAghIjuAAIAAhEIDuAAIAAgOIBKgvIjIAAIAAhEIEzAAIAABDIhcA+IDLAAIAABEIjUAAIAAA4QAAAmgVAUQgVAWgsAAIhYAAgAtoiGQgGgngHggQAaADAZAAQAaAAAAgYIAAkMIBJAAIAAEbQgBAjgNASQgMATgaACQgUADgqAAIgXAAgA59iNIAAg6IGWAAIAAA6gAaKiRIAAnwIFNAAIAABBIkJAAIAAFvIEQAAIAABAgAFviRIAAnwIFNAAIAABBIkJAAIAAFvIEQAAIAABAgANhjtQAQgQAAgnIAAiTIg5AFIgEhHIA9gGIAAiVIBKAAIAACOIBTgHIAEBGIhXAIIAACPIBKg1QABAxAEAgQhnBNgPAVgAXWi6IAAmyICWAAIAAGkIg7AAIAAgkIgbAAIAAAygAYWkyIAbAAIAAj0IgbAAgAC7i6IAAmyICWAAIAAGkIg7AAIAAgkIgcAAIAAAygAD6kyIAcAAIAAj0IgcAAgArNmTIA/gRQAUA4AmCCIhFAZQgbhvgZhTgAu/j0QAohcAYhVIBBASQgZBfgoBeQgdgPgjgPgA5OjkIAAjVIgSAKQgTgegXgeQBKggA0goIhTAAIAAg4ICHAAIAAgvIBHAAIAAAvICUAAIAAA4IhoAAQA3AnBQAVQgWAngMAeIgZgNIAADbgA4HkcICnAAIAAgiIinAAgA4HlwICnAAIAAgiIinAAgA0snJQg7gjgqgrIAAA9IhHAAIAAg+QgpArg1AkIEKAAIAAAAgAbcj+IAAg7IBaAAIAAgzIhKAAIAAg5IBKAAIAAg0IhSAAIAAg6IDnAAIAAA6IhUAAIAAA0IBLAAIAAA5IhLAAIAAAzIBcAAIAAA7gAHBj+IAAg7IBaAAIAAgzIhKAAIAAg5IBKAAIAAg0IhSAAIAAg6IDnAAIAAA6IhUAAIAAA0IBLAAIAAA5IhLAAIAAAzIBcAAIAAA7gA8CnQIAtg1QAqAfAuAmIgyA8QgRgShCg6gA/MmxIAAhEIlmAAIAABEIhMAAIAAiGIBaAAIgvg9IA6gnQAgAlAiAuIgZARIBcAAQgXgsgTgfIBCgdQAWAhAeA1IglASIBCAAIA/hdIBKAoIgsA1IBOAAIAACGgAibnFIAAgcICNAAIAAAcgAmdnFIAAgcICNAAIAAAcgAj4nLIAAhVIieAAIAAAuIhAAAIAAhUIDeAAIAAgVIjDAAIAAgqIHIAAIAAAqIjBAAIAAAVIDcAAIAABUIg+AAIAAguIieAAIAABVgAibnyIAAgdIB4AAIAAAdgAmInyIAAgdIB4AAIAAAdgA7xplIAtgvQA/AsAcAXIgzA4Qgogmgtgmg");
	this.shape_1.setTransform(257.2,94.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AGyJiQg6AxijAKQgOghgRggQCAgGAzgRQAsgQAGgsIBHAAQgEAXgJATQBvAVBrAaIghA8QhrgfhxgdgAREHHQgxB+idBVQgVgcgpgqQCvhQAdhsIjGAAIAAhMIDXAAQAHgtACg4IjCAAIAAhKIHZAAIAABKIjHAAIgGBlIDpAAIAABMIjSAAQA9CKCZAtQgWAZgpA0QiQg8hCiZgAxvJUQCygpAig+IjNAAIAAg9IDeAAQADgYAAgfIi6AAIAAg8IC6AAIAAg4IBPAAIAAA4IC6AAIAAA8Ii6AAIgDA3IDoAAIAAA9IjFAAQA+BDCKAbIg4BMQiSgohChsQg1BkilA1QgQgWgpgygEgh6AInQg8Bhi5ATQgIgZgUgtQCXgPAxg7Ii7AAIAAg7IDVAAQAEgPACgQIBPAAQgCAQgEAPIDmAAIAAA7IjEAAQA8A8CRAJQgNATgYA5QiigQhIhlgAhiKaIAAgSIjdAAIAAASIhHAAIAAh/Ig2AVQgOgbgVgfQCJgjBshTIBSAAIgNANQBiBKCCAaIgjA/Ig3gTIAAB9gAk/JUIDdAAIAAgsIjdAAgAkwH0IC7AAQg2gdglgjQgjAhg9AfgA6TKaIAAiYQgnAggsAeQgJgkgOguQBUgyA/hBIiQAAIAAhDIDIAAQAUgbAQgdIBNARIgYAnID8AAIAABDIkvAAQgUAagYAYIEjAAIAADtIhQAAIAAggIjgAAIAAAggA5FI4IDgAAIAAhIIjgAAgAeJKaIAAgdIkIAAIAAmJIBIAAIAAFCIA6AAIAAmzIBLAAIAAGzIA7AAIAAlCIBIAAIAAGmgAYIKZIAAkFQgUAhgWAgQgIgqgQg5QBBhiAriTIBJARQgRA+gaA8IAAGRgAIhI8IAAhGIjNAAIAABGIhCAAIAAhKQggAVgiASQgRgcgSgaQBCgZAsgdIhhAAIAAgzICFAAIAAgYIhfAAIAAgqIBfAAIAAgZIg3AAIAAgrIA3AAIAAgWIBEAAIAAAWIBuAAIAAgWIBFAAIAAAWIA1AAIAAArIg1AAIAAAZIBgAAIAAAqIhgAAIAAAYICGAAIAAAzIhhAAQAzAiA5AUQgOATgVAlQghgOgfgWIAABFgAFJHHIDfAAIgcgaIimAAQgOAOgPAMgAGDF6IBuAAIAAgYIhuAAgAGDE4IBuAAIAAgZIhuAAgAisFwIAhgoQB8A0AzAYIggA3IiwhbgAnHGRQBbgeBTguIApApQhRAwhhArIglg4gEgmFAGrIAAg8IDjAAIAAgfIi3AAIAAg8IC3AAIAAgfIjXAAIAAg7IB6AAQgLgbgNgUIBOgQIAlA/IBUAAQATgbAYgkIBSAQIgqAvICFAAIAAA7IjbAAIAAAfIC9AAIAAA8Ii9AAIAAAfIDlAAIAAA8gAgjFrIAAgsIlbAAIAAAsIhLAAIAAhgIDVAAIgPggIBNgIIASAoIDKAAIAABggA2ZEeIAAgnIibAAIAAAnIhMAAIAAgnIh4AAIAAhEIB4AAIAAgyIBMAAIAAAyICbAAIAAgzIBNAAIAAAzIBsAAIAABEIhsAAIAAAngAsYEcIAAgvIiPAAIAAAvIhJAAIAAgvIhuAAIAAg+IBuAAIAAgtIBJAAIAAAtICPAAIAAgtIBJAAIAAAtIBvAAIAAA+IhvAAIAAAvgAJ9EOIAAg5ImGAAIAAA5Ig7AAIAAhtIDWAAIgNgeIBWgGIAOAkIDPAAIAABtgAiND3IAAgfIiKAAIAAAfIhIAAIAAgfIh9AAIAAg5IB9AAIAAgjIBIAAIAAAjICKAAIAAgjIBIAAIAAAjIB8AAIAAA5Ih8AAIAAAfgAN0jAQAWgWAAgrIAAh4IhMAAIAAhHIBMAAIAAjcIBLAAIAADcIF5AAIAABHIjQAAQBBBwCZAtQgZAfgeAsQithIhBigIheAAIAACYICNgvIAABIQiiAygiAcgEAkfgB+IAgiVIBNAAIgsCVgAaAi/QBNgJAtgPQgugUgsgRIAfgsIg5AAIAAg6IBdAAIAUgkIhiAAIAAihIBUAAIAAglIhcAAIAAg6IFPAAIAAA6IheAAIAAAlIBVAAIAAChIi8AAIAoALIgQAZIC0AAIAAA6Ig4AAQgRAngaAfIBeAlIgkA9Ihwg0QhCAmhqAQQgLgdgTgkgAb2kVIBGAZQAUgSAPgaIhaAAgAd+m+IAjAAIAAgxIgjAAgAcim+IAjAAIAAgxIgjAAgAbGm+IAjAAIAAgxIgjAAgAcionIAjAAIAAglIgjAAgAXEi2QAXg0ADhGQAEhGAAhZIAAi1ICaAAIAAHAQAAAjgRANQgRAOg5gBQgFgggKgnIAdACQASAAAAgbIAAhIIgnAAQAABsgpBFQgZgigUgWgAYdlwIAkAAIAAhIIgkAAIAABIgAYdn4IAkAAIAAhHIgkAAgAGRh/IAAkGQhHBXhpBKQgSgZgmgwQCuhxBBiQIjXAAIAAhLIH2AAIAABLIjDAAQgSAtgZAqIAbAAIAABBIA2g0QBKBCBoBgIg/A/QhGhRhjhaIAAEVgAtGi7IBSABQARAAAMgDQAMgDACgTIkLAAIAMiDIgsAAIAAg5IAyAAIAIhXIgaAbQgSgagbgfQBJhKAlhPIBNALIgQAfID6AAIAAA7IkdAAQgNATgPASIEbAAIgBCEIArAAIAAA5IgsAAIgCBLIApAAIAAA4IgrAAQgCAqgQAQQgQAQgeADQgeADhXABIgRg5gArrksIghAhIBFAAIABhLIhjAAIA+AqgAuHkLIBmAAQgegXgcgUIAjggIhIAAgArqmxIgjAiIBIAAIABhMIhjAAIA9AqgAt6mPIBdAAIg8gtIAigfIg8AAgAxkiYQAchaAZh0QAiAPAkALQgZBcgaBuQgjgMglgKgEghhgC7IBSABQARAAAMgDQAMgDACgTIkLAAIAMiDIgsAAIAAg5IAyAAIAIhXIgaAbQgSgagbgfQBJhKAlhPIBNALIgQAfID6AAIAAA7IkeAAQgMATgPASIEbAAIgCCEIAsAAIAAA5IgtAAIgBBLIApAAIAAA4IgrAAQgCAqgQAQQgQAQgeADQgeADhXABIgRg5gEggGgEsIghAhIBFAAIABhLIhjAAIA+AqgEgijgELIBnAAQgegXgcgUIAjggIhIAAgEggFgGxIgjAiIBIAAIABhMIhjAAIA9AqgEgiVgGPIBdAAIg8gtIAigfIg8AAgEgl/gCYQAchaAYh0QAjAPAkALQgZBcgaBuQgjgMglgKgAhti2IirAAIAAiDQgPgQgPgNIAACdIg7AAIAAgkIgeAAIAAAvIg9AAIAAnAICWAAIAAEBQAngiAcgpIggAAIAAjTIEqAAIAADTIjBAAQgHAPgJAOIDkAAQgBBTgEBtQAABQg5AEQgUACg8ABIgJgygAjzlPIAWAAIAABlICpAAIAAAoQAaAAABghIAGiAIhJAAIgIARIBJA5IgjAqIhAg4QgXAggeAaQgNgRgcgZQAqgiAagqIhLAAgAmPkcIAeAAIAAkTIgeAAgAjQnvIClAAIAAgcIilAAgAjQo4IClAAIAAgcIilAAgA2iiRQg4AAgfgUQgfgWAAgpQAAhGCbhrIiEAAIAAhDIACAAQgegbgVgPIAAFCIhCAAIAAgpIgsAAIAAAvIhDAAIAAm0ICxAAIAABsQA5hHAjhUIBLAWQgKAYgMAXIC8AAIAABDIjiAAQgWAhgXAcIDkAAIAABAQi/CHAAAoQAAAaAwAAIA6AAQAXAAAOgJQAPgJAEgUQAEgUAGg6QAjANAnAJQgHAzgKAkQgKAmgbAPQgcAQgvAAgA6gkvIAsAAIAAj6IgsAAgAxvnVIAtg0QApAeAtAnIgxA7IhShMgEgmKgHVIAtg0QApAeAtAnIgxA7IhShMgAP9oTQCRhEBXhAIA6BEQh0BCiCA5gAxgpoIAvgzQArAgAsAmIgyA3QgmgkgugmgEgl7gJoIAvgzQAqAgAtAmIgyA3Qgmgkgugmg");
	this.shape_2.setTransform(258.7,95);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AkRJUQBHgiAygvQgmg6gWhJQgHAOgJAMQgUgggagiIAAFDIhHAAIAAieQhGAjghAbIgghGQAUgQABgZIAAkVIBDAAIAAEVIAvgaIAAkxIBHAAIAADPQA8hXAgh7IBMANQgKAlgMAjIC5AAIAABJIgkAAQgSCMg5BeQAxAuBEAbQgYAhgZAqQhBgkgzg1Qg2A3hKAmQgSgogZgigAikEqQARBcAqBBQAnhCAShpIhsAAIgIAOgAxuJiQBVg4BNhUIBAAyQhXBchUA6gEgi6AJUQBIgiAxgvQglg6gWhJIgRAaQgUgggagiIAAFDIhHAAIAAieQhFAjgiAbIgghGQAUgQABgZIAAkVIBEAAIAAEVIAugaIAAkxIBHAAIAADPQA9hXAgh7IBLANQgKAlgMAjIC8AAIAABJIglAAQgRCMg8BeQAyAuBFAbQgYAhgYAqQhFgkgyg1Qg1A3hLAmQgSgogZgigEghMAEqQARBcApBBQAohCARhpIhsAAIgHAOgAswIGIA2gxQBgBIBJBEIg+A7QhPhPhShHgACsJVQDHhaATilIjRAAIAAhMIDZAAQADg6AAhPIBTAAQgCBRgDA4IDiAAIAABMIjbAAQAuC3C1A/QgmAsgYAfQiVhGg7ibQgsCOilBXQgWgbgogrgASTKaIAAizIgwAAIAAAjIhFAAIAAhGIgqAqIgnguIAADaIhFAAIAAi0QgZA1geArQgJgkgQg0QAzg8AbhOIhJAAIAAhHIBLAAIAAg9Ig+AGQgFglgIgbQBdgKBlgOIAQBAIhCAKIAABFIBBAAIAABHIhBAAIAAAyIARgTQAlAiAbAcIAAjVIB1AAIAAhrIBGAAIAABrIBzAAIAAEeIhDAAIAAgjIgwAAIAACzgATZGkIAwAAIAAh1IgwAAgARjGkIAwAAIAAh1IgwAAgA6NKaIAAjGQgnAogxAqQgMg0gMglQBuhbAthLIiFAAIAAhJIBrAAQgUgigUgeIA/ggQASAYAfAuIgvAaIBcAAIAABDQgXAugmAwIAAAdIAXgcQAmAZAvAlIgvA2Ig9g1IAADbgAY+KRQgJgogMgrQAyAFAtAAQAuAAgBgwIAAhYIjrAAIAAhLIDrAAIAAhAICFhKIlKAAIAAhJIHNAAIAABJIi1BsIAAAeIDbAAIAABLIjbAAIAABoQAAA5gZAbQgYAbg0AAgA2AKPQhKAAAAhNIAAm6IBLAAIAAGoQAAAcAbAAIAPAAQAcAAAGgXQAJg0AFg0QAhAPAsAPQgKBGgQAsQgNAyhJAAgAw0HFIAAkvIGqAAIAAEvgAvjGBIEIAAIAAinIkIAAgAQIjFQBHgjAygvQgmg6gVhIIgRAaQgTghgbghIAAFDIhGAAIAAieQhHAigiAbIgfhGQAVgPAAgaIAAkUIBDAAIAAEUIAwgaIAAkwIBGAAIAADOQA8hXAhh7IBKANQgJAlgMAkIC7AAIAABJIgkAAQgRCMg8BdQAxAvBGAbQgYAhgYAqQhEglgzg0Qg1A3hLAlQgTgogYghgAR2nvQAQBbAqBCQAohDARhoIhsAAIgHAOgEgiRgClQA8hCA5hQIkvAAIAAhJIGaAAIAABCQg9BWhZBsgEAkggB9IAgiUIBOAAIgtCUgAlLh9IAAkIIh5AAIAAhIIHVAAQgGCUgDAhQgDAigNAWQgPAUgaAIQgZAIh5gBQgFgjgMguQA4AEAkAAQAWAAALgJQAMgJADgRQABgSAChGIixAAIAAEIgAGSh+IAAkGQhHBYhpBKQgRgagmgvQCthxBBiRIjXAAIAAhLIH2AAIAABLIjDAAQgSAugZAqIAbAAIAABAIA2g0QBKBCBpBhIhAA+QhGhQhjhbIAAEVgAxujTIA2guIAAiXIgzAAIAAhIIB9AAIAADeQAoAwBFAAIBTAAQBWAACKgCIgZBJIk3gEQgmgBgcgMQgdgNgSgYIhCBDgAY0h/IAAjGQgmAogxAqQgMg0gMgmQBuhaAshMIiEAAIAAhJIBrAAQgUghgUgeIA/ghIAxBGIgwAaIBdAAIAABDQgXAuglAxIAAAdIAWgcQAmAZAvAkIgvA2Ig8g1IAADcgA3xh/IAAh0IkDAAIAAhFIBMAAIAAiHQgOAQgQAPQgVgggdgmQBUhEAthzIBUANQgJAYgLAWIFFAAIAABGIivAAIAABIICbAAIAABGIibAAIAABWIDAAAIAABFIjAAAIAAB0gA5bk4IBqAAIAAhWIhqAAgA6VnUICkAAIAAhIIhuAAQgXAmgfAigAdCiLQhKAAAAhMIAAm7IBLAAIAAGoQAAAcAaAAIAPAAQAeAAAEgWQALg0AEg1QAhAPAsAPQgLBGgPAtQgOAxhHAAgAt2k0QBCAFAXAAQAqAAAAgtIAAigIjbAAIAAhDIDbAAIAAhaIBPAAIAABaIBPAAIAABDIhPAAIAAC2QAAAugWAZQgVAXgoACIhrABQgHgjgNgsgAvEnIIA9gtQAkAqA6BKIhAAxQgpg5gyg/gEgjCgHkIA8gpQAxAzAeAoIhBArQgvg+gbgfgEgmNgHZQCSg/BgiBIBrAAIgSASQBTBwCIA7QgYAfgaAkQiOhGhOhwQhWBwiQBKQgdgtgVgXgAiXnrIAAguIhyAAIAAAuIhQAAIAAguIiEAAIAAhHICEAAIAAg5IBQAAIAAA5IByAAIAAg5IBRAAIAAA5IB/AAIAABHIh/AAIAAAugAxep3IA+glQApA5AcAuIhGAoQgeg4gfgyg");
	this.shape_3.setTransform(258.6,94.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AG3K2IAAhFQASAJAVAAQAkAAAPgjIAQgoIh6ktIBiAAIA8C9QAEARADAVIACAAQACgOAHgXIA8i+IBYAAIh9FJQgrBzhXAAQgiAAgTgIgAgBK7IAAm5IBXAAIAAAuIABAAQAig2BAAAQA6AAAgAoQAhAoAABHQAABLgmAtQgmAvg9gBQg3ABgdgtIgBAAIAACwgABoFVQgUAXAAAlIAAAaQAAAfASAVQASAUAcABQAgAAATgaQATgaAAguQAAhUhCAAQgeAAgSAXgAnUK7IAAm5IBZAAIAAAuIABAAQAjg2A/AAQA6AAAhAoQAgAoAABHQAABLgmAtQglAvg+gBQg3ABgdgtIgBAAIAACwgAlpFVQgUAXAAAlIAAAaQAAAfASAVQASAUAcABQAgAAATgaQATgaAAguQAAhUhCAAQgeAAgSAXgAXcI9QAkhHAAiGIBGAAQAAAwgEAqQAOAiAYAVIAAinIiKAAIAAhDIBrAAIAAgyIhYAAIAAhEIBYAAIAAhGIBKAAIAABGIBSAAIAABEIhSAAIAAAyIBhAAIAABDIhFAAIAAA9IA+AAIAABDIg+AAIAABFQAbAEBXAAQBSAACLgDQgOAkgNApQjaABhYgGQhXgFgmg+QgLAwgTAmIg6g+gA/qI9QAkhHAAiGIBGAAQAAAwgEAqQAOAiAYAVIAAinIiKAAIAAhDIBqAAIAAgyIhXAAIAAhEIBXAAIAAhGIBLAAIAABGIBRAAIAABEIhRAAIAAAyIBhAAIAABDIhFAAIAAA9IA+AAIAABDIg+AAIAABFQAbAEBXAAQBSAACKgDQgOAkgMApQjaABhYgGQhXgFgmg+QgLAwgTAmIg6g+gEAm4AI1IBTACQAhAAAAghIAAljIj4AAIAAg8IFBAAIAAGTQAABmhHAFQg8AEgsAAQgGgpgIgbgEAiAAJ5IAAmzIBJAAIAAGzgEAlYAJXIAAjMIgzAAIAACXIg/AAIAAjPIByAAIAAguIiBAAIAAg8ICCAAIgOgeIBJgUIARAyIB5AAIAAA8IiDAAIAAAuIB0AAIAACHQgBBHhCAAIglgBIgKg9IAiABQARAAAAgaIAAg/Ig1AAIAADMgAtxIfQgagZAAgqQAAhXBngOIBTgLQAAg1g3AAQg2AAgvAhIAAhEQAUgMAjgGQAhgIAZAAQB+AAAAB/IAAC3IhTAAIAAgsIgBAAQgfA0g8gBQgrABgZgZgAsKGnQgvAGAAAlQAAARALAKQAMALAUAAQAbAAARgUQARgSAAgdIAAgWgAx2IwIAAitQAAhFgzAAQgZAAgQAUQgRATAAAeIAACtIhZAAIAAnAIBZAAIAADAIABAAQAjg2A6AAQBnAAAAB8IAAC6gAdPIEQhKAAAAhOIAAiqICLAAIAAhQIiWAAIAAhCIDgAAIAADUIiLAAIAABaQAAAaAcAAIAZAAQAWAAAHgMQAHgMADhHQAtATAeALQgIBAgKATQgPAwhFAAgA53IEQhKAAAAhOIAAiqICLAAIAAhQIiWAAIAAhCIDgAAIAADUIiLAAIAABaQAAAaAcAAIAZAAQAVAAAIgMQAGgMADhHQAuATAeALQgIBAgKATQgQAwhEAAgANYGTIAAhRIIRAAIAABRgEgpuAGTIAAhRIIQAAIAABRgEAihACFIA1gsQAqApAfAgIg7AyQgegoglgngEgpvgDZQBug+AJh/Ih8AAIAAhIIB8AAIAAhvIhjAJQgEgegIgrQCYgLCOgUIARBHIh3AOIAAB5ICUAAIAAjaIBRAAIAADaIBrAAIAABIIhrAAIAADyIhRAAIAAjyIiUAAQgHCliBBWQgfgighgcgAnVjJQA4g4AAhmIAAi7QB9gMBNgZIAfBAQhDAPhgAKIAAA7IClAAIAABAIgrAAIAADSIhHAAIAAjSIgzAAQAACHhABPQgdgWghgWgA1cjqQBEhhACjOIg/AAIAAhIIBBAAIABhbIBGAAIAABbIB8AAIgIFdQgCAogPATQgPAVgUAEQgWAFhAAAIgThSQAiADAWgBQANAAAIgFQAGgFACgKQACgLAChJIADi2Ig1AAQgDEDhfB5QgUglgXgogEAgzgCeIAgiUIBNAAIgtCUgAFbieIAAgTIkbAAIAAATIhIAAIAAiLIGtAAIAACLgABAjfIEbAAIAAgcIkbAAgAZnjkQgpAmgzAeQgKgSgSgbIAAAsIhIAAIAAoGIExAAQAAA4gDAmQgDAngWATQgVAUglABIhbgBQgFgcgKgnQAwAEAeAAQAUAAAKgJQAIgJAAgaIidAAIAACEIDxAAIAAA9QgYBOgxA/QAsAdA3ARQgUAfgaArQg3gbgugpgAXvjuQAngTAfgXQgkgsgdg3IAvgiQAaAzAmAmQAhgpARg0IimAAgA8KjFQA1hHAjhUIA9AbQgwBmgqA+QgkgYgXgMgA9QihIAAhYIiNAbIgNhKIAcgDIAAkyIgWAAIAAhAIDtAAIAABAIgXAAIAAEUIAggFQgEApAAAdIgcAEIAABjgA+Nk0IA9gJIAAg3Ig9AAgA+NmwIA9AAIAAg4Ig9AAgA+NokIA9AAIAAg5Ig9AAgATejsIAlACQAOgBAFgGQAGgGAAgOIAAhhIg7AQIgIhQIBDgMIAAhiIg7AAIAAhHIA7AAIAAhhIBGAAIAABhIA2AAIAABHIg2AAIAABUIA5gMQgDAwABAZIg3AMIAACOQAAAlgTAQQgTARhLABQgFgagOgwgAMyiiIAAi1QhDBXhyBBQgZglgYgdQBrgtBKhRIirAAIAAhHIB6AAQgWgdgogvIAzglIhVAAIAAhHIDCAAIAAg9IBPAAIAAA9IDFAAIAABHIhYAAIA2AoQglAtgfAcICCAAIAABHIizAAQBMBPBtAoQgZAggYAlQh0g/hChVIAAC1gAOBnGIBYAAIgxgpQAigfAhgpIhqAAgAMMntIg2AnIBcAAIAAhxIhpAAQAgAgAjAqgA5YlDIA4gcQAvBPApBOIg+AgQgphagphHgAqQjdQgJATgIANQgZgQgagMQAcgxAQgqIA4AVIgcA8IAbABQAVAAAAgUIAAhBIhmAAIAAg2IBmAAIAAgiIhuAAIAAg3IA7AAIgVgiIBGAAIAXAiIAhAAQAKgQAIgSIBNAAIgZAiIA2AAIAAA3IhrAAIAAAiIBiAAIAAA2IhiAAIAABaQAAAygzAFQgSACgrABQgDgcgIgegAwyirIAAnjIDeAAIAAHhIhKAAIAAgtIhKAAIAAAvgAvokiIBKAAIAAkkIhKAAgAoMkbIAtgYQAMAPAaAqIgwAdQgUgngPgXgAg9lBIAAgxIB6AAIgQggIAkgGIhTAAIAAh1IGhAAIAAB1IhUAAIAmAHIgbAfICHAAIAAAxgACWlyIBpAAIAagmIiZAAQALARALAVgABGnHIEPAAIAAgYIkPAAgA7lmCIAAkXID+AAIAAEXgA6fnDIByAAIAAiVIhyAAgArBn2IAAg2IBnAAIgIggIAqAAIAAgOIiVAAIAAg+ICVAAIAAgjIBHAAIAAAjIBmAAIAAgjIBIAAIAAAjICVAAIAAA+IiVAAIAAAYIhIAAIAAgYIhmAAIAAAYIgoAAIAFAWIBeAAIAAA2gAgVonIAAgtIC8AAIAAgaIjaAAIAAgzIDaAAIAAgcIBNAAIAAAcIDcAAIAAAzIjcAAIAAAaIC8AAIAAAtg");
	this.shape_4.setTransform(261.8,98.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAIJxQA+g8AghnIhdAAIAAg+IIdAAIAAA+IjkAAIAAAhIC6AAIAAA8Ii6AAIAAAjIBYABICNgBQgOAkgIAcQgnABhlgBIhPgBQh+AAg5g8QgaAugeAfIg/gtgACtHoIgRAuQAjAlA5AMIAAh5IiQAAgA27KeIAgiVIBNAAIgtCVgEAkMAKdIAAkHQgUAggXAhQgMg4gOgwQBHh0Aqh+IBLATQgSA8gYA3IAAGagAlDJpQAhgkAXgvIgtAhQgXghgaghIAABjQABAZgNAPQgOARgfABQggACggAAQgDgYgFgWQgigMgbgIQAYhEAQhHIA/AQQgQBDgQAyQAoACAGgHQAFgHgBgLIAAh8IhcAAIAAilIDoAAIAAClIhHAAIAAAwIArgfIA3BDQAkhTADhwIguAAIAAhEIAwAAIABiGIBIAAIgDCGICJAAIAABEIiKAAIgCAlIA1AAIAADTQgBANANAAQAKAAAEgMQADgLAEhPIA9AUQgKBmgHAQQgJAPgNAJQgPAHgYAAIgUAAQg9AAAAhEIAAivQgUCahOBkQgcgbgegZgAnHGAIBjAAIAAgzIhjAAgEgkiAKdIAAgdIjhAAIAAAdIhFAAIAAmWIBoAAIAAgzIhyAAIAAgIIgxA0QgtgogmggIAugxQA2AoAgAaIAAgzIGHAAIAAA+Ih4AAIAAAzIBmAAIAAGWgEgoDAJGIDhAAIAAgmIjhAAgEgoDAHmIDhAAIAAgfIggAAQg/gBAAhCIAAhCIgjAAQgDBZguA+QgbgbgTgQgEgoDAGkQAgguABg0IghAAgEglDAF3QAAAVAVAAIAMAAIAAhKIghAAgEgmiAEHIAhAAIAAgzIghAAgEAnAAKbQgGgsgIggQAdADAugBQAeAAAAgjIAAh8IimAAIAAhJICmAAIAAgwIBchXIjdAAIAAhIIE8AAIAABNIhuBsIAAAWICBAAIAABJIiBAAIAACcQABAUgGAPQgFAQgOALQgOAMgpABQgfADgjAAIgXgBgEgi4AJZQAdgvALg4QALg7AAhyIAAivIG+AAIAACpIlxAAIAAAhIGJAAIgDDcQAAAqgNASQgMASgRAIQgRAJh4gBQgFghgKgmIBMADQARAAAKgGQAIgHADgJQADgKAAhZIABg+Ik8AAQABChhBBbQgkgpgagZgEgg4AEAIEkAAIAAgrIkkAAgAsHJGQgvAgg0AcQgRgfgcghQBBgbA2gmQgPg9gGhhIhvAAIAAA8IBdgNQgBAZAAATIABAeIhdALIAABuQAAAegNAPQgOAQgjADQgkACgwABQgJgxgLgYQAaADAcgBIALAAQAKAAAFgGQAFgIAAgPIAAhBIhWANIgOhNQAygEAygHIAAhFIhjAAIAAhGIBjAAIAAg2IhNAGIgKhGQB7gHBwgRIARBFQgnAGgtAFIAAA+IBqAAIgHibIBNAAQADBPAEBMICzAAIAABGIixAAQAEA+AIAsQAwgsAmg4IA7AwQg2BFhFA5QAWA0AbAAIAIgCQAFgCAHgcQAHgbAGgoQAmAaAcALQgPBTgVAdQgTAdgkAAQhOAAgphUgAJ3KWIAAjyQgTAhgWAfIgXhpQBDhtAqiMIBJAXQgUA+gZA8IAAGDgAWdJCQAoADAuABQANAAAJgDQAKgEAGgFQAHgHACgIQACgHABg8IADhwIABhVIhfAAQgSAngUAkQgbgRgmgRIAAFGIhNAAIAAgnIhNAAIAAAqIhMAAIAAm9IA5AAQAQg1AHghIBRAMIgZBKIBeAAIAABrQArhKAph4IBLAUQgMAjgOAkICNAAIgGE6QgBA0gGAUQgIAUgPAMQgPANgbAFQgbAFhbAAQgIgwgMgjgATJIjIBNAAIAAhdIhNAAgATJF+IBNAAIAAheIhNAAgEgrgAJ9QAehUAdh9QAuARAdAIQgdB5geBWQgogNgjgKgAd9JBQBrAEAnABQAYAAALgJQAKgJAEgLQAFgNADh2IlrAAIARi0IBVAAIgLBwIC5AAIAPiHIk3AAIAAhFIGTAAIgVDMIBXAAQgDCfgEAwQgEAwgcAXQgdAYgvABQgxAChpAAQgHgngNgrgAMxKSQgFgfgJgnQAbACATAAQAUAAAIgFQAHgFAAgQIAAkLIBLAAIAAEhQABAhgNASQgNAQgfADQgXACglAAIgaAAgEggYAJfIAAiiIDiAAIAACIIicAAIAAAagA/SITIBWAAIAAglIhWAAgAPUGGIBEgRQAWA7ApB/IhMAYQgchvgbhSgALQIlQAnhQAehmIBHASQgdBogqBaQgegPgngPgAacIXIAAhHIGJAAIAABHgAV5GRIA/grQAoAuAuBEIhFAtQgqhEgmgwgEgroAFHIAtg1QA9AuAjAfIgzA4QgwgtgqgjgALTFIQA0hRAkhzIBNAKIgSA3IDlAAIAAA/IgZBhIhJgPIAVhNIi1AAQgcA9giAwQgVgUgjgagABIF2IAAjmIGeAAIAADmgACVE5IEFAAIAAgeIkFAAgACVDqIEFAAIAAgdIkFAAgAriC8IAvguQBAA0AfAgQgfAdgUAVQgogtgzgrgAiQCzIAugmQAjAiAkAmIgxAsQgfgmglgogAohD3IAAhAIBpAAIgNgxIBRgIIAMA5IBfAAIAABAgAuzi5QDNgzBvhtIA2AuQh4B5jQA7IgqhCgAU0h8IAgiUIBOAAIgtCUgA27h8IAgiUIBNAAIgtCUgANch+IAAhcIhYAAIAAg7QgWAggYAcIgog9IAACXIhCAAIAAjxQgRAggTAbQgGgzgMg1QAshRAtirIBHATQgTBGgVA8IAADfQBYhcAqh7IhjAAIAAhEICPAAIAAhZIBIAAIAABZICdAAIAABEIh1AAQAqB1BiBaQgXAjgZAqQgWgWgTgcIAAA4IhbAAIAABcgAOkkfIBSAAQgyhMgghvgAMLkfIBRAAIAAi9QgaBng3BWgEgrogDAQBNgjAjgnQAlgmAEhEIhjAAIAAkOIGwAAIAAEOIhuAAIAAB9QAAApAegBIAWAAQARABAHgOQAHgQAIhFQAeANAvAPQgLA9gKAbQgNA2hKAAIg6AAQhRAAAAhbIAAiSIhBAAQgFBdgqA3QgpA3hZArQgTgagkgogEgpmgG6IEWAAIAAiDIkWAAgEAnpgDKQAwACAoAAQAfAAAAgfIAAgIIjpAAIAABuIhPAAIAAjwQgkAlgqAhIgShWQBShFAyhXIh/AAIAAhEICiAAQAMgdAJgeIBYAMIgUAvIEbAAIAABEIk8AAIgYAoIEgAAIAAEpQABAigSATQgPASgeADQgdADhVAAQgHgmgPglgEAl3gEqIDpAAIAAgoIjpAAgEAl3gGNIDpAAIAAgnIjpAAgAnih/IAAoUIBAAAIAABgIA2AWIgTA/IgjgSIAAFxgA/Qh/IAAiiQhFBeh7A8IguhDQBtgtA8hAIiOAAIAZiwIC6AAIAAgwIjHAAIAAhCIBnAAIgegnIBCgcIA0BDIBgAAQAZghAWgiIBLAcIgjAnIBgAAIAACyIjDAAIAAAvIDdAAQgCBIgDApQgCApgWAVQgVATgeADQgeADhFgCQgIgigLglQAjAFAkAAQAVAAAPgKQAOgJAAgwIiQAAIAAC4gEghPgF4IB/AAIAAgvIh4AAgA+EnnIB3AAIAAgwIh3AAgAbRiAIAAiAIg3AAIAAhBIA3AAIAAjZICyAAIAAglIjcAAIAAhCIIEAAIAABCIjdAAIAAAlICzAAIAADZIA2AAIAABBIg2AAIAAAnQAAAmgQAVQgPAVgbADQgbAEhQAAQgFgpgJgfQAtACAWAAQAaAAAGgKQAFgMAAgMIAAgWIkaAAIAACAgAfOlBIBoAAIAAgtIhoAAgAcclBIBnAAIAAgtIhnAAgAfOmtIBoAAIAAgtIhoAAgAccmtIBnAAIAAgtIhnAAgAliiBIAAkUIE/AAIAAETIhKAAIAAgaIiqAAIAAAbgAkXjWICqAAIAAglIiqAAgAkXk0ICqAAIAAgmIiqAAgAEliCIgNhGQAmACAsAAQAfAAAAgeIAAgqQiTBPjJA4QgWgxgSgZQCfgeB6g0IkSAAIAAhCIBAAAIAAkEIB4AAIAbgyIBWAJIgaApIC4AAIAADeQAXgRATgUIAuA1QgoAigwAeIAABfQAABZhSABgACWllIDzAAIAAghIjzAAgACWm3IDzAAIAAggIjzAAgACWoHIDzAAIAAghIjzAAgAxXjyIA/gNIAAh8IgzAAIAAhLIAzAAIAAhlIg6AAIAAhLIC/AAIAABLIg7AAIAABlIAqAAIAABLIgqAAIAABqQAagHAbgJQgCAjABAqQhfAZhTAYgAuSksQCFgzBehRIA1AtQhpBZiFA9QgOgdgcgigAuSmaQBbgoBKhAIAwAuQhMBDhhAyQgMgVgcgmgAosmNQARhRAHhSIAtAEQgKBcgNBNIgugKgAl2myIAAg7IBAAAIAAgxIg4AAIAAg8IA4AAIAAg9IBKAAIAAA9IBTAAIAAg8IBMAAIAAA8IA2AAIAAA8Ig2AAIAAAxIBCAAIAAA7gAjsntIBTAAIAAgxIhTAAgAu6oCQBng6A4heIBRAAIgIAMQBBBYBdAqQgRAbgVAoQhng3g5hTQg4BXhjA/QgPgkgWghg");
	this.shape_5.setTransform(258.2,91.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.ani1_元件1烦烦烦 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFF6C3").s().p("ACTEoQgggQgDgcQgBgNAagEQAVgGADgCIAJgXQAEgQAAgZQAAgUgJhCIg7AAQgZABgPgJQgWgIgLgMQgMgOgDgSQAAgYAegbQAXgJAiAAQAdADATAAIAAACQAGguAhgwIAMgpQgBgGgbABQhJAGgRAAQhXgLgVhEQAFg8CagEQAmAAAvAEQBAARAJATQArAdAEA3QAAAdgZAcQgVAggUAbQgbAdgDAGQAWAAAOgDQAIgDAPAAQAZABARADQAuAFAAAOQAAAXgcAlQgIANgKAIIgLAHQgZAJgQADIgdAAQAGAmADBEQAAAxgEAsQAAAog7AAQgZAAgogUgAimEkQgRgJABgRQACgWAEgQIgHAAQgngEglgMQgZgHgegOQgtgegCgfQAAhUAhhTQAEgVAEgHIADAAQghgCgJgJQgigWABgoQAJgUAagLQAdgRAdAAIALAAIAPgwQAoggA1gFQAuATAAAaQgBAagEAOIAbAAQBZAAAMAbQAfAbABASQAAAcgoAUQgpAYg6AEQgbAAgYgEQghBhgJAzQABAcAbAGQAEADAPAAQAGgfAHhIQAQglAbAAQAjAEAKAXQAXAcAAAaQgCAbgLAdQAQgEAUgIQAdABAAAbQAAAdg1ARQgQAHgNACQgVBFgUAMQgPAIgRAAQgNAAgKgIg");
	this.shape.setTransform(215.4,112.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFF6C3").s().p("AgcEbQgRgJgDgKQAAgKAKgLQAHgMAFgLQAFgIAAg9IgHgwIgIghQAAgRALgVQAKgSAPgDQAfAAAFAJQAEADANA7QALA5ALBwQAAAWgTAJQgVAKgUAAQgPAAgcgJgACmCcQgfgagNgcQgGgPAAgTQAEgOAUgEQAVgDALAAQApAAAvAMQAfAXADAeQACANAAASQAAASgTAIQgUAMgWAAQgcAAgpgZgAkoB5QADgPAcgcQAagvAogoQAwg4A3gvQg3gFhAgUQhTgXgFg4QAFgfAjgVQBCgXAgAAQAhAABHALQA2AFBAADIBlAMQBTADAWADQAhAPAIAnQAAAXgkAPQgVAPghAGQgjAEggAJQgfAGggACQgiAAggADQABAAAAAGQAAAQgHAOQgGAUgHAIQgHAXgyAjQhOA+gmAZQgyAxguAEQgaAAAAgYg");
	this.shape_1.setTransform(132.9,117.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFF6C3").s().p("ACaE0QgigQgDgdQAAgOAagFQAWgGADgCIAKgXQAEgRAAgbQAAgUgKhFIg8AAQgbAAgQgJQgXgIgLgMQgNgPgCgSQAAgaAegcQAYgJAkAAQAeADAUAAIAAACQAGgwAigyIANgrQgBgFgcAAQhNAHgRAAQhbgMgWhIQAFg9ChgEQAoAAAxADQBDASAJAUQAtAeAFA6QAAAegcAdQgVAigVAcQgcAdgEAHQAYAAAOgDQAJgDAQAAQBbADAAAVQAAAXgdAnQgMAUgTAJQgZAJgRAEIgeAAQAGAnADBIQAAAzgEAuQAAApg9AAQgaAAgqgVgAiuEwQgQgJAAgSQACgWAFgSIgHAAQgqgDgmgNQgagHgfgPQgvgfgCghQAAhXAihXQAFgWAEgHIADAAQgigDgKgJQgjgWAAgqQAKgWAbgLQAegRAfAAIALAAIAQgyQApgiA3gFQAxAUAAAbQgCAbgEAPIAcAAQBdAAAMAcQAiAcAAASQAAAegpAVQgrAZg8AEQgcAAgagEQgjBlgJA1QACAdAbAHQAFADAQAAQAGghAIhLQAPgnAdAAQAlAFAKAYQAYAdAAAcQgCAbgMAfQAQgEAVgIQAfAAAAAdQAAAeg4ARQgQAIgOACQgVBIgWAMQgPAJgSAAQgNAAgMgJg");
	this.shape_2.setTransform(46.8,113.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFF6C3").s().p("AgnFiQgdgEgqgMQghgHgNgjQAFgdAjAAQAdAFAyADQA1AHAvAAQAXAABJgNQAsgLAFgUQAAikgUgeQgPgQg6AAQhagIgXAAQgRAAguAIQg4AKgSABIAAACQAAAZgGAdQANgDAWAAQBHAAAcAHQApAJAAAiQAAAniZAAQgZAAgHgEIgEAeQgJBKgMARQgSAagoAAQgkAAgagmQgMgdgGg9QgFg1AAhcQAAhRBJAAQAgAAARALQAPgTA0gIIAUgDQgagSAAguQAEgeAPgTQg3gHhCgUQhbgcgHg8QAHggAngVQBGgbAjAAQAkAABPAMQA9AHBIAEQA3AHA5ADQBfAEAXAEQAjAPAJAsQAAAdgmAMQgXARgmAIQglADgjALIhCAIQgoAAgpAEQgNAEgEAAQgCALgIAXQgOApgXASQgGAIgIAFIATgBQCKAABrAKQBVAIAIAmQASAuACDLQAAA6hLAZQhEAah9AAQgvAAgqgEg");
	this.shape_3.setTransform(211.4,35.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFF6C3").s().p("Al1ABQAAg0CTgQQByAACTgGQBOAABBAIQBKAGA+AKQA5AWADArQAAAYhDATQhJANg1AAQh6ACheAAQlSgPAAg6g");
	this.shape_4.setTransform(121,34.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFF6C3").s().p("AhZE2QgdgBgHgQQADgKACgSIALgOIAAAAIAAAAQgDgMgLgZIgMgfQgNgegKgeQgOACgXgEIgBADQgDAYg6AQQgvAMgdhUQgZhfABgLQAGgnAogSQAggBAqAlQAXAGAZBYIABAFQAQAAAhgJQAygNAEgMQARgKgJgfQgDgJgMABQgLgBgvANQgegBgRgNQgPAAgGgYQgIgdAtgWQANgEA9gDIA7gDQAfABAXBZQAMAtgQAWQgQAcgnAOIgUAGQAOAIAQAnQASAqATBCQAGAUgMAMQgMAPgSAFQgQAEgWAAIgJAAgAjfElQgbgKgEgPQgFgWAKgcQAKgUAPgVQALgHALgDQATgFAJAaQARAZACAIQAGAXgQAZQgNAXgRAFIgIABQgJAAgLgFgAAlDBQgOgCgPgIQgagNgIgbQADglAYgIQBGgPAVAfQAAhLAHg/QADgSAGgNIgJACQglAGgYgFQghgJgFgZQABgbApgPQApgLAggLIAJhFQAEgTAUgGQAXAEANARQASAYADANQACAHgDACIAxgOQA9gMALAqQACATgPAKQgLAKgPAIIhSAdIAAAKQgDA1gMArQgGAtgNAlQgYA2gIAKQgJAGgLADQgNAAgHgMIgCAGQgHASgQAEQgKADgKAAQgIAAgIgCgAECCRQgZgOgKglQgFgRgFhQQABggADgUQAOgNASgFQAYACALAPQASAOAEARQADALgFAhIACArQAEANAMAMQAEADAigGQAggIAFAUQAKAjhaAYQgpAAgSgKgAllhTQgSgFgVgdQgIgqArgRIBSgOQgHgQgKgjQgBgSATgWQAmgWAYgGQAZgCAYALQAhAHAGAXQAHAaAAAPIBGgTQANgDATAIQALAEAEAOQADAOgXAXQgKAUgMAIQgzAnhFATQhoAcgxAAQgbAAgLgJgADvjIQgMgDgNgHQgagOgIgfQACgaAWgKQBJgMAPA6QAEANgHAOQgFAPgNADQgIACgHAAQgJAAgIgCg");
	this.shape_5.setTransform(39.2,34.3,1,1,0,0,0,-0.7,-3.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFF6C3").s().p("ACaFAQgZgEgkgaQgegVABgcQACgNAaAAQAVgDAEgCIANgUQAGgQADgZQADgTAChCIg6gJQgZgEgOgLQgVgMgIgNQgKgPABgQQAEgaAggWQAYgGAjAFQAcAJATADQAMgsAogqIASgmQAAgGgbgEQhKgFgQgCQhWgagLhGQAOg6CcAUQAlAGAuALQA9AaAFAVQAnAjgEA3QgFAdgeAXQgZAdgYAXQgfAYgEAHQAWADAOgBQAJgCAPACIAoAKQAtAMgCANQgDAVgiAjQgKAMgMAGIgMAFQgZAFgRABIgcgEQAAAlgIBFQgHAwgLAsQgFAggnAAQgJAAgLgCgAjCD6QgNgCgJgKQgPgMADgQQAFgVAHgQIgHgBQgmgJgigSQgZgLgagTQgogjACggQAOhQAshQQAIgUAEgGIAEABQgggIgIgKQgegbAGgnQANgTAbgHQAfgMAdAEIALACIAWgtQAsgaA1AEQArAZgEAbQgFAZgGANIAaAEQBYANAGAdQAeAfgDASQgEAcgqAOQgtARg6gFQgagEgYgHQgwBcgQAvQgDAcAZAKQAEAEAPACQALgeAShDQAVgkAbAFQAiAKAGAYQASAdgEAaQgGAZgPAcQAQgCAVgEQAfAFgEAbQgFAdg6AIQgQAFgNAAQgfBBgWAIQgMAFgLAAIgJgBg");
	this.shape_6.setTransform(215.4,112.2,1,1,0,0,0,-0.8,-2.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFF6C3").s().p("AAVEdQgTgGgCgJQgBgKAFgMQAGgNADgNQAEgIgJg8IgLguQgKgWgDgKQgCgQAHgXQAHgTAPgGQAfgFAGAJQAFACAUA5QATA3AbBtQADAWgQALQgUANgUADIgKABQgNAAgWgEgAkKCkQABgQAXgfQATgyAigvQAog9Avg2Qg4AEhCgMQhVgLgNg3QAAgfAggZQA+ghAggFQAhgEBHAAQA2gCBAgGIBlgEQBTgJAXAAQAiALAOAlQADAWgiAUQgSASggALQgiAJgeANQgeALgfAHQgiAFgfAHIACAGQACAQgFAOQgDAVgGAKQgEAXgsArQhDBIgjAdQgpA4guALIgHAAQgTAAgDgUgADECEQgigWgRgZQgIgOgDgTQACgOATgHIAfgIQApgGAwAFQAiASAHAeQAFANACARQADASgSAKQgSAQgWADIgKAAQgaAAgkgPg");
	this.shape_7.setTransform(132.9,117.3,1,1,0,0,0,0.9,0.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFF6C3").s().p("ADCFLQgagBgpgZQgggSgCgeQABgNAbgDQAWgEADgCQAEgFAIgSQAEgRACgaQABgVgEhEIg9gEQgagCgPgKQgXgKgKgNQgMgPgBgTQABgZAhgaQAYgIAkACQAeAGAUABQAKguAkgwIAQgpQAAgGgdgCQhNACgRgBQhcgSgPhJQAJg9ChAHQAnACAxAIQBCAVAHAVQAsAhAAA6QgCAegdAaQgYAhgWAbQgeAbgEAIQAXABAOgCQAKgDAQABQBbAJgCAVQgBAVggAnQgOATgTAIQgZAIgSADIgegCQAEAmgCBIQgDAzgHAuQgCAmgzAAIgLgBgAiuEiQgOgBgLgJQgQgLABgRQAEgWAGgRIgHgBQgpgGglgQQgagIgegRQgtgiAAghQAHhXAmhUQAHgXAEgGIAEAAQgigFgJgJQgigZADgqQALgVAcgJQAfgPAfACIALAAIATgxQArgeA4gCQAvAXgCAbQgDAbgFAPIAcABQBcAHALAcQAfAfgBASQgCAegrASQgsAWg8AAQgcgCgZgFQgqBhgMA1QAAAeAaAIQAEADARABQAIggAMhKQATgkAdACQAkAHAJAXQAVAegCAbQgEAcgNAeQAQgDAWgHQAgACgBAdQgCAeg8AOQgQAGgOABQgZBHgXALQgOAHgPAAIgEgBg");
	this.shape_8.setTransform(46.8,113.6,1,1,0,0,0,-0.5,-1.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFF6C3").s().p("AgvFuQgtgKgrgOQgbgLgngVQgdgPgFgkQAMgbAiAIQAaALAxAOQA0AUAtAKQAUAGBKADQAuAAAJgSQAmifgMgiQgMgTg4gOQhVgcgVgGQgTgEgugDQg5gCgRgDIgBABQgGAZgMAaQANAAAWAFQBFAQAZAPQAoASgIAhQgJAmiXgkQgYgGgGgFIgKAcQgaBGgQAOQgXAVgngJQgjgIgQgsQgGgfAJg9QAGg0AVhXQAUhRBHARQAgAHAMAPQAUgPA0AEIAVACQgWgYALgtQALgdATgOQg0gTg8gkQhSgvAHg9QAOgdArgLQBLgLAiAIQAiAIBKAfQA4AVBHAUQA0AUA3AQQBbAaAVAJQAfAWgBAtQgHAcgoAEQgaAKgmgBQglgFglADIhCgHQgngJgpgGIgQAAIgUAeQgVAkgbANQgHAGgJAEIASACQCHAhBlAgQBRAcgBAmQAGAzgsDGQgNA5hPAGQgTADgWAAQg/AAhYgWg");
	this.shape_9.setTransform(211.4,35.9,1,1,0,0,0,-1.5,0.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFF6C3").s().p("AlyAxQgHg0CPgiQBxgOCRgXQBOgKBCAAQBJgEA/ADQA7AOAIAtQADAYhAAYQhHAWg0AHQh5ARhdAMQhqAIhJAAQifAAgFgng");
	this.shape_10.setTransform(121,34.7,1,1,0,0,0,-0.2,0.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFF6C3").s().p("AipE4QgbgJgDgRIAMgZIAOgMQAAgMgEgbIgEghQgFgggBggQgOgCgWgKQABAAAAAAQAAABAAAAQgBABAAAAQAAABgBAAQgJAXg8AAQgxAAgHhZQABhiAFgLQAPgjAsgIQAfAIAeAuQAWAMAABbIAAAFQAPAEAiAAQA0AAAIgJQASgGAAgjQAAgHgMgCQgLgDgxAAQgcgJgNgRQgPgEAAgZQAAgeAygJQANAAA8AMIA6AMQAcAJAABbQAAAxgTARQgYAWgqADIgVABQAMAMAFApQAHAtABBFQAAAUgOAJQgQAMgTAAQgUAAgagIgAkmEEQgXgQAAgQQAAgWARgZQAPgQAUgRQAMgEAMAAQATAAADAcQAJAdAAAHQAAAYgWAUQgTATgRAAQgNAAgNgLgADQDyQgUgTAAgnQAAgSAQhQQAJgfAJgSQAQgJATAAQAXAJAGARQAOARAAASQAAAMgOAgIgKAqQAAANAKAPQADAEAhADQAiAAAAAWQAAAkhdAAQgogLgPgPgAgPDoQgNgGgMgMQgZgTAAgdQAMgjAcAAQBFADANAkQAShJAYg8QAIgRAKgMIgKAAQgmgDgWgKQgdgRAAgaQAKgZArgEQArAAAigCIAahBQAJgRAVAAQAVAJAIAUQALAcAAANQAAAIgDAAIAzAAQA9AEAAArQgDATgRAGQgNAHgQAEIhYAEIgCAKQgRAzgXAoQgRAqgWAgQglAugLAIQgKAEgLAAQgNgEgDgNIgFAFQgLAPgQAAQgSAAgPgIgAEYhgQgKgGgLgKQgWgVAAggQAKgYAXgDQBKAHAAA8QAAANgLAMQgJANgNAAQgRAAgOgJgAlGiJQgQgKgNghQAEgrAugFIBSAHQgDgQAAglQADgSAZgQQAqgLAYAAQAZAEAVARQAeAQAAAXQAAAcgFAOIBIAAQANAAAQANQAKAGAAAOQAAAPgdAQQgPARgLAFQg7AZhIAAQimAAgYgfg");
	this.shape_11.setTransform(39.2,34.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6}]},6).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,254.8,146.6);


(lib.role2_元件37 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role2_Bitmap10();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,8,8);


(lib.role2_元件35 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role2_Bitmap9();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,39,23);


(lib.role2_元件34 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role2_Bitmap2();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,30,20);


(lib.role2_元件33 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role2_Bitmap3();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,30,20);


(lib.role2_元件31 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role2_Bitmap8();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,30,103);


(lib.role2_元件30 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role2_Bitmap6();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,51,93);


(lib.role2_元件28 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role2_Bitmap7();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,40,73);


(lib.role2_元件27 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role2_Bitmap4();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,91,25);


(lib.role2_元件25 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role2_Bitmap1();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,235,129);


(lib.role2_补间17 = function() {
	this.initialize();

	// 图层 1
	this.instance = new lib.role2_Bitmap11();
	this.instance.setTransform(-79.1,-97.2);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-79.1,-97.2,158,194);


(lib.ani2_wenzimc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 5 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A+hKKIAAimICeAAIglpZIomCTIBDlxIGuhXIgWjrIGKh9IAAE3IEagsIAfD+Ik5BMIAAM6IjPCvgAS7KaICiuEIALACIJ3AlIidIBIkfANIgKBhIM8AvIh1EegAYrBnIBtAAIAhhmIiYgQgA2PGkIBBigIKGEQIlsDHgAn2GaIGLjbIA2BAIAnAAIAAhPIF2gOIASl2Il0gQIAAhoIgmACIilDyIAlAnIBIgaIA4BbImnE/IjNjDIB8i9IiwiBIE6p5ID6CKIjLFHIAfAVIB9iiIDCA+IADACIALghIN7giIA2ErIlPgLIAAFgIGFAAIBBDdIxIClIAAjJIgkgIIl7F3gEglUAGUIGTiEIAACwIjbC/gAfPFiIAzpXIq3guIivFBIiEhzIDbqjIETAsIhUDyIOAgpIhlNwgEgkPAB3ICghkIBtCTIhHA7gA2cBxIDVkHIDqCYIldC8gA19o3IgHgTIBKjdICzBhIiJCPg");
	mask.setTransform(-15.9,47.1);

	// 图层 6
	this.instance = new lib.ani2_yj3();
	this.instance.setTransform(-309.2,-50.6,0.999,0.999,25,0,0,34.7,260.6);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:275.5,y:153},14).wait(16));

	// 图层 8
	this.instance_1 = new lib.wenzi();
	this.instance_1.setTransform(-267.4,-216.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(30));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-267.4,-216.4,534.9,369);


(lib.ani2_sanbai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 1
	this.instance = new lib.ani2_faguang();
	this.instance.setTransform(154.4,307.5,1,1,0,0,0,324,547.5);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},3).to({alpha:0},4).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-169.6,-240,648,1600);


(lib.ani2_元件57 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 1
	this.instance = new lib.ani2_元件56();
	this.instance.setTransform(47.5,109.1,0.097,0.097,0,0,0,47.5,109);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(39).to({_off:false},0).to({regY:109.1,scaleX:1.09,scaleY:1.09},6).to({scaleX:0.98,scaleY:0.98},3).to({scaleX:1,scaleY:1},2).wait(35).to({scaleX:1.07,scaleY:1.07},4).to({regX:47.4,regY:109.4,scaleX:0.06,scaleY:0.06},4).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.ani2_ani1_哈哈哈哈 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 1
	this.instance = new lib.ani2_ani1_我擦擦();
	this.instance.setTransform(72.9,13.9,1,1,0,0,0,72.9,13.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0.531},14).to({alpha:1},15).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,315,36);


(lib.ani2_倒计时 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 2
	this.instance = new lib.ani2_元件11a();
	this.instance.setTransform(81.4,131.2,1.423,1.235,0,0,0,61.1,134.8);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(59).to({_off:false},0).to({scaleX:0.4,scaleY:0.4,x:72.4,y:131.1},30,cjs.Ease.get(1)).to({_off:true},1).wait(9));

	// 图层 3
	this.instance_1 = new lib.ani2_元件12a();
	this.instance_1.setTransform(64.9,132.4,1.423,1.235,0,0,0,61.1,134.8);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(29).to({_off:false},0).to({regY:134.9,scaleX:0.4,scaleY:0.4},29,cjs.Ease.get(1)).to({_off:true},1).wait(40));

	// 图层 1
	this.instance_2 = new lib.ani2_元件13b();
	this.instance_2.setTransform(62,135.2,1.423,1.235,0,0,0,61.1,134.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({regX:61,scaleX:0.4,scaleY:0.4,y:135.1},28,cjs.Ease.get(1)).to({_off:true},1).wait(70));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-8.7,50.2,143.8,176.5);


(lib.role2_元件32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 2
	this.instance = new lib.role2_元件34();
	this.instance.setTransform(142.3,17.1,1,1,0,0,0,15.2,10.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.88,scaleY:0.88,y:17},19).to({scaleX:1,scaleY:1,y:17.1},20).wait(1));

	// 图层 1
	this.instance_1 = new lib.role2_元件33();
	this.instance_1.setTransform(15.2,10.1,1,1,0,0,0,15.2,10.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleX:0.84,scaleY:0.84},19).to({scaleX:1,scaleY:1},20).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,157.1,27);


(lib.role2_元件26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 3 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("ACeBdQhOgwAjiYIGJAjQgXCwh9ATQgiAFgfAAQhRAAg4gjgAm1BHQhTgrAPibIGdAGQgZDAh2AVQgnAHgkAAQhHAAg4gcg");
	mask.setTransform(50.9,12.9);

	// 图层 1
	this.instance = new lib.role2_元件27();
	this.instance.setTransform(56.9,13,1,1,0,0,0,45.6,12.7);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:49.6,y:12.3},19,cjs.Ease.get(1)).wait(30).to({x:56.9,y:13},20).wait(11));

	// 图层 2
	this.instance_1 = new lib.role2_Bitmap5();

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(80));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,102,26);


(lib.role2_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 2
	this.instance = new lib.role2_元件25();
	this.instance.setTransform(111.1,99.7,1,1,0,0,0,111.3,99.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:4.8,x:104.6},19).wait(30).to({rotation:0,x:111.1},20).wait(11));

	// 图层 5
	this.instance_1 = new lib.role2_元件32();
	this.instance_1.setTransform(97.5,162.2,1,1,0,0,0,78.8,13.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regY:13.6,rotation:2.1,x:94.4,y:162.3},19).wait(30).to({regY:13.5,rotation:0,x:97.5,y:162.2},20).wait(11));

	// 图层 6
	this.instance_2 = new lib.role2_元件26();
	this.instance_2.setTransform(99,156.3,1,1,0,0,0,50.9,25.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({regX:50.8,rotation:2.3,x:95.2,y:156.4},19).wait(30).to({regX:50.9,rotation:0,x:99,y:156.3},20).wait(11));

	// 图层 8
	this.instance_3 = new lib.role2_元件30();
	this.instance_3.setTransform(68.9,209.2,1,1,0,0,0,25.4,46.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({x:64.1},19).wait(1).to({regX:8.3,regY:82.9,x:47,y:245.8},0).to({scaleY:1.02},5).to({scaleY:1},5).to({scaleY:1.02},5).to({scaleY:1},5).to({scaleY:1.02},4).to({scaleY:1},4).wait(1).to({regX:25.4,regY:46.3,x:64.1,y:209.2},0).to({x:68.9},20).wait(11));

	// 图层 7
	this.instance_4 = new lib.role2_元件28();
	this.instance_4.setTransform(39.4,219.1,1,1,0,0,0,19.9,36.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({x:35.1},19).wait(30).to({x:39.4},20).wait(11));

	// 图层 9
	this.instance_5 = new lib.role2_元件31();
	this.instance_5.setTransform(186.7,238.3,1,1,0,0,0,14.8,45.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({x:180.7},19).wait(30).to({x:186.7},20).wait(11));

	// 图层 10
	this.instance_6 = new lib.role2_元件35();
	this.instance_6.setTransform(97.2,182.6,1,1,0,0,0,19.4,11.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({rotation:4.8,x:95.4},19).wait(30).to({rotation:0,x:97.2},20).wait(11));

	// 图层 11
	this.instance_7 = new lib.role2_元件37();
	this.instance_7.setTransform(103.7,161,1,1,0,0,0,4,4);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({x:100},19).wait(30).to({x:103.7},20).wait(11));

	// 图层 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1D5165").s().p("AgdAeQgNgNAAgRQAAgQANgOQANgLAQAAQARAAANALQANAOAAAQQAAARgNANQgNANgRgBQgQABgNgNg");
	this.shape.setTransform(90.8,160.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#1D5165").s().p("AgdAeQgMgNAAgRQAAgQAMgOQAMgLARAAQASAAAMALQAMAOAAAQQAAARgMANQgMANgSgBQgRABgMgNg");
	this.shape_1.setTransform(90.6,160.6);
	this.shape_1._off = true;

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#1D5165").s().p("AgdAeQgNgNAAgRQAAgQANgOQANgLAQAAQASAAAMALQAMAOAAAQQAAARgMANQgMANgSgBQgQABgNgNg");
	this.shape_2.setTransform(90.2,160.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#1D5165").s().p("AgdAeQgMgNgBgRQABgQAMgOQAMgLARAAQARAAANALQANAOAAAQQAAARgNANQgNANgRgBQgRABgMgNg");
	this.shape_3.setTransform(88.9,160.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#1D5165").s().p("AgdAeQgNgNABgRQgBgQANgOQAMgLARAAQARAAANALQANAOAAAQQAAARgNANQgNANgRgBQgRABgMgNg");
	this.shape_4.setTransform(87.6,160.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#1D5165").s().p("AgeAfQgNgNAAgSQAAgRANgOQANgNARAAQASAAANANQAMAOAAARQAAASgMANQgNANgSAAQgRAAgNgNg");
	this.shape_5.setTransform(87.2,160.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#1D5165").s().p("AgeAgQgOgNAAgTQAAgSAOgOQANgNARAAQATAAANANQANAOAAASQAAATgNANQgNAOgTAAQgRAAgNgOg");
	this.shape_6.setTransform(87.2,160.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#1D5165").s().p("AgfAhQgOgNAAgUQAAgSAOgPQANgOASAAQATAAANAOQAOAPAAASQAAAUgOANQgNAPgTAAQgSAAgNgPg");
	this.shape_7.setTransform(87.2,160.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#1D5165").s().p("AggAiQgPgOAAgUQAAgTAPgQQAOgOASABQAUgBANAOQAPAQAAATQAAAUgPAOQgNAPgUAAQgSAAgOgPg");
	this.shape_8.setTransform(87.2,160.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#1D5165").s().p("AghAkQgOgPAAgVQAAgUAOgQQAOgOATAAQAUAAAOAOQAOAQABAUQgBAVgOAPQgOAPgUAAQgTAAgOgPg");
	this.shape_9.setTransform(87.2,160.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#1D5165").s().p("AgeAfQgNgNAAgSQAAgSANgNQANgNARAAQASAAANANQANANAAASQAAASgNANQgNAOgSAAQgRAAgNgOg");
	this.shape_10.setTransform(87.2,160.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#1D5165").s().p("AgfAhQgOgOAAgTQAAgSAOgOQAOgOARAAQATAAANAOQANAOAAASQAAATgNAOQgNAOgTAAQgRAAgOgOg");
	this.shape_11.setTransform(87.2,160.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#1D5165").s().p("AggAiQgOgOAAgUQAAgTAOgQQAOgNASAAQAUAAANANQAOAQAAATQAAAUgOAOQgNAPgUAAQgSAAgOgPg");
	this.shape_12.setTransform(87.2,160.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#1D5165").s().p("AgdAeQgNgNAAgRQAAgQANgOQAMgLARAAQARAAANALQANAOAAAQQAAARgNANQgNANgRgBQgRABgMgNg");
	this.shape_13.setTransform(89.4,160.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2,p:{x:90.2}}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_4,p:{x:87.6}}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2,p:{x:87.5}}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_4,p:{x:88.5}}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_13,p:{x:89.4}}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_13,p:{x:90.3}}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape}]},1).wait(11));
	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},1).wait(5).to({_off:false,x:89.7},0).wait(1).to({x:89.5},0).to({_off:true},1).wait(5).to({_off:false,x:88.3},0).wait(1).to({x:88.1},0).to({_off:true},1).wait(1).to({_off:false,x:87.8},0).to({_off:true},1).wait(32).to({_off:false,x:87.2},0).to({_off:true},1).wait(9).to({_off:false,x:89},0).to({_off:true},1).wait(4).to({_off:false,x:89.9},0).to({_off:true},1).wait(2).to({_off:false,x:90.5},0).to({_off:true},1).wait(1).to({_off:false,x:90.8},0).wait(11));
	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1).to({_off:false},0).wait(1).to({x:90.4},0).to({_off:true},1).wait(1).to({_off:false,x:90.1},0).wait(1).to({x:89.9},0).to({_off:true},1).wait(2).to({_off:false,x:89.3},0).wait(1).to({x:89.1},0).to({_off:true},1).wait(1).to({_off:false,x:88.7},0).wait(1).to({x:88.5},0).to({_off:true},1).wait(2).to({_off:false,x:87.9},0).to({_off:true},1).wait(2).to({_off:false,x:87.4},0).wait(1).to({x:87.2},0).wait(1).to({_off:true},1).wait(9).to({_off:false},0).to({_off:true},1).wait(4).to({_off:false,scaleX:1.14,scaleY:1.21},0).to({_off:true},1).wait(4).to({_off:false,scaleX:1,scaleY:1},0).to({_off:true},1).wait(3).to({_off:false,scaleX:1.14,scaleY:1.21},0).to({_off:true},1).wait(3).to({_off:false,scaleX:1,scaleY:1},0).to({_off:true},1).wait(1).to({_off:false,x:87.4},0).to({_off:true},1).wait(1).to({_off:false,x:87.7},0).wait(1).to({x:87.9},0).wait(1).to({x:88.1},0).wait(1).to({x:88.3},0).to({_off:true},1).wait(1).to({_off:false,x:88.6},0).wait(1).to({x:88.8},0).to({_off:true},1).wait(1).to({_off:false,x:89.2},0).to({_off:true},1).wait(1).to({_off:false,x:89.5},0).wait(1).to({x:89.7},0).to({_off:true},1).wait(1).to({_off:false,x:90.1},0).to({_off:true},1).wait(2).to({_off:false,x:90.6},0).to({_off:true},1).wait(11));

	// 图层 3
	this.instance_8 = new lib.role2_补间17("synched",0);
	this.instance_8.setTransform(110.4,285.2,1,1,0,0,0,0,97.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({regX:0.1,rotation:-3.5},19).wait(30).to({startPosition:0},0).to({regX:0,rotation:0},20).wait(11));

	// 图层 12
	this.instance_9 = new lib.role2_Bitmap12();
	this.instance_9.setTransform(73.8,223.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(80));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.2,0,235,323.9);


(lib.ani2_11231231231 = function() {
	this.initialize();

	// 图层 2
	this.instance = new lib.role2_2();
	this.instance.setTransform(127.5,152.9,1.077,1.077,0,0,0,117.3,161.9);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(1,-21.5,253.1,348.7);


(lib.ani2_gezhongmc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{aniend:676});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_239 = function() {
		playSound("sound01");
	}
	this.frame_676 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(239).call(this.frame_239).wait(437).call(this.frame_676).wait(1));

	// 图层 12
	this.instance = new lib.lg();
	this.instance.setTransform(-114,-480);

	this.instance_1 = new lib.ani2_wenzimc();
	this.instance_1.setTransform(5.1,-238.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).to({state:[]},155).wait(522));

	// 图层 8
	this.btn = new lib.btn001();
	this.btn.setTransform(-6,313.7,1,1,0,0,0,149.5,82.5);
	this.btn._off = true;

	this.timeline.addTween(cjs.Tween.get(this.btn).wait(663).to({_off:false},0).wait(14));

	// 图层 5
	this.instance_2 = new lib.ani2_sanbai("synched",0,false);
	this.instance_2.setTransform(1.9,-3.4,1,1,0,0,0,156.8,272);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(250).to({_off:false},0).wait(14).to({regX:0,regY:0,x:-154.9,y:-275.4},0).wait(12).to({startPosition:0},0).wait(15).to({startPosition:0},0).wait(14).to({startPosition:0},0).wait(11).to({startPosition:0},0).wait(9).to({startPosition:0},0).wait(8).to({startPosition:0},0).wait(9).to({startPosition:0},0).wait(7).to({startPosition:0},0).wait(10).to({startPosition:0},0).wait(11).to({startPosition:0},0).wait(18).to({startPosition:0},0).wait(28).to({startPosition:0},0).wait(26).to({startPosition:0},0).wait(8).to({startPosition:0},0).wait(6).to({startPosition:0},0).wait(7).to({startPosition:0},0).wait(7).to({startPosition:0},0).wait(14).to({startPosition:0},0).wait(24).to({startPosition:0},0).wait(16).to({startPosition:0},0).wait(6).to({startPosition:0},0).wait(8).to({startPosition:0},0).wait(8).to({startPosition:0},0).wait(9).to({startPosition:0},0).wait(12).to({startPosition:3},0).wait(9).to({startPosition:0},0).wait(76).to({startPosition:0},0).wait(10).to({startPosition:0},0).wait(15));

	// 图层 11
	this.instance_3 = new lib.ani2_倒计时("synched",0,false);
	this.instance_3.setTransform(0,-34,1.878,1.878,0,0,0,63,128);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(155).to({_off:false},0).to({_off:true},90).wait(432));

	// 图层 9
	this.instance_4 = new lib.ani2_ani1_哈哈哈哈();
	this.instance_4.setTransform(-60.1,329.7,1,1,0,0,0,72.9,13.9);

	this.instance_5 = new lib.ani2_元件57();
	this.instance_5.setTransform(-24.3,-143,0.716,0.716);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_4}]}).to({state:[]},155).to({state:[{t:this.instance_5}]},508).wait(14));

	// 图层 15
	this.gtInfoMc = new lib.ani1_gtInfoMc();
	this.gtInfoMc.setTransform(25.3,186.9,1,1,0,0,0,279.1,142.1);

	this.timeline.addTween(cjs.Tween.get(this.gtInfoMc).to({_off:true},155).wait(522));

	// gtInfoMc
	this.instance_6 = new lib.ani2_wenzimc();
	this.instance_6.setTransform(-1.6,128,0.958,0.958);

	this.instance_7 = new lib.ani2_11231231231();
	this.instance_7.setTransform(-16,-36.3,1.183,1.183,0,0,0,114.6,129.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_7},{t:this.instance_6}]},658).wait(19));

	// headMc
	this.nickTxt = new cjs.Text("", "bold 45px 'Microsoft YaHei'", "#FFFF00");
	this.nickTxt.name = "nickTxt";
	this.nickTxt.lineHeight = 47;
	this.nickTxt.lineWidth = 439;
	this.nickTxt.setTransform(-141.3,-29.8);

	this.headMc = new lib.ani1_headMc();
	this.headMc.setTransform(-197.6,-16.5,1,1,0,0,0,51.3,51.3);

	this.instance_8 = new lib.jiu();
	this.instance_8.setTransform(-110,-141.1);

	this.instance_9 = new lib.yi();
	this.instance_9.setTransform(-100,-81.9);

	this.instance_10 = new lib.bai();
	this.instance_10.setTransform(-94.7,-153.2);

	this.instance_11 = new lib.hao();
	this.instance_11.setTransform(-107.1,-122.2);

	this.instance_12 = new lib.bu();
	this.instance_12.setTransform(-109.2,-136.1);

	this.instance_13 = new lib.hao2();
	this.instance_13.setTransform(-116.4,-121.1);

	this.instance_14 = new lib.jiuyibai();
	this.instance_14.setTransform(-251.7,-202.1);

	this.instance_15 = new lib.ani1_元件1烦烦烦();
	this.instance_15.setTransform(7.3,-328.7,1.874,1.874,0,0,0,127.5,73.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.headMc},{t:this.nickTxt}]}).to({state:[]},150).to({state:[{t:this.instance_8}]},466).to({state:[{t:this.instance_9}]},6).to({state:[{t:this.instance_10}]},5).to({state:[{t:this.instance_11}]},5).to({state:[{t:this.instance_12}]},5).to({state:[{t:this.instance_13}]},5).to({state:[{t:this.instance_14}]},5).to({state:[{t:this.instance_15}]},11).wait(19));

	// 图层 10
	this.instance_16 = new lib.role2_2();
	this.instance_16.setTransform(55.7,364.7,6.225,6.225,0,0,0,117.4,142.6);
	this.instance_16._off = true;

	this.instance_17 = new lib.x2();
	this.instance_17.setTransform(-242.2,180.7,1,1,-60);

	this.instance_18 = new lib.x1();
	this.instance_18.setTransform(237.2,-202.5,0.998,0.998,137.6);

	this.instance_19 = new lib.x3();
	this.instance_19.setTransform(-255.4,-148.2,0.999,0.999,21.9);

	this.instance_20 = new lib.role2_2();
	this.instance_20.setTransform(21.2,444.6,2.792,2.792,0.5,0,0,117.4,142.8);

	this.instance_21 = new lib.role21_Bitmap2();
	this.instance_21.setTransform(-409.2,-59);

	this.instance_22 = new lib.role21_Bitmap1();
	this.instance_22.setTransform(-389.4,-132.6);

	this.instance_23 = new lib.role21_Bitmap3();
	this.instance_23.setTransform(-360.3,-139.9);

	this.instance_24 = new lib.role21_Bitmap4();
	this.instance_24.setTransform(-335.6,-135.5);

	this.instance_25 = new lib.role21_Bitmap5();
	this.instance_25.setTransform(-373.7,-525.9);

	this.instance_26 = new lib.role2_2();
	this.instance_26.setTransform(13.1,-242.3,2.026,2.136,0,-179.5,0.5,117.3,142.8);

	this.instance_27 = new lib.role2_2();
	this.instance_27.setTransform(12.8,282.2,2.136,2.136,0.5,0,0,117.3,142.8);

	this.instance_28 = new lib.role2_2();
	this.instance_28.setTransform(144.9,230,1.894,2.136,-33,0,0,117.4,143);

	this.instance_29 = new lib.role2_2();
	this.instance_29.setTransform(237.1,-92.5,1.894,2.136,-126.4,0,0,117.4,142.9);

	this.instance_30 = new lib.role2_2();
	this.instance_30.setTransform(6.4,-243.5,1.999,2.136,0,-175.6,4.4,117.4,142.8);

	this.instance_31 = new lib.role2_2();
	this.instance_31.setTransform(-227.8,-81.4,2,2.136,0,104.3,-75.7,117.4,142.8);

	this.instance_32 = new lib.role2_2();
	this.instance_32.setTransform(-225.9,126.9,2,2.136,0,59.3,-120.7,117.4,142.8);

	this.instance_33 = new lib.role2_2();
	this.instance_33.setTransform(13.1,-242.3,2.026,2.136,0,-179.5,0.5,117.3,142.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_16}]},245).to({state:[{t:this.instance_16}]},14).to({state:[{t:this.instance_16}]},12).to({state:[{t:this.instance_16}]},15).to({state:[{t:this.instance_16}]},14).to({state:[{t:this.instance_17}]},11).to({state:[{t:this.instance_18,p:{scaleX:0.998,scaleY:0.998,rotation:137.6,x:237.2,y:-202.5}}]},10).to({state:[{t:this.instance_19}]},10).to({state:[{t:this.instance_19},{t:this.instance_17}]},12).to({state:[{t:this.instance_19},{t:this.instance_17},{t:this.instance_18,p:{scaleX:0.998,scaleY:0.998,rotation:137.6,x:237.2,y:-202.5}}]},9).to({state:[{t:this.instance_19},{t:this.instance_17},{t:this.instance_18,p:{scaleX:0.998,scaleY:0.998,rotation:137.6,x:237.2,y:-202.5}},{t:this.instance_16}]},11).to({state:[{t:this.instance_20,p:{regX:117.4,scaleX:2.792,scaleY:2.792,x:21.2,y:444.6,rotation:0.5,regY:142.8}},{t:this.instance_16}]},11).to({state:[{t:this.instance_16}]},18).to({state:[{t:this.instance_18,p:{scaleX:3.178,scaleY:3.178,rotation:0,x:-612,y:-953}}]},29).to({state:[{t:this.instance_21}]},20).to({state:[{t:this.instance_22}]},8).to({state:[{t:this.instance_23}]},6).to({state:[{t:this.instance_24}]},7).to({state:[{t:this.instance_25}]},6).to({state:[{t:this.instance_16}]},8).to({state:[{t:this.instance_17}]},25).to({state:[{t:this.instance_18,p:{scaleX:0.998,scaleY:0.998,rotation:137.6,x:237.2,y:-202.5}}]},18).to({state:[{t:this.instance_19}]},7).to({state:[{t:this.instance_20,p:{regX:117.3,scaleX:2.136,scaleY:2.136,x:12.8,y:282.2,rotation:0.5,regY:142.8}},{t:this.instance_16}]},7).to({state:[{t:this.instance_27,p:{regX:117.3,scaleX:2.136,rotation:0.5,skewX:0,skewY:0,x:12.8,y:282.2,regY:142.8,scaleY:2.136}},{t:this.instance_26,p:{regX:117.3,regY:142.8,scaleX:2.026,rotation:0,skewX:-179.5,skewY:0.5,x:13.1,y:-242.3,scaleY:2.136}},{t:this.instance_20,p:{regX:117.3,scaleX:2.136,scaleY:2.136,x:267.3,y:-2.3,rotation:-89.5,regY:142.8}},{t:this.instance_16}]},9).to({state:[{t:this.instance_33},{t:this.instance_32},{t:this.instance_31},{t:this.instance_30,p:{regX:117.4,regY:142.8,scaleX:1.999,scaleY:2.136,skewX:-175.6,skewY:4.4,x:6.4,y:-243.5}},{t:this.instance_29,p:{regX:117.4,regY:142.9,scaleX:1.894,scaleY:2.136,rotation:-126.4,x:237.1,y:-92.5}},{t:this.instance_28,p:{regX:117.4,regY:143,scaleX:1.894,scaleY:2.136,rotation:-33,x:144.9,y:230}},{t:this.instance_27,p:{regX:117.4,scaleX:2,rotation:0,skewX:153.9,skewY:-26.1,x:-125.7,y:-201.5,regY:142.8,scaleY:2.136}},{t:this.instance_26,p:{regX:117.4,regY:142.9,scaleX:1.894,rotation:-159.9,skewX:0,skewY:0,x:126.9,y:-192.6,scaleY:2.136}},{t:this.instance_20,p:{regX:117.3,scaleX:2.136,scaleY:2.136,x:277.3,y:55.7,rotation:-74.3,regY:142.8}},{t:this.instance_16}]},8).to({state:[{t:this.instance_16}]},11).to({state:[{t:this.instance_16}]},11).to({state:[{t:this.instance_20,p:{regX:104.1,scaleX:0.484,scaleY:0.484,x:64.2,y:-67.7,rotation:0,regY:165.5}},{t:this.instance_16}]},5).to({state:[{t:this.instance_26,p:{regX:104.1,regY:165.5,scaleX:0.484,rotation:0,skewX:0,skewY:0,x:97.2,y:-74.7,scaleY:0.484}},{t:this.instance_20,p:{regX:104.1,scaleX:0.646,scaleY:0.646,x:19.1,y:-70.9,rotation:0,regY:165.6}},{t:this.instance_16}]},4).to({state:[{t:this.instance_27,p:{regX:104.1,scaleX:0.484,rotation:0,skewX:0,skewY:0,x:153.2,y:-87.7,regY:165.5,scaleY:0.484}},{t:this.instance_26,p:{regX:104.1,regY:165.6,scaleX:0.646,rotation:0,skewX:0,skewY:0,x:74.1,y:-84.9,scaleY:0.646}},{t:this.instance_20,p:{regX:104.1,scaleX:0.891,scaleY:0.891,x:-28.6,y:-77.4,rotation:0,regY:165.6}},{t:this.instance_16}]},4).to({state:[{t:this.instance_28,p:{regX:104.1,regY:165.5,scaleX:0.484,scaleY:0.484,rotation:0,x:153.2,y:-89.7}},{t:this.instance_27,p:{regX:104.1,scaleX:0.646,rotation:0,skewX:0,skewY:0,x:74.1,y:-85.8,regY:165.6,scaleY:0.646}},{t:this.instance_26,p:{regX:104.1,regY:165.6,scaleX:0.891,rotation:0,skewX:0,skewY:0,x:-40.7,y:-104.5,scaleY:0.891}},{t:this.instance_20,p:{regX:104,scaleX:1.46,scaleY:1.46,x:-206.7,y:-52.4,rotation:0,regY:165.5}},{t:this.instance_16}]},4).to({state:[{t:this.instance_29,p:{regX:104.1,regY:165.5,scaleX:0.484,scaleY:0.484,rotation:0,x:153.2,y:-89.7}},{t:this.instance_28,p:{regX:104.1,regY:165.6,scaleX:0.646,scaleY:0.646,rotation:0,x:74.1,y:-85.8}},{t:this.instance_27,p:{regX:104.1,scaleX:0.891,rotation:0,skewX:0,skewY:0,x:-40.7,y:-104.5,regY:165.6,scaleY:0.891}},{t:this.instance_26,p:{regX:104,regY:165.5,scaleX:1.46,rotation:0,skewX:0,skewY:0,x:-210.7,y:-50.4,scaleY:1.46}},{t:this.instance_20,p:{regX:104,scaleX:2.177,scaleY:2.177,x:-93.8,y:62.3,rotation:0,regY:165.5}},{t:this.instance_16}]},4).to({state:[{t:this.instance_30,p:{regX:104.1,regY:165.5,scaleX:0.484,scaleY:0.484,skewX:0,skewY:0,x:153.2,y:-89.7}},{t:this.instance_29,p:{regX:104.1,regY:165.6,scaleX:0.646,scaleY:0.646,rotation:0,x:74.1,y:-85.8}},{t:this.instance_28,p:{regX:104.1,regY:165.6,scaleX:0.891,scaleY:0.891,rotation:0,x:-40.7,y:-104.5}},{t:this.instance_27,p:{regX:104,scaleX:1.46,rotation:0,skewX:0,skewY:0,x:-184.7,y:-52.4,regY:165.5,scaleY:1.46}},{t:this.instance_26,p:{regX:104,regY:165.5,scaleX:2.177,rotation:0,skewX:0,skewY:0,x:-97.8,y:72.3,scaleY:2.177}},{t:this.instance_20,p:{regX:104,scaleX:2.567,scaleY:2.567,x:7.4,y:222.9,rotation:0,regY:165.5}},{t:this.instance_16}]},4).to({state:[{t:this.instance_17}]},5).to({state:[{t:this.instance_18,p:{scaleX:0.998,scaleY:0.998,rotation:137.6,x:237.2,y:-202.5}}]},5).to({state:[{t:this.instance_19}]},6).to({state:[]},5).wait(59));
	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(245).to({_off:false},0).wait(14).to({regY:142.7,scaleX:7.96,scaleY:7.96,x:515.6,y:392.7},0).wait(12).to({scaleX:7.59,scaleY:7.59,x:235.6,y:11.2},0).wait(15).to({scaleX:7.47,scaleY:7.47,x:-118.5,y:-223.2},0).wait(14).to({regX:117.5,scaleX:2.69,scaleY:2.69,rotation:0.5,x:29.8,y:197},0).to({_off:true},11).wait(52).to({_off:false,regX:117.4,regY:142.8,scaleX:2.27,scaleY:2.27,x:8.4,y:273},0).wait(11).to({regX:117.5,scaleX:2.71,scaleY:2.79,rotation:0,skewX:-178.8,skewY:1.2,x:37.5,y:-433.8},0).wait(18).to({regX:117.4,scaleX:9.07,scaleY:9.07,rotation:0.5,skewX:0,skewY:0,x:-4.4,y:-172},0).to({_off:true},29).wait(55).to({_off:false,scaleX:2.67,scaleY:2.67,x:24.9,y:196.7},0).to({_off:true},25).wait(32).to({_off:false,regX:117.3,scaleX:2.03,scaleY:2.14,rotation:0,skewX:-179.5,skewY:0.5,x:13.1,y:-242.3},0).wait(9).to({scaleX:2.14,rotation:90.5,skewX:0,skewY:0,x:-245.6,y:43.8},0).wait(8).to({regX:117.4,scaleX:1.98,rotation:0,skewX:28,skewY:-152,x:-116,y:244.3},0).wait(11).to({regY:142.9,scaleX:2.71,scaleY:2.71,skewX:0,skewY:0,x:30.3,y:190.6},0).wait(11).to({regX:104.1,regY:165.5,scaleX:0.48,scaleY:0.48,x:64.2,y:-67.7},0).wait(5).to({regY:165.6,scaleX:0.65,scaleY:0.65,x:-14,y:-64.9},0).wait(4).to({scaleX:0.89,scaleY:0.89,x:-85.7,y:-62.4},0).wait(4).to({regX:104,regY:165.5,scaleX:1.46,scaleY:1.46,x:-191.7,y:-43.4},0).wait(4).to({scaleX:2.18,scaleY:2.18,x:-105.8,y:46.3},0).wait(4).to({scaleX:2.57,scaleY:2.57,x:9.4,y:212.9},0).wait(4).to({regX:104.1,regY:165.6,scaleX:3.47,scaleY:3.47,x:142.1,y:379},0).to({_off:true},5).wait(75));

	// 图层 14
	this.instance_34 = new lib.dx();
	this.instance_34.setTransform(-319.9,305.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_34).to({_off:true},155).wait(522));

	// 图层 2
	this.instance_35 = new lib.bj();
	this.instance_35.setTransform(-320,-480,1,1.563);

	this.timeline.addTween(cjs.Tween.get(this.instance_35).wait(677));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-445.7,-539.4,765.8,1559.5);


// stage content:



(lib.kardUI2 = function() {
	this.initialize();

	// 图层 1
	this.kardMc = new lib.ani2_gezhongmc();
	this.kardMc.setTransform(320.3,480);

	this.addChild(this.kardMc);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(194.6,690.6,765.8,1559.5);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;