var loading_lib = [];
var main_lib = [];
	
var ani1_lib = [{src:"images/aniUI01_Bitmap1.png", id:"aniUI01_Bitmap1"},
		{src:"images/aniUI01_Bitmap2.png", id:"aniUI01_Bitmap2"},
		{src:"images/aniUI01_Bitmap3.png", id:"aniUI01_Bitmap3"},
		{src:"images/aniUI01_Bitmap4.png", id:"aniUI01_Bitmap4"},
		{src:"images/bj.jpg", id:"bj"},
		{src:"images/d1.png", id:"d1"},
		{src:"images/duquzhong01.png", id:"duquzhong01"},
		{src:"images/dx.png", id:"dx"},
		{src:"images/gr1.png", id:"gr1"},
		{src:"images/gr2.png", id:"gr2"},
		{src:"images/gr3.png", id:"gr3"},
		{src:"images/gr4.png", id:"gr4"},
		{src:"images/greetpic1.png", id:"greetpic1"},
		{src:"images/greetpic2.png", id:"greetpic2"},
		{src:"images/greetpic3.png", id:"greetpic3"},
		{src:"images/greetpic4.png", id:"greetpic4"},
		{src:"images/lg.jpg", id:"lg"},
		{src:"images/role1_Bitmap1.png", id:"role1_Bitmap1"},
		{src:"images/role1_Bitmap10.png", id:"role1_Bitmap10"},
		{src:"images/role1_Bitmap11.png", id:"role1_Bitmap11"},
		{src:"images/role1_Bitmap12.png", id:"role1_Bitmap12"},
		{src:"images/role1_Bitmap13.png", id:"role1_Bitmap13"},
		{src:"images/role1_Bitmap2.png", id:"role1_Bitmap2"},
		{src:"images/role1_Bitmap3.png", id:"role1_Bitmap3"},
		{src:"images/role1_Bitmap4.png", id:"role1_Bitmap4"},
		{src:"images/role1_Bitmap5.png", id:"role1_Bitmap5"},
		{src:"images/role1_Bitmap6.png", id:"role1_Bitmap6"},
		{src:"images/role1_Bitmap7.png", id:"role1_Bitmap7"},
		{src:"images/role1_Bitmap8.png", id:"role1_Bitmap8"},
		{src:"images/role1_Bitmap9.png", id:"role1_Bitmap9"},
		{src:"images/role1_eye.png", id:"role1_eye"},
		{src:"images/role1_p6.png", id:"role1_p6"},
		{src:"images/role1_p7.png", id:"role1_p7"},
		{src:"images/role2_Bitmap1.png", id:"role2_Bitmap1"},
		{src:"images/role2_Bitmap10.png", id:"role2_Bitmap10"},
		{src:"images/role2_Bitmap11.png", id:"role2_Bitmap11"},
		{src:"images/role2_Bitmap12.png", id:"role2_Bitmap12"},
		{src:"images/role2_Bitmap2.png", id:"role2_Bitmap2"},
		{src:"images/role2_Bitmap3.png", id:"role2_Bitmap3"},
		{src:"images/role2_Bitmap4.png", id:"role2_Bitmap4"},
		{src:"images/role2_Bitmap5.png", id:"role2_Bitmap5"},
		{src:"images/role2_Bitmap6.png", id:"role2_Bitmap6"},
		{src:"images/role2_Bitmap7.png", id:"role2_Bitmap7"},
		{src:"images/role2_Bitmap8.png", id:"role2_Bitmap8"},
		{src:"images/role2_Bitmap9.png", id:"role2_Bitmap9"},
		{src:"images/s1btn.jpg", id:"s1btn"},
		{src:"images/s2btn.jpg", id:"s2btn"},
		{src:"images/t1.png", id:"t1"},
		{src:"images/t2.png", id:"t2"},
		{src:"images/wenzi.png", id:"wenzi"},
		{src:"sounds/sound01.mp3", id:"sound01"}];

var ani2_lib = [];
var ani11_lib = [
		{src:"images/b1.png", id:"b1"},
		{src:"images/b2.png", id:"b2"},
		{src:"images/b3.png", id:"b3"},
		{src:"images/bai.png", id:"bai"},
		{src:"images/bj.jpg", id:"bj"},
		{src:"images/bu.png", id:"bu"},
		{src:"images/hao.png", id:"hao"},
		{src:"images/hao2.png", id:"hao2"},
		{src:"images/jiu.png", id:"jiu"},
		{src:"images/jiuyibai.png", id:"jiuyibai"},
		{src:"images/num1.png", id:"num1"},
		{src:"images/num2.png", id:"num2"},
		{src:"images/num3.png", id:"num3"},
		{src:"images/role011_Bitmap1.png", id:"role011_Bitmap1"},
		{src:"images/role011_Bitmap2.png", id:"role011_Bitmap2"},
		{src:"images/role011_Bitmap3.png", id:"role011_Bitmap3"},		
		{src:"images/role1_p1.png", id:"role1_p1"},
		{src:"images/role1_p2.png", id:"role1_p2"},
		{src:"images/role1_p3.png", id:"role1_p3"},
		{src:"images/role1_p4.png", id:"role1_p4"},
		{src:"images/role1_p5.png", id:"role1_p5"},
		{src:"images/woyeyao.png", id:"woyeyao"},
		{src:"images/yi.png", id:"yi"}
	];
var ani21_lib = [{src:"images/bai.png", id:"bai"},
		{src:"images/bj.jpg", id:"bj"},
		{src:"images/bu.png", id:"bu"},
		{src:"images/hao.png", id:"hao"},
		{src:"images/hao2.png", id:"hao2"},
		{src:"images/jiu.png", id:"jiu"},
		{src:"images/jiuyibai.png", id:"jiuyibai"},
		{src:"images/num1.png", id:"num1"},
		{src:"images/num2.png", id:"num2"},
		{src:"images/num3.png", id:"num3"},
		{src:"images/role21_Bitmap1.png", id:"role21_Bitmap1"},
		{src:"images/role21_Bitmap2.png", id:"role21_Bitmap2"},
		{src:"images/role21_Bitmap3.png", id:"role21_Bitmap3"},
		{src:"images/role21_Bitmap4.png", id:"role21_Bitmap4"},
		{src:"images/role21_Bitmap5.png", id:"role21_Bitmap5"},
		{src:"images/woyeyao.png", id:"woyeyao"},
		{src:"images/x1.png", id:"x1"},
		{src:"images/x2.png", id:"x2"},
		{src:"images/x3.png", id:"x3"},
		{src:"images/yi.png", id:"yi"}
];	
var ani3_lib = [
		{src:"images/haobuhao.png", id:"haobuhao"},
		{src:"images/haobuhao2.png", id:"haobuhao2"},
		{src:"images/shareTxt.png", id:"shareTxt"},
		{src:"images/tipsIcon.png", id:"tipsIcon"}
			];
	
		

var kardui1 = [{src:"images/b1.png", id:"b1"},
		{src:"images/b2.png", id:"b2"},
		{src:"images/b3.png", id:"b3"},
		{src:"images/bai.png", id:"bai"},
		{src:"images/bj.jpg", id:"bj"},
		{src:"images/bu.png", id:"bu"},
		{src:"images/dx.png", id:"dx"},
		{src:"images/hao.png", id:"hao"},
		{src:"images/hao2.png", id:"hao2"},
		{src:"images/headimg.jpg", id:"headimg"},
		{src:"images/jiu.png", id:"jiu"},
		{src:"images/jiuyibai.png", id:"jiuyibai"},
		{src:"images/lg.jpg", id:"lg"},
		{src:"images/num1.png", id:"num1"},
		{src:"images/num2.png", id:"num2"},
		{src:"images/num3.png", id:"num3"},
		{src:"images/role011_Bitmap1.png", id:"role011_Bitmap1"},
		{src:"images/role011_Bitmap2.png", id:"role011_Bitmap2"},
		{src:"images/role011_Bitmap3.png", id:"role011_Bitmap3"},
		{src:"images/role1_Bitmap1.png", id:"role1_Bitmap1"},
		{src:"images/role1_Bitmap10.png", id:"role1_Bitmap10"},
		{src:"images/role1_Bitmap11.png", id:"role1_Bitmap11"},
		{src:"images/role1_Bitmap12.png", id:"role1_Bitmap12"},
		{src:"images/role1_Bitmap13.png", id:"role1_Bitmap13"},
		{src:"images/role1_Bitmap2.png", id:"role1_Bitmap2"},
		{src:"images/role1_Bitmap3.png", id:"role1_Bitmap3"},
		{src:"images/role1_Bitmap4.png", id:"role1_Bitmap4"},
		{src:"images/role1_Bitmap5.png", id:"role1_Bitmap5"},
		{src:"images/role1_Bitmap6.png", id:"role1_Bitmap6"},
		{src:"images/role1_Bitmap7.png", id:"role1_Bitmap7"},
		{src:"images/role1_Bitmap8.png", id:"role1_Bitmap8"},
		{src:"images/role1_Bitmap9.png", id:"role1_Bitmap9"},
		{src:"images/role1_eye.png", id:"role1_eye"},
		{src:"images/role1_p1.png", id:"role1_p1"},
		{src:"images/role1_p2.png", id:"role1_p2"},
		{src:"images/role1_p3.png", id:"role1_p3"},
		{src:"images/role1_p4.png", id:"role1_p4"},
		{src:"images/role1_p5.png", id:"role1_p5"},
		{src:"images/wenzi.png", id:"wenzi"},
		{src:"images/woyeyao.png", id:"woyeyao"},
		{src:"images/yi.png", id:"yi"},
		{src:"sounds/sound01.mp3", id:"sound01"}];
var kardui2 = [{src:"images/duquzhong01.png", id:"duquzhong01"},
		{src:"images/role21_Bitmap1.png", id:"role21_Bitmap1"},
		{src:"images/role21_Bitmap2.png", id:"role21_Bitmap2"},
		{src:"images/role21_Bitmap3.png", id:"role21_Bitmap3"},
		{src:"images/role21_Bitmap4.png", id:"role21_Bitmap4"},
		{src:"images/role21_Bitmap5.png", id:"role21_Bitmap5"},
		{src:"images/role2_Bitmap1.png", id:"role2_Bitmap1"},
		{src:"images/role2_Bitmap10.png", id:"role2_Bitmap10"},
		{src:"images/role2_Bitmap11.png", id:"role2_Bitmap11"},
		{src:"images/role2_Bitmap12.png", id:"role2_Bitmap12"},
		{src:"images/role2_Bitmap2.png", id:"role2_Bitmap2"},
		{src:"images/role2_Bitmap3.png", id:"role2_Bitmap3"},
		{src:"images/role2_Bitmap4.png", id:"role2_Bitmap4"},
		{src:"images/role2_Bitmap5.png", id:"role2_Bitmap5"},
		{src:"images/role2_Bitmap6.png", id:"role2_Bitmap6"},
		{src:"images/role2_Bitmap7.png", id:"role2_Bitmap7"},
		{src:"images/role2_Bitmap8.png", id:"role2_Bitmap8"},
		{src:"images/role2_Bitmap9.png", id:"role2_Bitmap9"},
		{src:"images/x1.png", id:"x1"},
		{src:"images/x2.png", id:"x2"},
		{src:"images/x3.png", id:"x3"}];
			